context:
  version: 0.17.8

package:
  name: xeus-python
  version: ${{ version }}

source:
  url: https://github.com/jupyter-xeus/xeus-python/archive/refs/tags/${{ version }}.tar.gz
  sha256: 0f7681a36dac26af2f275e81a49eee2f2be86c4b4e82cb7770b540d2695bd53d

build:
  number: 1

requirements:
  build:
  - ${{ compiler("cxx") }}
  - cmake
  - ninja
  host:
  - python
  - libpython
  - nlohmann_json
  - nlohmann_json-abi
  - xeus
  - xeus-lite >=4.0.1
  - pybind11
  - pybind11_json
  - xtl
  - pyjs >=4.0.1
  - zstd
  run:
  - python
  - xeus-python-shell-lite >=0.6.0,<0.7
  - pyjs-rt >=4.0.1

tests:
- package_contents:
    files:
    - bin/xpython.wasm
    - bin/xpython.js

about:
  license: BSD-3-Clause
  license_family: BSD-3
  license_file: LICENSE
  summary: xeus-python
  homepage: https://github.com/jupyter-xeus/xeus-python

extra:
  recipe-maintainers:
  - DerThorsten
  - martinRenou
