context:
  version: 0.18.2

package:
  name: xeus-python
  version: ${{ version }}

source:
  url: https://github.com/jupyter-xeus/xeus-python/archive/refs/tags/${{ version }}.tar.gz
  sha256: 79053c6ae96b0534b60a0be38f7aef484d2f825374734822c5e36b133f38efad

build:
  number: 0

requirements:
  build:
  - ${{ compiler("cxx") }}
  - cmake
  - ninja
  host:
  - python
  - libpython
  - nlohmann_json
  - nlohmann_json-abi
  - xeus
  - xeus-lite >=4.0.1
  - pybind11
  - pybind11_json
  - xtl
  - pyjs >=4.0.1
  - zstd
  run:
  - python
  - xeus-python-shell-lite >=0.6.0,<0.7
  - pyjs-rt >=4.0.1

tests:
- package_contents:
    files:
    - bin/xpython.wasm
    - bin/xpython.js

about:
  license: BSD-3-Clause
  license_family: BSD-3
  license_file: LICENSE
  summary: xeus-python
  homepage: https://github.com/jupyter-xeus/xeus-python

extra:
  recipe-maintainers:
  - DerThorsten
  - martinRenou
