context:
  version: 0.19.1

package:
  name: xeus-python
  version: ${{ version }}

source:
  url: https://github.com/jupyter-xeus/xeus-python/archive/refs/tags/${{ version }}.tar.gz
  sha256: 7ba188e447eeb7c35e2f1c4eb844fce26e60ad6dc21fddde00783060799777f5

build:
  number: 0

requirements:
  build:
  - ${{ compiler("cxx") }}
  - cmake
  - ninja
  host:
  - python
  - libpython
  - openssl <4
  - nlohmann_json
  - nlohmann_json-abi
  - xeus
  - xeus-lite >=5.0.0
  - pybind11
  - pybind11_json
  - xtl
  - pyjs >=4.0.6
  - zstd
  run:
  - python
  - xeus-python-shell-lite >=0.8,<0.9
  - pyjs-rt >=4.0.6

tests:
- package_contents:
    files:
    - bin/xpython.wasm
    - bin/xpython.js

about:
  license: BSD-3-Clause
  license_family: BSD-3
  license_file: LICENSE
  summary: xeus-python
  homepage: https://github.com/jupyter-xeus/xeus-python

extra:
  recipe-maintainers:
  - DerThorsten
  - martinRenou
  - JohanMabille
