context:
  version: 10.8.12

package:
  name: passagemath-setup
  version: ${{ version }}

source:
- url: https://pypi.org/packages/source/p/passagemath-setup/passagemath_setup-${{ version }}.tar.gz
  sha256: 9cd1822d1b5410deac53679f6a77978073582851fc304a3a532986af503644fb

build:
  script: ${{ PYTHON }} -m pip install .
  noarch: python
  number: 0

requirements:
  build:
  - python
  - crossenv >=1.2
  - cross-python_emscripten-wasm32
  - ${{ compiler("c") }}
  - pip
  - passagemath-abi == ${{ version }}
  host:
  - python
  - setuptools
  - wheel
  - pip
  run:
  - python
  - setuptools
  - jinja2
  - passagemath-abi == ${{ version }}

tests:
- script: pytester
  files:
    recipe:
    - test_passagemath_setup.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run

about:
  summary: 'passagemath: Build system of the Sage library'
  license: GPL-2.0-or-later
  license_file: README.rst
  description: |
    sage-setup: Build system of the Sage library
    ================================================

    This is the build system of the Sage library, based on setuptools.

extra:
  emscripten_tests:
    python:
      pytest_files:
      - test_passagemath_setup.py
  recipe-maintainers:
  - mkoeppe
