context:
  version: 10.0.3

package:
  name: scip
  version: ${{ version }}

source:
  url: https://github.com/scipopt/scip/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 6eb97f4d647b6ef734dc9fbd8d35761de367b68de9d881cfd1bc8f460c0004f1

build:
  number: 0

requirements:
  build:
  - ${{ compiler("cxx") }}
  - cmake
  - ninja
  host:
  - boost-cpp
  - gmp
  - mpfr
  - zlib
  - soplex
  # omitted for now: papilo

tests:
- script:
  - test -d ${PREFIX}/include/scip
- package_contents:
    files:
    - lib/libscip.a

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Mixed integer programming solver
  homepage: https://github.com/scipopt/scip

extra:
  recipe-maintainers:
  - mkoeppe
