context:
  name: libheif
  version: 1.23.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/strukturag/libheif/releases/download/v${{ version }}/libheif-${{ version }}.tar.gz
  sha256: 4c9182b18897617182eed12ab5eb9f9d855b3aa3a736d6bdb31abc034ec7d393
  patches:
  - fix-emscripten-val-set.patch # Fixes error: 'val_set' was not declared in this scope, to remove when https://github.com/strukturag/libheif/pull/1565 is merged

build:
  number: 0
  script: build.sh

requirements:
  build:
  - ${{ compiler('c') }}
  - ${{ compiler('cxx') }}
  - cmake
  - ninja
  - pkg-config
  host:
  - zlib
  - libtiff
  - libpng
  run:
  - zlib
  - libtiff
  - libpng

tests:
- package_contents:
    include:
    - libheif/heif.h
    lib:
    - libheif.a
    files:
    - lib/cmake/libheif/libheif-config.cmake
- script:
  - build_tests.sh
  requirements:
    build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - make
  files:
    recipe:
    - build_tests.sh
    - tests/

about:
  license: LGPL-3.0-or-later
  license_file: COPYING
  summary: ISO/IEC 23008-12:2017 HEIF and AVIF file format decoder and encoder
  description: |
    libheif is an ISO/IEC 23008-12:2017 HEIF and AVIF (AV1 Image File Format) file format decoder and encoder.
    HEIF and AVIF are new image file formats employing HEVC (H.265) or AV1 image coding, respectively, for the
    best compression ratios currently possible.
  homepage: https://github.com/strukturag/libheif

extra:
  recipe-maintainers:
  - Alex-PLACET
