context:
  name: sirocco
  version: '1.0'

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/miguelmarco/sirocco/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 70b1d327258aac2a82c4e466d47e6e3e3efc976454ba6b41f94c8670d4913fe9

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - ${{ compiler("c") }}
  - ${{ compiler('cxx') }}
  - pkg-config
  - autoconf-archive

tests:
  - package_contents:
      files:
        - lib/libsirocco.a
        - include/sirocco.h

about:
  homepage: https://github.com/miguelmarco/sirocco
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Sirocco Is a ROot Certified COntinuator

extra:
  recipe-maintainers:
  - wangyenshu