context:
  name: sirocco
  version: 2.1.1

package:
  name: ${{ name }}
  version: ${{ version }}
  
source:
  url: https://github.com/miguelmarco/SIROCCO2/releases/download/${{ version }}/libsirocco-${{ version }}.tar.gz
  sha256: 83d1dd5622120eda42c475696235dd67be8072a76baad0a70693d9743a659a61

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - ${{ compiler("c") }}
  - ${{ compiler('cxx') }}
  - pkg-config
  - autoconf-archive
  host:
  - mpfr
  - gmp

tests:
  - package_contents:
      files:
        - lib/libsirocco.a
        - include/sirocco.h

about:
  homepage: https://github.com/miguelmarco/SIROCCO2
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Sirocco Is a ROot Certified COntinuator

extra:
  recipe-maintainers:
  - mkoeppe
