context:
  version: 10.8.5

package:
  name: passagemath-flint
  version: ${{ version }}

source:
- url: https://pypi.org/packages/source/p/passagemath-flint/passagemath_flint-${{ version }}.tar.gz
  sha256: 48237a05f657993bb68a558ccefe08c0515f21416a37d06dcb1706a84a6ccf56

build:
  script: ${{ PYTHON }} -m pip install .
  number: 0

requirements:
  build:
  - python
  - crossenv >=1.2
  - cross-python_emscripten-wasm32
  - ${{ compiler("c") }}
  - ${{ compiler("cxx") }}
  - pip
  - passagemath-setup
  - passagemath-environment
  - cython
  - cysignals
  - pkgconfig
  - numpy
  - passagemath-abi == ${{ version }}
  host:
  - python
  - gmp
  - mpfr
  - mpc
  - gsl
  - ntl
  - libflint
  - mpfi
  - numpy
  - cysignals
  - memory-allocator
  - passagemath-categories
  - passagemath-modules
  - passagemath-ntl
  run:
  - python
  - cysignals
  - memory-allocator
  - numpy
  - passagemath-categories
  - passagemath-ntl

tests:
- script: pytester
  files:
    recipe:
    - test_passagemath_flint.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run
    - passagemath-modules
    - passagemath-repl

about:
  license: GPL-2.0-or-later
  license_file: README.rst
  summary: 'passagemath: Fast computations with MPFI and FLINT'
  description: |
    Distribution of a part of the Sage library.
    It provides Cython interfaces to the MPFI and FLINT libraries.
    It also ships the implementation of number fields.

extra:
  emscripten_tests:
    python:
      pytest_files:
      - test_passagemath_flint.py
  recipe-maintainers:
  - mkoeppe
