context:
  name: orjson
  version: 3.11.9

package:
  name: ${{ name }}
  version: ${{ version }}

source:
- url: https://files.pythonhosted.org/packages/source/o/orjson/orjson-${{ version }}.tar.gz
  sha256: 4fef17e1f8722c11587a6ef18e35902450221da0028e65dbaaa543619e68e48f

build:
  number: 0

  files:
    exclude:
    - '**/*.pyi'
    - '**/__pycache__/**'
    - '**/*.pyc'
    - '**/test_*.py'
  python:
    skip_pyc_compilation:
    - '**/*.py'

requirements:
  build:
  - cross-python_${{ target_platform }}
  - cffi
  - setuptools-rust
  - rust-nightly
  - maturin
  host:
  - python
  - openssl
  - cffi
  run:
  - cffi
  - typing_extensions

tests:
- script: pytester
  requirements:
    build:
    - pytester
    run:
    - pytester-run
  files:
    recipe:
    - test_orjson.py

about:
  license: Apache-2.0
  license_file:
  - LICENSE-APACHE
  - LICENSE-MIT
  summary: orjson is a fast, correct JSON library for Python.
  homepage: https://github.com/ijl/orjson
  repository: https://github.com/ijl/orjson
  documentation: https://github.com/ijl/orjson
