context:
  version: 2.11.0

source:
- url: https://github.com/stevengj/nlopt/archive/v${{ version }}.tar.gz
  sha256: 53e552d83e9294d67db37f0f4a23f15933a9ef698485301a18b98b40004cf0de

build:
  number: 0

outputs:
- package:
    name: nlopt   # python
    version: ${{ version }}

  build:
    script: build_python.sh
    files:
      exclude:
      - '**/__pycache__/**'
      - '**/*.pyc'
      - '**/test_*.py'
    python:
      skip_pyc_compilation:
      - '**/*.py'

  requirements:
    build:
    - cross-python_emscripten-wasm32
    - python
    - swig
    - pip
    - numpy
    - cmake
    host:
    - numpy
    - python
    run:
    - numpy

  tests:
  - script: pytester
    files:
      recipe:
      - test_import_nlopt.py
    requirements:
      build:
      - pytester
      run:
      - pytester-run

- package:
    name: libnlopt
    version: ${{ version }}

  build:
    script: build_static.sh

  requirements:
    build:
    - ${{ compiler('c') }}
    - cmake
    - make

  tests:
  - package_contents:
      files:
      - include/nlopt.h
      - lib/libnlopt.a
      - lib/pkgconfig/nlopt.pc

about:
  homepage: https://nlopt.readthedocs.io/en/latest/
  repository: https://github.com/stevengj/nlopt
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: Nonlinear optimization library
  description: |
    Library for nonlinear optimization, wrapping many algorithms for global and
    local, constrained or unconstrained, optimization.
