context:
  name: nlopt
  version: 2.8.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
- url: https://github.com/stevengj/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: e02a4956a69d323775d79fdaec7ba7a23ed912c7d45e439bc933d991ea3193fd

build:
  number: 0

requirements:
  build:
  - cross-python_${{ target_platform }}
  - cmake
  - python
  - swig
  - pip
  - numpy
  host:
  - numpy
  - python
  run:
  - numpy

tests:
- script: pytester
  files:
    recipe:
    - test_import_nlopt.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run

about:
  homepage: https://github.com/stevengj/nlopt
  documentation: https://nlopt.readthedocs.io/en/latest/
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: |
    library for nonlinear optimization, wrapping many algorithms for global and
    local, constrained or unconstrained, optimization
  description: |
    NLopt is a library for nonlinear local and global optimization, for
    functions with and without gradient information. It is designed as a simple,
    unified interface and packaging of several free/open-source nonlinear
    optimization libraries.

extra:
  recipe-maintainers:
  - IsabelParedes
