context:
  name: RcppParallel
  version: 6.1.1.9000
package:
  name: r-${{ name | lower }}
  version: ${{ version | replace('-', '_') }}

source:
  path: src/RcppParallel

build:
  number: 0
  # skip: ${{ r_base == '4.6.1' }} ONLY IF NEEDED


requirements:
  build:
  - cross-r-base_${{ target_platform }} ==${{ r_base }}
  - ${{ compiler('c') }}
  - r-base
  host:
  - r-base ==${{ r_base }}



about:
  homepage: https://cran.r-project.org/package=${{ name }}
  documentation: https://cran.r-project.org/web/packages/${{ name }}/refman/${{ name }}.html
  repository: https://cran.r-project.org/package=${{ name }}
  license: GPL-3.0-or-later
  license_file:
  - ${{ PREFIX }}/lib/R/share/licenses/GPL-2
  summary: "An empty mock package of RcppParallel on Emscripten."
  description: |-
    An empty mock package of RcppParallel on Emscripten.

extra:
  recipe-maintainers:
  - DerThorsten
