context:
  name: r-glue
  version: 1.8.1

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url:
  - https://cran.r-project.org/src/contrib/${{ name[2:] }}_${{ version }}.tar.gz
  - https://cran.r-project.org/src/contrib/Archive/${{ name[2:] }}/${{ name[2:] }}_${{ version }}.tar.gz
  - https://cloud.r-project.org/src/contrib/${{ name[2:] }}_${{ version }}.tar.gz
  sha256: 1c55905d3efc3d5c199ceb0bd12218e97f0d4c64df6038ff41ecef415478a122

build:
  number: 0
  string: r${{ r_abi_build_tag }}_h${{ hash }}_${{ build_number }}
  script: $R CMD INSTALL $R_ARGS .

requirements:
  build:
  - cross-r-base_${{ target_platform }} ==${{ r_base }}
  - ${{ compiler('c') }}

tests:
- package_contents:
    lib:
    - R/library/${{ name[2:] }}/libs/${{ name[2:] }}.so

about:
  homepage: https://github.com/tidyverse/glue
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: |
    Glue strings to data in R. Small, fast, dependency free interpreted string
    literals.
  description: |
    Glue offers interpreted string literals that are small, fast, and dependency
    -free. glue does this by embedding R expressions in curly braces, which are
    then evaluated and inserted into the string.

extra:
  recipe-maintainers:
  - IsabelParedes
