context:
  name: xfun
  version: '0.59'

package:
  name: r-${{ name }}
  version: ${{ version }}

source:
  url:
  - https://cran.r-project.org/src/contrib/${{ name }}_${{ version }}.tar.gz
  - https://cloud.r-project.org/src/contrib/${{ name }}_${{ version }}.tar.gz
  sha256: ea0e0d75563bfb6e6ea7f69ac5f99f621e4072cb633229989bf9dd7ccd8adc44

build:
  number: 0
  script: $R CMD INSTALL $R_ARGS .

requirements:
  build:
  - cross-r-base_${{ target_platform }} ==${{ r_base }}
  - ${{ compiler('c') }}
  host:
  - r-base ==${{ r_base }}

tests:
- package_contents:
    lib:
    - R/library/${{ name }}/libs/${{ name }}.so
- script: run_r_test test_xfun.R
  files:
    recipe:
    - test_xfun.R
  requirements:
    build:
    - r-wasm-tester

about:
  homepage: https://cran.r-project.org/package=${{ name }}
  documentation: https://git.yihui.org/xfun/
  repository: https://github.com/yihui/xfun
  license: MIT
  license_file: LICENSE
  summary: Miscellaneous R functions
  description: |
    Miscellaneous functions commonly used in other packages maintained by
    'Yihui Xie'.

extra:
  recipe-maintainers:
  - IsabelParedes
