context:
  version: 0.2.3
  name: r-lazyeval

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url:
  - https://cran.r-project.org/src/contrib/${{ name[2:] }}_${{ version }}.tar.gz
  - https://cloud.r-project.org/src/contrib/${{ name[2:] }}_${{ version }}.tar.gz
  sha256: c65db1997b195a7bb0ab3afbb834345ea277b428b2736eeded4242629e86adcb

build:
  number: 1
  string: r${{ r_abi_build_tag }}_h${{ hash }}_${{ build_number }}
  script: $R CMD INSTALL $R_ARGS .

requirements:
  build:
  - cross-r-base_${{ target_platform }} ==${{ r_base }}
  - ${{ compiler('c') }}
  - r-rlang
  host:
  - r-rlang
  run:
  - r-rlang

tests:
- package_contents:
    lib:
    - R/library/${{ name[2:] }}/libs/${{ name[2:] }}.so

about:
  homepage: https://CRAN.R-project.org/package=lazyeval
  repository: https://github.com/hadley/lazyeval
  license: GPL-3.0-only
  license_family: GPL3
  license_file: GPL-3
  summary: An alternative to non-standard evaluation (NSE) for R
  description: |
    An alternative approach to non-standard evaluation using formulas. Provides a
    full implementation of LISP style 'quasiquotation', making it easier to
    generate code with other code.

extra:
  recipe-maintainers:
  - IsabelParedes
