"""Generate `test_upstream_cdb.py` from Cadabra's own regression tests.

Upstream runs every `tests/*.cdb` file through the `cadabra2` command line
REPL, which is not part of this package. The same files run fine with just
the Python module: `cadabra2.cdb2python_string` translates Cadabra notation to
Python (this is exactly what the REPL does) and the result is executed in a
namespace prepared by `cadabra2_defaults`. pytester only ships `test_*.py`
files to the browser, so the sources are embedded into a generated test file.

The recipe selects the upstream tests (`tests: files: source:`); this script
turns every `.cdb` file in the given directory into one test case.

Usage: python gen_upstream_tests.py [DIRECTORY_WITH_CDB_FILES]
"""

import json
import pathlib
import sys

# Tests which use `cdb` packages; these work with the global kernel (as in the
# REPL), so they run late in the session as they add global properties.
GLOBAL_KERNEL = ["manip"]

# `numerical` checks that division by zero inside substitute() raises; the
# aborted algorithm leaves state behind which makes later tests in the same
# process fail (upstream runs each file in a fresh process), so it runs last.
RUN_LAST = GLOBAL_KERNEL + ["numerical"]

TEMPLATE = '''"""Cadabra upstream regression tests (tests/*.cdb), generated by
gen_upstream_tests.py; see there."""

import contextlib
import io
import json

import pytest

SOURCES = json.loads(__SOURCES__)
GLOBAL_KERNEL = set(__GLOBAL_KERNEL__)


@pytest.mark.parametrize("name", list(SOURCES))
def test_upstream(name):
    import cadabra2

    # Translate with display enabled, as the REPL does.
    code = cadabra2.cdb2python_string(SOURCES[name], True, "")
    namespace = {"__name__": "__main__"}
    out = io.StringIO()
    try:
        with contextlib.redirect_stdout(out):
            exec("import cadabra2\\nfrom cadabra2 import *\\nfrom cadabra2_defaults import *\\n", namespace)
            # Upstream runs every test file in its own process; give each a
            # fresh kernel.
            if name in GLOBAL_KERNEL:
                namespace["__cdbkernel__"] = cadabra2.__cdbkernel__
            else:
                namespace["__cdbkernel__"] = cadabra2.create_scope()
            # Upstream tests signal failures with `assert`.
            exec(compile(code, name + ".cdb", "exec"), namespace)
    except BaseException:
        print(out.getvalue()[-3000:])
        raise
'''


def main():
    tests_dir = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "tests")
    names = sorted(p.stem for p in tests_dir.glob("*.cdb"))
    if not names:
        sys.exit(f"no .cdb files found in {tests_dir}")
    names = [n for n in names if n not in RUN_LAST] + [n for n in RUN_LAST if n in names]
    sources = {name: (tests_dir / f"{name}.cdb").read_text() for name in names}
    text = TEMPLATE.replace("__SOURCES__", repr(json.dumps(sources)))
    text = text.replace("__GLOBAL_KERNEL__", repr(GLOBAL_KERNEL))
    pathlib.Path("test_upstream_cdb.py").write_text(text)
    print(f"generated test_upstream_cdb.py with {len(names)} upstream tests: {' '.join(names)}")


if __name__ == "__main__":
    main()
