context:
  name: tachyon
  version: 0.99.5

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: http://jedi.ks.uiuc.edu/~johns/raytracer/files/${{ version }}/tachyon-${{ version }}.tar.gz
  sha256: 09203c102311149f5df5cc367409f96c725742666d19c24db5ba994d5a81a6f5

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - ${{ compiler("c") }}
  - ${{ compiler('cxx') }}
  - pkg-config
  - autoconf-archive

tests:
  - package_contents:
      files:
        - bin/poly.x
        - bin/class.x
        - bin/cws.x
        - bin/nef.x
        - bin/mori.x

about:
  homepage: http://jedi.ks.uiuc.edu/~johns/raytracer/
  license: GPL-3.0-only
  license_file: README
  summary: a Package for Analyzing Lattice Polytopes 

extra:
  recipe-maintainers:
  - wangyenshu