context:
  name: libgit2
  version: 1.9.7

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/${{ name }}/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 1a4fbe7589e814777ae76b64734ad80f4ecad22cd33a22682a2aaea4ae5375e7

build:
  number: 0

requirements:
  build:
  - ${{ compiler('c') }}
  - cmake
  - pkg-config
  host:
  - pcre2
  - zlib

tests:
- script:
  - test -f ${PREFIX}/include/git2.h
  - test -f ${PREFIX}/lib/libgit2.a
  - test -f ${PREFIX}/lib/pkgconfig/libgit2.pc

about:
  homepage: https://github.com/libgit2/libgit2
  license: GPL-2.0-only WITH GCC-exception-2.0
  license_file: COPYING

extra:
  recipe-maintainers:
  - ianthomas23
