context:
  name: libgit2
  version: 1.9.6

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/${{ name }}/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: a88a42a4ea9bdab7aa8686eead3bf7d9c6dd74529caca16ab22eaa92433d31d9

build:
  number: 0

requirements:
  build:
  - ${{ compiler('c') }}
  - cmake
  - pkg-config
  host:
  - pcre2
  - zlib

tests:
- script:
  - test -f ${PREFIX}/include/git2.h
  - test -f ${PREFIX}/lib/libgit2.a
  - test -f ${PREFIX}/lib/pkgconfig/libgit2.pc

about:
  homepage: https://github.com/libgit2/libgit2
  license: GPL-2.0-only WITH GCC-exception-2.0
  license_file: COPYING

extra:
  recipe-maintainers:
  - ianthomas23
