context:
  name: r-wasm-tester
  version: 0.2.0

package:
  name: ${{ name }}
  version: ${{ version }}

build:
  number: 0

requirements:
  run:
  - nodejs

tests:
- package_contents:
    files:
    - bin/Rtester.js
    - bin/run_r_test
- script: run_r_test --help

about:
  summary: Package to test WebAssembly R packages in a headless browser.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
  - IsabelParedes
