context:
  version: "21.0.13+1" 
  
package:
  name: openjdk
  version: ${{ version }}

source:
  - git: https://github.com/bmarti44/openjdk.git
    target_directory: openjdk

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - make
    - autoconf
    - pkg-config
    - findutils
    - coreutils
    - openjdk =21
  host:
    - libffi 

about:
  homepage: https://openjdk.org/
  summary: open-source implementation of the Java Platform
  license: GPL-2.0-only
  license_file: LICENSE
