context:
  version: 5.0.0

package:
  name: xeus-lite-static
  version: ${{ version }}

source:
  url: https://github.com/jupyter-xeus/xeus-lite/archive/refs/tags/${{ version }}.tar.gz
  sha256: d0f03b73526f398d43b404170459135abcb2489f9b10ee007c90f7af46f66228

build:
  number: 0

requirements:
  build:
  - ${{ compiler("cxx") }}
  - cmake
  - ninja
  host:
  - nlohmann_json
  - xeus

tests:
  - package_contents:
      files:
        - lib/libxeus-lite.a

  - script:
      - generic-testing
    requirements:
      build:
      - generic-testing

about:
  license: BSD-3-Clause
  license_family: BSD-3
  license_file: LICENSE
  summary: xeus-lite implements the emscripten/js based communication layer between the kernel and the frontend
  homepage: https://github.com/jupyter-xeus/xeus-lite
extra:
  recipe-maintainers:
  - DerThorsten
  - JohanMabille

