context:
  version: 7.2.0

package:
  name: traits
  version: ${{ version }}

source:
- url: https://pypi.io/packages/source/t/traits/traits-${{ version }}.tar.gz
  sha256: 77e2203f2bebc06fada6139475a974dc96cf2e99991e4fe4ffd29e346ca0fc13

build:
  number: 0
  script: ${PYTHON} -m pip install . ${PIP_ARGS}

  files:
    exclude:
    - '**/*.pyi'
    - '**/tests/**'
    - '**/__pycache__/**'
    - '**/*.pyc'
    - '**/test_*.py'
  python:
    skip_pyc_compilation:
    - '**/*.py'
requirements:
  build:
  - cross-python_${{ target_platform }}
  - ${{ compiler("c") }}
  - python
  - pip
  host:
  - python
  run:
  - python

tests:
- script: pytester
  files:
    recipe:
    - test_import_traits.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run

about:
  homepage: https://docs.enthought.com/traits
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: traits - explicitly typed attributes for Python
