context:
  name: cohomcalg
  version: '0.32'

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/BenjaminJurke/cohomCalg/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 367c52b99c0b0a4794b215181439bf54abe4998872d3ef25d793bc13c4d40e42

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - ${{ compiler("c") }}
  - ${{ compiler('cxx') }}
  - pkg-config
  - autoconf-archive

tests:
- package_contents:
    files:
    - lib/libcohomcalg.a

about:
  homepage: https://github.com/BenjaminJurke/cohomCalg
  license: GPL-3.0-only
  license_file: LICENSE
  summary: A software package for computation of sheaf cohomologies for line bundles on toric varieties.

extra:
  recipe-maintainers:
  - wangyenshu