context:
  version: '1.26'
  name: libdeflate

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/ebiggers/libdeflate/archive/v${{ version }}.tar.gz
  sha256: bba03fffc5538576213675ce6968fcff6ce2e67d82e4d5febea2d05f9f13cf85

build:
  number: 0

requirements:
  build:
  - ${{ compiler("cxx") }}
  - cmake
  - make

tests:
- package_contents:
    files:
    - include/libdeflate.h
    - lib/libdeflate.a

about:
  homepage: https://github.com/ebiggers/libdeflate
  license: MIT
  license_file: COPYING
  summary: |
    libdeflate is a library for fast, whole-buffer DEFLATE-based compression and
    decompression.
  description: |
    Heavily optimized library for DEFLATE/zlib/gzip compression and
    decompression.

extra:
  recipe-maintainers:
  - DerThorsten

