context:
  version: 0.9.9

package:
  name: libfrobby
  version: ${{ version }}

source:
  url: https://github.com/Macaulay2/frobby/releases/download/v${{ version }}/frobby_v${{ version }}.tar.gz
  sha256: 4c072c2ee208d853b7173921d45cc7d39297cf3f7fd9c8e7da8e482da3b51aa3

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - ${{ compiler('cxx') }}
  host:
  - gmp

tests:
- package_contents:
    files:
    - lib/libfrobby.a
    - include/frobby.h

about:
  homepage: https://github.com/Macaulay2/frobby
  license: GPL-2.0-only
  license_file: COPYING
  summary: Frobby is a software system and project for computations with monomial ideals.

extra:
  recipe-maintainers:
  - wangyenshu