context:
  name: flex
  version: 2.6.4

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/westes/flex/releases/download/v${{ version }}/flex-${{ version }}.tar.gz
  sha256: e87aae032bf07c26f85ac0ed3250998c37621d95f8bd748b31f15b33c45ee995

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - ${{ compiler("c") }}
  - ${{ compiler('cxx') }}
  - pkg-config
  - autoconf-archive

tests:
- package_contents:
    files:
    - lib/libfl.a
    - include/FlexLexer.h

about:
  homepage: https://github.com/westes/flex
  license: LicenseRef-flex-BSD
  license_file: COPYING
  summary: The Fast Lexical Analyzer - scanner generator for lexing in C and C++ 

extra:
  recipe-maintainers:
  - wangyenshu