#!/bin/bash

unset cmake

unset CONDA_FORGE_EMSCRIPTEN_ACTIVATED
unset PY_SIDE_LD_FLAGV
unset EM_FORGE_OPTFLAGS
unset EM_FORGE_DBGFLAGS
unset EM_FORGE_LDFLAGS_BASE
unset EM_FORGE_CFLAGS_BASE
unset EM_FORGE_SIDE_MODULE_LDFLAGS
unset EM_FORGE_SIDE_MODULE_CFLAGS

# restore
export LDFLAGS=$EM_OLD_LDFLAGS
export CFLAGS=$EM_OLD_CFLAGS

unset EM_OLD_LDFLAGS
unset EM_OLD_CFLAGS
