#!/bin/bash

unset cmake

unset CONDA_FORGE_EMSCRIPTEN_ACTIVATED
unset EMSDK_PYTHON
unset PYTHON
unset CONDA_EMSDK_DIR
unset CC
unset CXX
unset AR
unset RANLIB
unset CMAKE_ARGS
unset PY_SIDE_LD_FLAGV
unset EM_FORGE_OPTFLAGS
unset EM_FORGE_DBGFLAGS
unset EM_FORGE_LDFLAGS_BASE
unset EM_FORGE_CFLAGS_BASE
unset EM_FORGE_SIDE_MODULE_LDFLAGS
unset EM_FORGE_SIDE_MODULE_CFLAGS
unset LDFLAGS
