context:
  version: 2.5.4
  name: openjpeg


package:
  name: ${{ name }}-static
  version: ${{ version }}

source:
  url: https://github.com/uclouvain/openjpeg/archive/v${{ version }}.tar.gz
  sha256: a695fbe19c0165f295a8531b1e4e855cd94d0875d2f88ec4b61080677e27188a
build:
  number: 0

requirements:
  build:
  - ${{ compiler("cxx") }}
  - cmake
  - make
  host:
  - libtiff-static
  - libpng-static
  - zlib-static
  run:
  - ${{pin_compatible("libtiff-static", lower_bound="x.x.x", upper_bound="x.x.x")}}
  - ${{pin_compatible("libpng-static", lower_bound="x.x.x", upper_bound="x.x.x")}}
  - ${{pin_compatible("zlib-static", lower_bound="x.x.x", upper_bound="x.x.x")}}

tests:
- package_contents:
    files:
    - include/openjpeg-2.5/openjpeg.h
    - lib/libopenjp2.a
- script:
    - generic-testing
  requirements:
    build:
    - generic-testing



about:
  homepage: http://www.openjpeg.org/
  license: BSD-2-Clause
  license_file: LICENSE
  summary: An open-source JPEG 2000 codec written in C


extra:
  recipe-maintainers:
  - DerThorsten

