context:
  version: 6.0.3

package:
  name: xeus
  version: ${{ version }}

source:
  url: https://github.com/jupyter-xeus/xeus/archive/refs/tags/${{ version }}.tar.gz
  sha256: 75035a58d989766d1cda7cf3c3704bd6ead2077a5bfb9b20f6776248743f1340

build:
  number: 0

requirements:
  run_exports:
  - ${{ pin_subpackage('xeus', upper_bound='x.x') }}
  build:
  - cmake
  - ${{ compiler("cxx") }}
  - make
  host:
  - nlohmann_json
  - nlohmann_json-abi

tests:
- script:
  - test -f $PREFIX/lib/libxeus.a
  - test -f $PREFIX/lib/libxeus.so
  - test -f $PREFIX/include/xeus/xeus.hpp
about:
  license: BSD-3-Clause
  license_family: BSD-3
  license_file: LICENSE
  summary: xeus
  homepage: https://github.com/jupyter-xeus/xeus
extra:
  recipe-maintainers:
  - DerThorsten
  - JohanMabille
