context:
  version: 4.10.0
  name: libnetcdf

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/Unidata/netcdf-c/archive/refs/tags/v${{ version }}.tar.gz
  sha256: ce160f9c1483b32d1ba8b7633d7984510259e4e439c48a218b95a023dc02fd4c
  patches:
  - parallel-disable.patch
  - hdf5-parallel-disable.patch
build:
  number: 0

requirements:
  build:
  - python
  - cross-python_${{ target_platform }}
  - ${{ compiler('c') }}
  - pip
  - m4
  - make
  host:
  - python
  - libxml2
  - hdf5
  - zlib
  run:
  - python

about:
  homepage: http://www.unidata.ucar.edu/software/netcdf/
  license: MIT
  license_file: COPYRIGHT
  summary: Libraries and data formats that support array-oriented scientific data
  repository: https://github.com/Unidata/netcdf-c
