context:
  name: libnetcdf
  version: 4.10.1

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/Unidata/netcdf-c/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 33c27231c478c3b35da7c7758fbdd02da1fe407abcb16ddfe195f69d164f930d
  patches:
  - patches/parallel-disable.patch
  - patches/hdf5-parallel-disable.patch

build:
  number: 0

  files:
    exclude:
    - share/man/man1/**
requirements:
  build:
  - python
  - cross-python_${{ target_platform }}
  - ${{ compiler('c') }}
  - pip
  - m4
  - make
  host:
  - python
  - libxml2 >=2.15
  - hdf5
  - zlib
  run:
  - python

tests:
- package_contents:
    files:
    - include/netcdf.h
    - lib/libnetcdf.a
    - lib/pkgconfig/netcdf.pc

about:
  homepage: http://www.unidata.ucar.edu/software/netcdf/
  license: MIT
  license_file: COPYRIGHT
  summary: |
    Libraries and data formats that support array-oriented scientific data.
  repository: https://github.com/Unidata/netcdf-c
