context:
  version: 2.5.0


package:
  name: doctest
  version: ${{ version }}

source:
  url: https://github.com/onqtam/doctest/archive/refs/tags/v${{ version }}.zip
  sha256: 263eb384092cf04b96db683cff160235f7cdae22ff03b363b1f8521730a1b1d0

build:
  number: 0

requirements:
  build:
  - ${{ compiler("cxx") }}
  - cmake
  - ninja

tests:
- script:
  - test -f $PREFIX/include/doctest/doctest.h
  - test -f $PREFIX/lib/cmake/doctest/doctestConfig.cmake

about:
  license: MIT
  license_file: LICENSE.txt
  summary: doctest
  homepage: https://github.com/onqtam/doctest
extra:
  recipe-maintainers:
  - DerThorsten
