context:
  version: 2.5.2


package:
  name: doctest
  version: ${{ version }}

source:
  url: https://github.com/onqtam/doctest/archive/refs/tags/v${{ version }}.zip
  sha256: 988fd276cd1c2786790776cd8d9715766d21b45718256bff123a30379a6352a7

build:
  number: 0

requirements:
  build:
  - ${{ compiler("cxx") }}
  - cmake
  - ninja

tests:
- script:
  - test -f $PREFIX/include/doctest/doctest.h
  - test -f $PREFIX/lib/cmake/doctest/doctestConfig.cmake

about:
  license: MIT
  license_file: LICENSE.txt
  summary: doctest
  homepage: https://github.com/onqtam/doctest
extra:
  recipe-maintainers:
  - DerThorsten
