context:
  version: 2.5.3


package:
  name: doctest
  version: ${{ version }}

source:
  url: https://github.com/onqtam/doctest/archive/refs/tags/v${{ version }}.zip
  sha256: 5ddeafa34bece65b9f2e5207186fa70cd8ca44c00f41ae2c25e6e50b427c2b79

build:
  number: 0

requirements:
  build:
  - ${{ compiler("cxx") }}
  - cmake
  - ninja

tests:
- script:
  - test -f $PREFIX/include/doctest/doctest.h
  - test -f $PREFIX/lib/cmake/doctest/doctestConfig.cmake

about:
  license: MIT
  license_file: LICENSE.txt
  summary: doctest
  homepage: https://github.com/onqtam/doctest
extra:
  recipe-maintainers:
  - DerThorsten
