context:
  name: xz
  version: 5.8.4

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/tukaani-project/xz/releases/download/v${{ version }}/xz-${{ version }}.tar.gz
  sha256: 0014c7886930454fe8bd4228665b51af55eeae560ea135c9c4cd33f55b2591d9

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - ${{ compiler('cxx') }}

tests:
- package_contents:
    files:
    - lib/liblzma.a
    - include/lzma.h
    - bin/xz
    - bin/xz.wasm

about:
  homepage: https://tukaani.org/xz/
  license: 0BSD
  license_file: COPYING
  summary: XZ Utils

extra:
  recipe-maintainers:
  - wangyenshu
