context:
  name: xz
  version: 5.8.3

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/tukaani-project/xz/releases/download/v${{ version }}/xz-${{ version }}.tar.gz
  sha256: 3d3a1b973af218114f4f889bbaa2f4c037deaae0c8e815eec381c3d546b974a0

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - ${{ compiler('cxx') }}

tests:
- package_contents:
    files:
    - lib/liblzma.a
    - include/lzma.h
    - bin/xz
    - bin/xz.wasm

about:
  homepage: https://tukaani.org/xz/
  license: 0BSD
  license_file: COPYING
  summary: XZ Utils 

extra:
  recipe-maintainers:
  - wangyenshu