context:
  name: msolve
  version: 0.10.1

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://msolve.lip6.fr/downloads/v${{ version }}/msolve-${{ version }}.tar.gz
  sha256: 60aa0d667515b846bb6cb8996d7f60e06f8d861974930e2343230c6a2c9eed9e

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - ${{ compiler("c") }}
  - ${{ compiler('cxx') }}
  - pkg-config
  - autoconf-archive
  host:
  - gmp
  - mpfr
  - libflint

tests:
- package_contents:
    files:
    - lib/libmsolve.a
    - include/msolve/msolve/msolve.h

about:
  homepage: https://msolve.lip6.fr/
  license: GPL-2.0-only
  license_file: COPYING
  summary: msolve is a library, written in plain C, for solving multivariate polynomial systems.

extra:
  recipe-maintainers:
  - wangyenshu