context:
  version: 0.3.6
  name: r-sparsevctrs

package:
  name: ${{ name }}
  version: ${{ version|replace("-", "_") }}

source:
  url:
  - https://cran.r-project.org/src/contrib/${{ name[2:] }}_${{ version }}.tar.gz
  - https://cloud.r-project.org/src/contrib/${{ name[2:] }}_${{ version }}.tar.gz
  sha256: b5913cb3b7471937d10b7784c78e955f8dc263c15ede4bef85a44c7572240aec

build:
  number: 0
  script: $R CMD INSTALL $R_ARGS .
  skip: ${{ r_base == '4.6.0' }}
  
requirements:
  build:
  - cross-r-base_${{ target_platform }} ==${{ r_base }}
  - ${{ compiler('c') }}
  - r-cli >=3.4.0
  - r-rlang >=1.1.0
  - r-vctrs
  host:
  - r-base ==${{ r_base }}
  - r-cli >=3.4.0
  - r-rlang >=1.1.0
  - r-vctrs
  run:
  - r-cli >=3.4.0
  - r-rlang >=1.1.0
  - r-vctrs
tests:
- package_contents:
    lib:
    - R/library/${{ name[2:] }}/libs/${{ name[2:] }}.so
- script: run_r_test 
  files:
    recipe:
    - test_import.R
  requirements:
    build:
    - r-wasm-tester
about:
  homepage: https://github.com/r-lib/sparsevctrs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Provides sparse vectors powered by ALTREP (Alternative Representations for R Objects) that behave like regular vectors, and can thus be used in data frames. Also provides tools to convert between sparse matrices and data frames with sparse columns and functions to interact with sparse vectors.

extra:
  recipe-maintainers:
    - DerThorsten
