context:
  name: qutip
  version: 5.3.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/qutip/qutip/archive/v${{ version }}.tar.gz
  sha256: 643dc71bfe14f8e87f5f2ee60267ebe787b214fffa9a3c2918dadaacc6a1fe13

build:
  number: 0
  script: ${PYTHON} -m pip install . -vvv --no-deps --no-build-isolation

  files:
    exclude:
    - '**/*.pyi'
    - '**/tests/**'
    - '**/*.pxd'
    - '**/*.ini'
    - '**/*.pyx'
    - '**/__pycache__/**'
    - '**/*.pyc'
    - '**/test_*.py'
  python:
    skip_pyc_compilation:
    - '**/*.py'
requirements:
  build:
  - ${{ compiler('cxx') }}
  - cross-python_${{ target_platform }}
  - cython
  - numpy
  - setuptools
  - packaging >=22
  - pip
  host:
  - python
  - numpy
  - scipy >=1.0
  run:
  - python
  - numpy
  - scipy >=1.0
  - packaging

tests:
- script: pytester
  files:
    recipe:
    - test_qutip.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: |
    QuTiP is open-source software for simulating the dynamics of open quantum
    systems and optimal quantum control.
  homepage: http://qutip.org
  repository: https://github.com/qutip/qutip

extra:
  recipe-maintainers:
  - hodgestar
