context:
  name: cocoa5
  version: 0.99850

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: http://cocoa.altervista.org/cocoalib/tgz/CoCoALib-${{ version }}.tgz
  sha256: d3e7af0153c6950f83f4e3556540f0177fedf5179f0f7667b7d6d670268fd445

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - ${{ compiler('cxx') }}
  - pkg-config
  - autoconf-archive
  host:
  - gmp
  - boost-cpp
  - cddlib
  - libfrobby
  - gfanlib
  - gsl
  - mpfr
  - libflint
  - normaliz
  - ntl
  - nauty

tests:
- package_contents:
    files:
    - bin/CoCoAInterpreter.js
    - bin/CoCoAInterpreter.wasm
    - bin/CoCoAInterpreter.data
    - bin/CoCoAInterpreter.data.js
    - lib/libcocoa.a

about:
  homepage: https://sites.google.com/view/cocoa-cocoalib
  license: GPL-3.0-only
  license_file: COPYRIGHT-full-text
  summary: CoCoA-5 is an interactive system for Computations in Commutative Algebra.

extra:
  recipe-maintainers:
  - wangyenshu