#!/bin/bash
IMAGE_DIR=$(pwd)/image
SOURCE_DIR=$(pwd)/image/src

export OCTAVE_VER="10.3.0"

# atm we install the *oct files in the same dir
# as the *.m files, without any arch-specific subdir
M_FILE_INSTALL_DIR=$PREFIX/share/octave/packages/image-${PKG_VERSION}
OCT_INSTALL_DIR=$M_FILE_INSTALL_DIR/


# copy DESCRIPTION,COPYING,INDEX into the M_FILE_INSTALL_DIR/packinfo
mkdir -p "${M_FILE_INSTALL_DIR}/packinfo"
cp "$IMAGE_DIR"/{DESCRIPTION,COPYING,INDEX} "${M_FILE_INSTALL_DIR}/packinfo/"

# copy everything from $THIS_DIR/image/into the M_FILE_INSTALL_DIR
cp -r "$IMAGE_DIR"/inst/* "${M_FILE_INSTALL_DIR}/"



cd "$SOURCE_DIR"

# Since 2.20.0 some sources include "config.h", which is normally generated by
# the package's configure script. We bypass configure and drive Makefile.in
# directly, so write out the one define that actually affects the build.
# Octave 11 renamed lo-mappers.h to mappers.h, so probe for it instead of
# hardcoding, and let the sources fall back to lo-mappers.h on Octave 10.
if [ -f "$PREFIX/include/octave-${OCTAVE_VER}/octave/mappers.h" ]; then
    echo "#define HAVE_OCTAVE_MAPPERS_H 1" > config.h
else
    echo "#define HAVE_OCTAVE_LO_MAPPERS_H 1" > config.h
fi

chmod +x $RECIPE_DIR/fake_mkoctfile.sh
make -f Makefile.in MKOCTFILE="$RECIPE_DIR/fake_mkoctfile.sh" 

# copy the generated .oct files into the OCT_INSTALL_DIR
mkdir -p "$OCT_INSTALL_DIR"
cp *.oct "$OCT_INSTALL_DIR/"

# run "build_pkg_add.sh" to generate the PKG_ADD and PKG_DEL files based on the generated .oct files
bash "${RECIPE_DIR}/build_pkg_add.sh" "${OCT_INSTALL_DIR}" 
