context:
  name: image
  version: 2.18.2

package:
  name: octave-${{ name }}
  version: ${{ version }}

source:
  url: 
    https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/image-${{
    version }}.tar.gz
  sha256: a5863c1392d977ea4f370cc5547e04b1763c2b77d7b3a1f2cf6cd8c1e5e49919
  target_directory: ${{ name }}

build:
  number: 0

requirements:
  build:
  - ${{ compiler('c') }}
  - ${{ compiler('cxx') }}
  - make
  - wabt
  - octave 10.3.*
  host:
  - octave 10.3.*

tests:
- package_contents:
    files:
    - share/octave/packages/${{ name }}-${{ version }}/imgetfile.m

about:
  homepage: https://octave.sourceforge.io/image/
  license: GPL-3.0-or-later
  license_file: ${{ name }}/COPYING
  summary: Image processing toolbox for GNU Octave

extra:
  recipe-maintainers:
  - arjxn-py
  - DerThorsten
