context:
  name: libgc
  version: 8.2.12

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/bdwgc/bdwgc/releases/download/v${{ version }}/gc-${{ version }}.tar.gz
  sha256: 42e5194ad06ab6ffb806c83eb99c03462b495d979cda782f3c72c08af833cd4e

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - ${{ compiler('cxx') }}

tests:
- package_contents:
    files:
    - lib/libgc.a
    - include/gc.h

about:
  homepage: https://www.hboehm.info/gc/
  license: LicenseRef-MIT-style
  license_file: README.md
  summary: The Boehm-Demers-Weiser conservative C/C++ Garbage Collector

extra:
  recipe-maintainers:
  - wangyenshu