context:
  version: '0.19'
  name: json-c

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://s3.amazonaws.com/json-c_releases/releases/json-c-${{ version }}.tar.gz
  sha256: 37ad0249902e301bd9052bf712e511fcc6acff4ecaad4b5900aad9ce564e26de
build:
  number: 0
requirements:
  build:
  - ${{ compiler("c") }}
  - cmake
  - make



tests:
- package_contents:
    files:
    - include/json-c/json.h
    - lib/libjson-c.a
    - lib/libjson-c.so


about:
  homepage: https://github.com/json-c/json-c
  license: MIT
  license_file: COPYING
  summary: JSON implementation in C.
extra:
  recipe-maintainers:
  - DerThorsten
