context:
  version: 0.6.2

package:
  name: gfanlib
  version: ${{ version }}

source:
  url: https://math.au.dk/~jensen/software/gfan/gfanlib${{ version }}.tar.gz
  sha256: 39f0c46fc8657741220419d3177b487eac64a4e391493789f130d4f4c5aac381

build:
  number: 0

requirements:
  build:
  - make
  - pkg-config
  - ${{ compiler('c') }}
  host:
  - gmp
  - cddlib

tests:
- package_contents:
    files:
    - include/gfanlib.h
    - lib/libgfan.a

about:
  homepage: https://math.au.dk/~jensen/software/gfan/gfan.html
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: Gfan is a software package for computing Gröbner fans and tropical varieties. Parts of gfan have been put into a library.

extra:
  recipe-maintainers:
  - wangyenshu