context:
  name: hexbin
  version: 1.28.6

package:
  name: r-${{ name }}
  version: ${{ version }}

source:
  url:
  - https://cran.r-project.org/src/contrib/${{ name }}_${{ version }}.tar.gz
  - https://cloud.r-project.org/src/contrib/${{ name }}_${{ version }}.tar.gz
  sha256: 848ee6a8f4c265df2adb86c76795a01386cdb3802be6bcc4fd73949851655337

build:
  number: 0
  # Dependencies not yet available for R 4.6.x on conda-forge
  skip: ${{ r_base == '4.6.1' }}
  script: $R CMD INSTALL $R_ARGS .

requirements:
  build:
  - ${{ compiler('c') }}
  - ${{ compiler('fortran') }}
  - cross-r-base_${{ target_platform }} ==${{ r_base }}
  - r-lattice
  host:
  - r-base ==${{ r_base }}
  - r-lattice
  - libflang
  run:
  - r-lattice

tests:
- package_contents:
    lib:
    - R/library/${{ name }}/libs/${{ name }}.so
- script: run_r_test
  files:
    recipe:
    - test_hexbin.R
  requirements:
    build:
    - r-wasm-tester

about:
  homepage: https://cran.r-project.org/package=hexbin
  repository: http://github.com/edzer/hexbin
  license: GPL-2.0-only
  license_family: GPL2
  license_file: ${{ PREFIX }}/lib/R/share/licenses/GPL-2
  summary: Hexagonal binning routines and plotting methods

extra:
  recipe-maintainers:
  - IsabelParedes
