context:
  name: simplejson
  version: 4.1.2

package:
  name: ${{ name }}
  version: ${{ version }}

source:
- url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 6ae4186f90362e9c03c80a1cd5062a20f3a11ac9d391f7ee0ef0701a0e2b7394

build:
  number: 0
  script: ${PYTHON} -m pip install . ${PIP_ARGS}

  files:
    exclude:
    - '**/tests/**'
    - '**/__pycache__/**'
    - '**/*.pyc'
    - '**/test_*.py'
  python:
    skip_pyc_compilation:
    - '**/*.py'
requirements:
  build:
  - ${{ compiler("cxx") }}
  - cross-python_${{ target_platform }}
  - python
  - cython
  - numpy
  - pip
  - extension-helpers
  host:
  - numpy
  - python

tests:
- script: pytester
  requirements:
    build:
    - pytester
    run:
    - pytester-run
  files:
    recipe:
    - test_simplejson.py

about:
  homepage: http://github.com/simplejson/simplejson
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Simple, fast, extensible JSON encoder/decoder for Python
  description: |
    Simplejson is a simple, fast, complete, correct and extensible JSON
    <http://json.org> encoder and decoder for Python 2.5+ and Python 3.3+. It is
    pure Python code with no dependencies, but includes an optional C extension
    for a serious speed boost.

extra:
  recipe-maintainers:
  - DerThorsten
