context:
  name: later
  version: 1.4.8

package:
  name: r-${{ name }}
  version: ${{ version }}

source:
  url:
  - https://cran.r-project.org/src/contrib/${{ name }}_${{ version }}.tar.gz
  - https://cloud.r-project.org/src/contrib/${{ name }}_${{ version }}.tar.gz
  sha256: ce5d88b3fd1df409eaa21aa53bf20b1a9331f75cd69e7e9b2a27b40d2290d219
  patches:
  - patches/0001-Disable-multi-threading.patch

build:
  number: 6
  # Dependencies not yet available for R 4.6.0 on conda-forge
  skip: ${{ r_base == '4.6.1' }}
  script: $R CMD INSTALL $R_ARGS .

requirements:
  build:
  - cross-r-base_${{ target_platform }} ==${{ r_base }}
  - ${{ compiler('c') }}
  - ${{ compiler('cxx') }}
  - r-rcpp
  - r-rlang
  host:
  - r-base ==${{ r_base }}
  - r-rcpp
  - r-rlang
  run:
  - r-rcpp
  - r-rlang

tests:
- package_contents:
    lib:
    - R/library/${{ name }}/libs/${{ name }}.so
- script: run_r_test test_later.R
  files:
    recipe:
    - test_later.R
  requirements:
    build:
    - r-wasm-tester

about:
  homepage: https://r-lib.github.io/later/
  repository: https://github.com/r-lib/later
  license: MIT
  license_file: LICENSE
  summary: |
    Utilities for Scheduling Functions to Execute Later with Event Loops
  description: |
    This WebAssembly version is experimental.
    Executes arbitrary R or C functions some time after the current time, after
    the R execution stack has emptied. The functions are scheduled in an event loop.

extra:
  recipe-maintainers:
  - IsabelParedes
