context:
  name: M2
  version: 1.26.06

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/Macaulay2/M2/releases/download/release-${{ version }}/Macaulay2-${{ version }}.tar.gz
  sha256: 9ba54041626f6364036f84b4168704d74136d1bec2dbe08d9d0fb3fef2a0c854

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - ${{ compiler("c") }}
  - ${{ compiler('cxx') }}
  - pkg-config
  - autoconf-archive
  - bison
  - flex
  - diffutils
  - patch
  - gettext
  - nodejs >=22
  - gfortran
  host:
  - 4ti2
  - libgc
  - boost-cpp
  - cddlib
  - csdp
  - eigen
  - fflas-ffpack
  - libflint
  - givaro
  - glpk
  - jansson
  - libxml2
  - lrslib
  - mpfi
  - topcom
  - cohomcalg
  - fplll
  - libfrobby
  - glpk
  - gmp
  - xz
  - memtailor
  - mathic
  - mathicgb
  - mpfr
  - mpsolve
  - nauty
  - normaliz
  - ntl
  - openblas
  - singular
  - lrslib
  - onetbb
  - zlib
  - libffi
  - gfanlib
  - msolve
  - gdbm
  - ncurses
  - gtest
  - zlib
  - readline
  - cocoalib

about:
  homepage: https://macaulay2.com/
  license: GPL-2.0-or-later
  license_file: README.md
  summary: The primary source code repository for Macaulay2, a system for computing in commutative algebra, algebraic geometry and related fields. 

extra:
  recipe-maintainers:
  - wangyenshu