context:
  version: 2.14.3

recipe:
  name: freetype-split

source:
  url: https://download.savannah.gnu.org/releases/freetype/freetype-${{ version }}.tar.gz
  sha256: e61b31ab26358b946e767ed7eb7f4bb2e507da1cfefeb7a8861ace7fd5c899a1

build:
  number: 0

outputs:
- package:
    name: freetype-static
    version: ${{ version }}

  build:
    script: build_pkg.sh
  requirements:
    build:
    - ${{ compiler('c') }}
    - cmake
    - make
    host:
    - libpng-static
    run:
    - ${{pin_compatible("libpng-static", lower_bound="x.x.x", upper_bound="x.x.x") }}

  tests:
  - script:
    - test -f $PREFIX/include/freetype2/freetype/freetype.h
    - test -f $PREFIX/include/freetype2/ft2build.h
    - test -f $PREFIX/lib/libfreetype.a
    - generic-testing
    requirements:
      build:
      - generic-testing
- package:
    name: freetype
    version: ${{ version }}

  build:
    script: build_pkg.sh
  requirements:
    build:
    - ${{ compiler('c') }}
    - cmake
    - ninja
    host:
    - libpng-static
    run_exports:
    - ${{ pin_subpackage('freetype', upper_bound='x.x') }}

  tests:
  - script:
    - test -f $PREFIX/include/freetype2/freetype/freetype.h
    - test -f $PREFIX/include/freetype2/ft2build.h
    - test -f $PREFIX/lib/libfreetype.so
    - generic-testing
    requirements:
      build:
      - generic-testing

about:
  homepage: https://www.freetype.org/
  license: GPL-2.0-only OR FTL
  license_file:
  - docs/GPLv2.TXT
  - docs/FTL.TXT
  summary: A Free, High-Quality, and Portable Font Engine
  description: |
    FreeType is designed to be small, efficient, highly customizable
    and portable while capable of producing high-quality output (glyph images)
    of most vector and bitmap font formats.
  documentation: http://freetype.sourceforge.net/freetype2/documentation.html
  repository: http://git.savannah.gnu.org/cgit/freetype/

extra:
  recipe-maintainers:
  - wolfv
  - anutosh491
