context:
  version: 1.0.2

package:
  name: sparrow-ipc
  version: ${{ version }}

source:
  url: https://github.com/QuantStack/sparrow-ipc/archive/${{ version }}.tar.gz
  sha256: 9c8b13806528a26f48be6271d56ae0a5540e3772d9fea4ef7d5b4838e32424e9
  patches:
  - patches/0001-use-host-flatc.patch
  - patches/0002-add-lz4-zstd-dependencies-to-config.patch

build:
  number: 0

  files:
    exclude:
    - '**/tests/**'
requirements:
  build:
  - ${{ compiler("cxx") }}
  - cmake
  - flatbuffers
  - lz4-c = 1.10.0
  - zstd
  host:
  - flatbuffers
  - sparrow
  - lz4-c = 1.10.0
  - zstd
  run:
  - flatbuffers
  - sparrow
  - lz4-c = 1.10.0
  - zstd

tests:
- package_contents:
    files:
    - include/sparrow_ipc/serialize.hpp
    - include/sparrow_ipc/deserialize.hpp
    - lib/libsparrow-ipc.a
    - share/cmake/sparrow-ipc/sparrow-ipcConfig.cmake
    - share/cmake/sparrow-ipc/sparrow-ipcConfigVersion.cmake
    - share/cmake/sparrow-ipc/sparrow-ipcTargets.cmake
- script:
  - build_tests.sh
  requirements:
    build:
    - ${{ compiler("cxx") }}
    - cmake
    - make
  files:
    recipe:
    - build_tests.sh
    - tests/

about:
  summary: C++20 idiomatic APIs for the Apache Arrow IPC
  description: C++20 idiomatic APIs for the Apache Arrow IPC
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  homepage: https://github.com/QuantStack/sparrow-ipc
  documentation: https://github.com/QuantStack/sparrow-ipc

extra:
  recipe-maintainers:
  - Alex-PLACET
