context:
  name: v86
  version: '0.5'

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/copy/v86/archive/refs/tags/0.5.tar.gz
  sha256: d76a4449b8b33449f45da332542b121767a363a389d1a3990f104423a4833b0e

build:
  number: 0

requirements:
  build:
    - make
    - clang           
    - rust
    - rust-std-wasm32-unknown-unknown            
    - nodejs          
    - openjdk        
    - wget            
    - lld

about:
  homepage: https://copy.sh/v86/
  license: BSD-2-Clause AND MIT
  license_file: LICENSE
  summary: x86 PC emulator and x86-to-wasm JIT, running in the browser 

extra:
  recipe-maintainers:
  - wangyenshu