context:
  version: 8.0.3

package:
  name: soplex
  version: ${{ version }}

source:
  url: https://github.com/scipopt/soplex/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 224eca4c49a2509a2a893a1d4b63e510e2ddb4ff374699cc6afc36f12af4e621

build:
  number: 0

requirements:
  build:
  - ${{ compiler("cxx") }}
  - cmake
  - ninja
  host:
  - boost-cpp
  - gmp
  - mpfr
  - zlib
  - bzip2
  # omitted for now: papilo

tests:
- script:
  - test -d ${PREFIX}/include/soplex
- package_contents:
    files:
    - lib/libsoplex.a

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Linear optimization solver using the revised simplex method
  homepage: https://github.com/scipopt/soplex

extra:
  recipe-maintainers:
  - mkoeppe
