context:
  version: 8.0.1

package:
  name: soplex
  version: ${{ version }}

source:
  url: https://github.com/scipopt/soplex/archive/refs/tags/v${{ version }}.tar.gz
  sha256: f989f650e0d489f4e84037af2a50b1d0928f62ab79179ef566111d9197c2b6c8

build:
  number: 1

requirements:
  build:
  - ${{ compiler("cxx") }}
  - cmake
  - ninja
  host:
  - boost-cpp
  - gmp
  - mpfr
  - zlib
  - bzip2
  # omitted for now: papilo

tests:
- script:
  - test -d ${PREFIX}/include/soplex
- package_contents:
    files:
      - lib/libsoplex.a

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Linear optimization solver using the revised simplex method
  homepage: https://github.com/scipopt/soplex

extra:
  recipe-maintainers:
  - mkoeppe
