context:
  name: r-fs
  version: 1.6.7

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url:
  - https://cran.r-project.org/src/contrib/Archive/${{ name[2:] }}/${{ name[2:] }}_${{ version }}.tar.gz
  - https://cloud.r-project.org/src/contrib/Archive/${{ name[2:] }}/${{ name[2:] }}_${{ version }}.tar.gz
  sha256: e8f0a8f4b15177166c9530cd922e38705421467f05ec55500b28bca5864be411
  patches:
  # Sourced from https://github.com/r-wasm/fs/tree/webr
  - patches/0001-Modify-vendored-libuv-source-for-webR-compat.patch
  - patches/0002-Add-Makevars-for-webR.patch
  # Select Emscripten as the target
  - patches/0003-Set-UNAME-to-Emscripten.patch

build:
  number: 1
  string: r${{ r_abi_build_tag }}_h${{ hash }}_${{ build_number }}
  script: |
    $R CMD INSTALL \
    --no-docs \
    --no-html \
    --no-test-load \
    --no-staged-install \
    --no-byte-compile \
    $R_ARGS .

requirements:
  build:
  - ${{ compiler('c') }}
  - cross-r-base_${{ target_platform }} ==${{ r_base }}
  - pkg-config

tests:
- package_contents:
    lib:
    - R/library/${{ name[2:] }}/libs/${{ name[2:] }}.so

about:
  homepage: https://fs.r-lib.org
  license: MIT
  summary: A cross-platform interface to file system operations, built on top of the 'libuv' C library.
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
  - rgaiacs
