context:
  name: libraqm
  version: 0.10.5

package:
  name: ${{ name }}
  version: ${{ version }}

source:
- url: https://github.com/HOST-Oman/libraqm/releases/download/v${{ version }}/raqm-${{ version }}.tar.xz
  sha256: 563053e724892a7b037913110ea2daef50ad575d4fa9f7c368ae1e4515f5e856

build:
  number: 0

requirements:
  build:
  - ${{ compiler('c') }}
  - meson
  - ninja
  - pkg-config
  host:
  - freetype
  - harfbuzz
  - sheenbidi

tests:
  - package_contents:
      include:
      - raqm.h
      - raqm-version.h
      lib:
      - libraqm.a

about:
  homepage: https://github.com/HOST-Oman/libraqm
  license: MIT
  license_file: COPYING
  summary: A library for complex text layout

extra:
  recipe-maintainers:
  - ianthomas23
