context:
  name: libraqm
  version: 0.11.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
- url: https://github.com/HOST-Oman/libraqm/releases/download/v${{ version }}/raqm-${{ version }}.tar.xz
  sha256: 3d0add115f7d4a9410d3377462ed3c05e86342193ef984183e4380e3787b2d4c

build:
  number: 0

requirements:
  build:
  - ${{ compiler('c') }}
  - meson
  - ninja
  - pkg-config
  host:
  - freetype
  - harfbuzz
  - sheenbidi

tests:
- package_contents:
    include:
    - raqm.h
    - raqm-version.h
    lib:
    - libraqm.a

about:
  homepage: https://github.com/HOST-Oman/libraqm
  license: MIT
  license_file: COPYING
  summary: A library for complex text layout

extra:
  recipe-maintainers:
  - ianthomas23
