context:
  version: 1.1.1-1.1
  name: r-Rcpp

package:
  name: ${{ name | lower }}
  version: ${{ version }}

source:
  url:
  - https://cran.r-project.org/src/contrib/${{ name[2:] }}_${{ version }}.tar.gz
  - https://cloud.r-project.org/src/contrib/${{ name[2:] }}_${{ version }}.tar.gz
  sha256: 32e5d5fee4080c8ca315f31b74c3eaa6367a1900e92e860e00390c9565f5fbe1

build:
  number: 0
  script: $R CMD INSTALL $R_ARGS .

requirements:
  build:
  - cross-r-base_${{ target_platform }} ==${{ r_base }}
  - ${{ compiler('cxx') }}
  host:
  - r-base ==${{ r_base }}

tests:
- package_contents:
    lib:
    - R/library/${{ name[2:] }}/libs/${{ name[2:] }}

about:
  homepage: https://www.rcpp.org/
  repository: https://github.com/RcppCore/Rcpp
  license: GPL-2.0-or-later
  license_file: GPL-2
  summary: Seamless R and C++ Integration
  description: |
    The 'Rcpp' package provides R functions as well as C++ classes which offer a
    seamless integration of R and C++. Many R data types and objects can be
    mapped back and forth to C++ equivalents which facilitates both writing of
    new code as well as easier integration of third-party libraries.

extra:
  recipe-maintainers:
  - IsabelParedes
