#!/usr/bin/env bash


# Process arguments
MODIFIED_ARGS=()
for arg in "$@"; do
    case "$arg" in
        -O3)
            MODIFIED_ARGS+=("-O2")  # Replace -O3 with -O2
            ;;
        -sWASM_BIGINT)
            # Remove this argument
            ;;
        *)
            MODIFIED_ARGS+=("$arg")  # Keep other arguments unchanged
            ;;
    esac
done


exec "$BUILD_PREFIX/bin/flang-new-bak" "${MODIFIED_ARGS[@]}"