#!/bin/sh

# Process the arguments
MODIFIED_ARGS=""
for arg in "$@"; do
    case "$arg" in
        -O3)
            MODIFIED_ARGS="$MODIFIED_ARGS -O2"
            ;;
        -sWASM_BIGINT)
            # Remove this argument
            ;;
        *)
            MODIFIED_ARGS="$MODIFIED_ARGS $arg"
            ;;
    esac
done

exec $BUILD_PREFIX/bin/flang-new-bak "${MODIFIED_ARGS[@]}"