context:
  name: snappy-computop
  version: 3.3.2

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/3-manifolds/SnapPy/archive/refs/tags/${{ version }}_as_released.tar.gz
  sha256: 2ba62fd23e5ee1e75685d30fef74880959c56e0e8f808f75ba95f88a5b2004e9

build:
  number: 0

requirements:
  build:
  - ${{ compiler('c') }}
  - ${{ compiler('cxx') }}
  - cross-python_emscripten-wasm32
  host:
  - python
  - pip
  - setuptools
  - wheel
  - cython >=0.28
  - mpmath
  run:
  - python
  - fxrays >=1.3
  - plink >=2.4.9
  - spherogram >=2.4.1
  - snappy_manifolds >=1.4
  - veering >=1.0.6
  - low_index >=1.2.1
  - tkinter-gl >=1.0
  - decorator
  - packaging
  - pypng
  - pyx
  - pickleshare
  - cypari >=2.3

tests:
- package_contents:
    files:
    - lib/python3.13/site-packages/snappy/SnapPy.cpython-313-wasm32-emscripten.so
    - lib/python3.13/site-packages/snappy/SnapPyHP.cpython-313-wasm32-emscripten.so

about:
  homepage: https://snappy.computop.org/
  license: GPL-2.0-only
  license_file: README.rst
  summary: SnapPy is a package for studying the topology and geometry of 3-manifolds, with a focus on hyperbolic structures.

extra:
  recipe-maintainers:
  - wangyenshu
