context:
  version: 1.4-2
  name: mvtnorm

package:
  name: r-${{ name }}
  version: ${{ version | replace('-', '_') }}

source:
  url:
  - https://cran.r-project.org/src/contrib/${{ name }}_${{ version }}.tar.gz
  - https://cloud.r-project.org/src/contrib/${{ name }}_${{ version }}.tar.gz
  - https://cran.r-project.org/src/contrib/Archive/${{ name }}/${{ name }}_${{ version }}.tar.gz
  sha256: 466302a08c9306d11384d85bf677893e4794541bde2991409be54e1f7b304b6e

build:
  number: 0

requirements:
  build:
  - cross-r-base_${{ target_platform }} ==${{ r_base }}
  - ${{ compiler('c') }}
  host:
  - r-base ==${{ r_base }}
  - libflang

tests:
- package_contents:
    lib:
    - R/library/${{ name }}/libs/${{ name }}.so
- script: run_r_test
  files:
    recipe:
    - test_mvtnorm.R
  requirements:
    build:
    - r-wasm-tester

about:
  homepage: https://codeberg.org/thothorn/mvtnorm
  license: GPL-2.0-only
  license_family: GPL2
  license_file: GPL-2
  summary: |
    Computes multivariate normal and t probabilities, quantiles, random
    deviates, and densities. Log-likelihoods for multivariate Gaussian models
    and Gaussian copulae parameterised by Cholesky factors of covariance or
    precision matrices are implemented for interval-censored and exact data, or
    a mix thereof. Score functions for these log-likelihoods are available. A
    class representing multiple lower triangular matrices and corresponding
    methods are part of this package.

extra:
  recipe-maintainers:
  - DerThorsten
