context:
  version: 6.9.13-45
package:
  name: imagemagick
  version: ${{ version | replace("-","_") }}

source:
  url: https://github.com/ImageMagick/ImageMagick6/archive/refs/tags/${{ version}}.tar.gz
  sha256: 5715a928e374c71fa07b62a52b1948480e29bd45f0ea1aa9e916da3f15ca7310
build:
  number: 0

  files:
    exclude:
    - share/man/man1/**
requirements:
  build:
  - libtool
  - ${{ compiler('c') }}
  - make
  - pkg-config
  host:
  - libtiff
  - libpng
  - libjpeg-turbo
  - bzip2
  - libxml2
  - openjpeg
  - zlib

tests:
- package_contents:
    files:
    - lib/libMagick++-6.Q16.a
    - include/ImageMagick-6/Magick++.h

about:
  homepage: http://www.imagemagick.org/
  license: AGPL-3.0-only
  license_file: LICENSE
  summary: Software suite to create, edit, compose, or convert bitmap images.

