context:
  name: libitk
  version: "5.4.6"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
- url: https://github.com/InsightSoftwareConsortium/ITK/archive/v${{ version }}.tar.gz
  sha256: cf28bc7220c57c24ebcbabbd3b2544ea7ab65f0aad430a99f8e157738ed812b7

build:
  number: 0

requirements:
  build:
  - ${{ compiler('c') }}
  - ${{ compiler('cxx') }}
  - cmake
  - ninja

tests:
- package_contents:
    files:
    - include/ITK-5.4/itkImage.h
    - lib/libITKCommon-5.4.a

about:
  homepage: https://www.itk.org/
  license: Apache-2.0
  license_file: LICENSE
  summary: ITK is an open-source toolkit for multidimensional image analysis
  description: |
    The Insight Toolkit (ITK) is an open-source, cross-platform system that
    provides developers with an extensive suite of software tools for image
    analysis. Developed through extreme programming methodologies, ITK employs
    leading-edge algorithms for registering and segmenting multidimensional data.
  repository: https://github.com/InsightSoftwareConsortium/ITK

extra:
  recipe-maintainers:
  - Copilot
