context:
  name: dynare-preprocessor-pylib
  version: 0.0.1.dev0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/EconForge/dynare_preprocessor_pylib/archive/073de0045c4a1b986081fc4164c290d7de510c85.tar.gz
  sha256: 594241ecd8e48f8d52f96875fd2c5a80dca7899148f4e772fd45b6ab99d6056e

build:
  number: 0

requirements:
  build:
    - cross-python_${{ target_platform }}
    - ${{ compiler("cxx") }}
    - bison
    - flex
    - meson
    - ninja
    - pkg-config
    - pip
    - nanobind
  host:
    - python
    - nanobind
    - boost-cpp
    - libpython
  run:
    - python
    - numpy

tests:
  - script: pytester
    requirements:
      build:
        - pytester
      run:
        - pytester-run
    files:
      recipe:
        - test_preproc.py

about:
  homepage: https://www.dynare.org/
  summary: Dynare preprocessor and Python library
  description: Preprocessor for Dynare economic models with Python nanobind bindings.
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - albop
    - svillemot
