context:
  name: dynare-preprocessor-pylib
  version: 0.0.1.dev0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/EconForge/dynare_preprocessor_pylib/archive/refs/tags/v${{ version }}.tar.gz
  sha256: eb5028ba54930ba90039cd5fa85f05ec322c6835415c567e08bab1ab7a34b6c6

build:
  number: 0

requirements:
  build:
    - cross-python_${{ target_platform }}
    - ${{ compiler("cxx") }}
    - bison
    - flex
    - meson
    - ninja
    - pkg-config
    - pip
    - nanobind
  host:
    - python
    - nanobind
    - boost-cpp
    - libpython
  run:
    - python
    - numpy

tests:
  - script: pytester
    requirements:
      build:
        - pytester
      run:
        - pytester-run
    files:
      recipe:
        - test_preproc.py

about:
  homepage: https://www.dynare.org/
  summary: Dynare preprocessor and Python library
  description: Preprocessor for Dynare economic models with Python nanobind bindings.
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - albop
    - svillemot
