context:
  version: 10.8.9

package:
  name: passagemath-iml
  version: ${{ version }}

source:
- url: https://pypi.org/packages/source/p/passagemath-iml/passagemath_iml-${{ version }}.tar.gz
  sha256: e93c4d3cf6b5b5c39f2704c914ca1d111b54fa94e70b219e4076fa7de0a9999e

build:
  script: |
    export LDFLAGS="$LDFLAGS -Wl,--allow-multiple-definition"
    ${{ PYTHON }} -m pip install .
  number: 1

requirements:
  build:
  - python
  - crossenv >=1.2
  - cross-python_emscripten-wasm32
  - ${{ compiler("c") }}
  - ${{ compiler("cxx") }}
  - pip
  - passagemath-setup
  - passagemath-environment
  - cython<3.3
  - cysignals
  - pkgconfig
  - numpy
  - passagemath-abi == ${{ version }}
  host:
  - python
  - gmp
  - mpfr
  - mpc
  - libflint
  - iml
  - numpy
  - cysignals
  - memory-allocator
  - mpmath
  - passagemath-categories
  - passagemath-flint
  - passagemath-modules
  run:
  - python
  - conway-polynomials
  - cysignals
  - memory-allocator
  - passagemath-categories
  - passagemath-environment
  - passagemath-flint
  - passagemath-modules

tests:
- script: pytester
  files:
    recipe:
    - test_passagemath_iml.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run
    - passagemath-modules
    - passagemath-repl

about:
  license: GPL-2.0-or-later
  license_file: README.rst
  summary: 'passagemath: Linear Algebra with IML'
  description: |
    Distribution of a part of the Sage library.
    It provides modules that depend on the library IML.

extra:
  emscripten_tests:
    python:
      pytest_files:
      - test_passagemath_iml.py
  recipe-maintainers:
  - mkoeppe
