#!/bin/bash

echo "[rust-nightly] Deactivating..."

unset CARGO_HOME
unset RUSTUP_HOME
unset OPENSSL_INCLUDE_PATH
unset OPENSSL_LIBRARY_PATH
unset OPENSSL_DIR
unset WASM32_UNKNOWN_EMSCRIPTEN_OPENSSL_LIB_DIR
unset WASM32_UNKNOWN_EMSCRIPTEN_OPENSSL_DIR
unset WASM32_UNKNOWN_EMSCRIPTEN_OPENSSL_INCLUDE_DIR
unset PYO3_CROSS
unset PYO3_PYTHON
unset PYO3_CROSS_PYTHON_VERSION
unset PYO3_CROSS_LIB_DIR
unset PYO3_CROSS_INCLUDE_DIR
unset CARGO_BUILD_TARGET
