context:
  name: csdp
  version: 6.2.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/coin-or/Csdp/archive/refs/tags/releases/${{ version }}.tar.gz
  sha256: 3d341974af1f8ed70e1a37cc896e7ae4a513375875e5b46db8e8f38b7680b32f

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - ${{ compiler("c") }}
  - ${{ compiler('cxx') }}
  - pkg-config
  - autoconf-archive
  host:
  - openblas

tests:
- package_contents:
    files:
    - lib/libsdp.a.a
    - include/index.h

about:
  homepage: https://github.com/coin-or/Csdp/wiki
  license: EPL-2.0
  license_file: COPYING
  summary: CSDP is a solver for semidefinite programming problems.

extra:
  recipe-maintainers:
  - wangyenshu