context:
  name: cddlib
  version: 0.94n

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/cddlib/cddlib/releases/download/${{ version }}/cddlib-${{ version }}.tar.gz
  sha256: b87ee07ba2c1d0ab92a3e4eccacdf568f981a095a392e3b9efd7e7e4a9e125b1

build:
  number: 0

requirements:
  build:
  - ${{ compiler('c') }}
  - libtool
  - m4
  - make
  - gnuconfig
  host:
  - gmp

tests:
- package_contents:
    files:
    - include/cddlib/setoper.h
    - lib/libcdd.a
    - lib/libcddgmp.a

about:
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: |
    Double description method for polyhedral representation conversion
  homepage: https://github.com/cddlib/cddlib

extra:
  recipe-maintainers:
  - mkoeppe
