context:
  name: ccluster
  version: 1.1.8

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/rimbach/Ccluster/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 99f7118355a691efac23f443fcf3cf44cad37074eca1b7bac1fddc24660802d1

build:
  number: 0

requirements:
  build:
    - make
    - ${{ compiler('c') }}
  host:
    - gmp
    - mpfr
    - libflint

tests:
- package_contents:
    files:
    - lib/libccluster.a

about:
  repository: https://github.com/rimbach/Ccluster
  license: LGPL-2.1-only
  license_file: LICENSE
  summary: Ccluster is a C library implementing an algorithm for local clustering of the complex roots of a univariate polynomial whose coefficients are any complex numbers.

extra:
  recipe-maintainers:
    - wangyenshu
