context:
  name: libbrial
  version: 1.2.15

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/BRiAl/BRiAl/releases/download/${{ version }}/brial-${{ version }}.tar.gz
  sha256: dde1bfbf90821af6bca7c4480a09d89c06c8d3153078b83e8ffce3ae03366f58

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - ${{ compiler('c') }}
  - ${{ compiler('cxx') }}
  - pkg-config
  - autoconf-archive
  host:
  - m4ri
  - boost-cpp

tests:
- package_contents:
    files:
    - lib/libbrial.a
    - include/polybori.h

about:
  homepage: https://github.com/BRiAl/BRiAl
  license: GPL-2.0-only
  license_file: LICENSE
  summary: BRiAl is the legacy version of PolyBoRi maintained by sagemath developers.

extra:
  recipe-maintainers:
  - wangyenshu