context:
  name: fmt
  version: 12.2.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/fmtlib/fmt/archive/${{ version }}.tar.gz
  sha256: 8b852bb5aa6e7d8564f9e81394055395dd1d1936d38dfd3a17792a02bebd7af0

build:
  number: 0

requirements:
  build:
  - ${{ compiler("cxx") }}
  - cmake
  - ninja

tests:
- package_contents:
    files:
    - include/fmt/base.h
    - include/fmt/core.h
    - lib/cmake/fmt/fmt-config.cmake
    - lib/libfmt.a
    - lib/pkgconfig/fmt.pc

about:
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: '{fmt} is an open-source formatting library for C++'
  description: |
    {fmt} is an open-source formatting library for C++.
    It can be used as a safe and fast alternative to (s)printf and iostreams.
  homepage: https://fmt.dev/latest/

extra:
  recipe-maintainers:
  - DerThorsten

