context:
  name: cryptography
  version: 47.0.0

package:
  name: cryptography
  version: ${{ version }}

source:
- url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 9f8e55fe4e63613a5e1cc5819030f27b97742d720203a087802ce4ce9ceb52bb

build:
  number: 0
  script: ${PYTHON} -m pip install . -vvv

  files:
    exclude:
    - '**/*.pyi'
    - '**/__pycache__/**'
    - '**/*.pyc'
    - '**/test_*.py'
  python:
    skip_pyc_compilation:
    - '**/*.py'
requirements:
  build:
  - ${{compiler('cxx')}}
  - cross-python_${{target_platform}}
  - cffi
  - openssl
  - setuptools-rust
  - rust-nightly
  - maturin
  host:
  - python
  - openssl
  - cffi
  run:
  - cffi

tests:
- script: pytester
  requirements:
    build:
    - pytester
    run:
    - pytester-run
  files:
    recipe:
    - test_import_cryptography.py

about:
  homepage: https://cryptography.io
  license: Apache-2.0 AND BSD-3-Clause AND PSF-2.0 AND MIT
  license_family: BSD
  license_file: LICENSE
