context:
  name: pydantic-core
  version: 2.45.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
- url: https://pypi.io/packages/source/p/pydantic-core/pydantic_core-${{ version }}.tar.gz
  sha256: a3ff659217dcb3d13442ed348e12e12ed6c876791154a575def1fea9bb667d8e

build:
  number: 0

  files:
    exclude:
    - '**/*.pyi'
    - '**/__pycache__/**'
    - '**/*.pyc'
  python:
    skip_pyc_compilation:
    - '**/*.py'

requirements:
  build:
  - cross-python_${{ target_platform }}
  - setuptools-rust
  - rust-nightly
  - maturin
  - typing_extensions
  host:
  - python
  - typing_extensions
  run:
  - typing_extensions

tests:
- script: pytester
  requirements:
    build:
    - pytester
    run:
    - pytester-run
  files:
    recipe:
    - test_pydantic_core.py

about:
  summary: Core validation logic for pydantic written in rust
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/pydantic/pydantic-core
  repository: https://github.com/pydantic/pydantic-core
