context:
  version: 0.9.2

package:
  name: xeus-sqlite
  version: ${{ version }}

source:
- url: https://github.com/jupyter-xeus/xeus-sqlite/archive/refs/tags/${{ version }}.tar.gz
  sha256: c8eafc86e11ce69776dba99c174496203286603ff72c630a1f4b3fbeac73c61f

build:
  number: 0

requirements:
  build:
  - ${{ compiler("cxx") }}
  - cmake
  - ninja
  host:
  - nlohmann_json >= 3.12
  - xproperty
  - cpp-tabulate
  - xvega
  - xvega-bindings
  - xeus-lite
  - xeus
  - xtl
  - sqlitecpp

tests:
- package_contents:
    files:
    - bin/xsqlite.js
    - bin/xsqlite.wasm

about:
  license: BSD-3-Clause
  license_family: BSD-3
  license_file: LICENSE
  summary: xeus-sqlite
  homepage: https://github.com/jupyter-xeus/xeus-sqlite
extra:
  recipe-maintainers:
  - DerThorsten
