#!/usr/bin/env bash
# gen-symbols.sh OUT.c ARCHIVE_OR_OBJECT...
#
# The emscripten port has no dynamic loader: os::dll_lookup() (and so every
# System.loadLibrary / native method lookup) is answered from a name -> address
# table named emscripten_static_symbols, which the program must provide. This
# writes that table for every JNI entry point defined in the given archives.
# It is also what keeps those functions alive: nothing else references them,
# so without the table wasm-ld would drop every native method in the JDK.
set -euo pipefail

out=$1; shift
NM="$(em-config LLVM_ROOT)/llvm-nm"

"$NM" --defined-only "$@" 2>/dev/null \
  | awk '$2 == "T" { print $3 }' \
  | grep -E '^(Java_|JNI_OnLoad|JNI_OnUnload|Agent_On|JIMAGE_|ZIP_|JDK_|JNU_|JAWT_|GetStringPlatformChars|VerifyClass|Splash)' \
  | sort -u > "$out.syms"

{
  echo "/* Generated by gen-symbols.sh -- do not edit. */"
  echo "struct EmscriptenStaticSymbol { const char *name; void *addr; };"
  sed 's/.*/extern void &(void);/' "$out.syms"
  echo "const struct EmscriptenStaticSymbol emscripten_static_symbols[] = {"
  sed 's/.*/  { "&", (void *) \&& },/' "$out.syms"
  echo "  { 0, 0 }"
  echo "};"
} > "$out"

echo "gen-symbols: $(wc -l < "$out.syms") entry points" >&2
rm -f "$out.syms"
