#!/bin/bash
set -exuo pipefail

mkdir -p build
cd build

emcmake cmake -GNinja \
    ${CMAKE_ARGS} \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="${PREFIX}" \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_PREFIX_PATH="${PREFIX}" \
    -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=BOTH \
    -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=BOTH \
    -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=BOTH \
    -DGDCM_BUILD_SHARED_LIBS=OFF \
    -DGDCM_BUILD_TESTING=OFF \
    -DGDCM_BUILD_APPLICATIONS=OFF \
    -DGDCM_BUILD_EXAMPLES=OFF \
    -DGDCM_WRAP_PYTHON=OFF \
    -DGDCM_WRAP_JAVA=OFF \
    -DGDCM_WRAP_CSHARP=OFF \
    -DGDCM_WRAP_PHP=OFF \
    -DGDCM_USE_VTK=OFF \
    -DGDCM_DOCUMENTATION=OFF \
    -DGDCM_PDF_DOCUMENTATION=OFF \
    -DGDCM_USE_SYSTEM_ZLIB=OFF \
    -DGDCM_USE_SYSTEM_EXPAT=OFF \
    -DGDCM_USE_SYSTEM_OPENSSL=OFF \
    -DGDCM_USE_SYSTEM_UUID=OFF \
    -DGDCM_USE_SYSTEM_JSON=OFF \
    -DGDCM_USE_SYSTEM_LIBXML2=OFF \
    -DGDCM_USE_SYSTEM_POPPLER=OFF \
    -DGDCM_USE_SYSTEM_SOCKETXX=OFF \
    -DGDCM_USE_SYSTEM_CHARLS=OFF \
    -DGDCM_USE_SYSTEM_OPENJPEG=OFF \
    -DGDCM_USE_SYSTEM_LJPEG=OFF \
    -DGDCM_USE_SYSTEM_PAPYRUS3=OFF \
    -DGDCM_USE_JPEGTURBO=OFF \
    -DGDCM_USE_JPEGLS=ON \
    -DGDCM_USE_PVRG=OFF \
    -DGDCM_USE_KAKADU=OFF \
    -DGDCM_USE_COREFOUNDATION_LIBRARY=OFF \
    -DGDCM_HAVE_PTHREAD_H=OFF \
    ..

ninja install

# Remove .la files if any
find "${PREFIX}" -name '*.la' -delete 2>/dev/null || true
