context:
  name: pspline
  version: 1.0-21

package:
  name: r-${{ name | lower }}
  version: ${{ version | replace('-', '_') }}

source:
  url:
  - https://cran.r-project.org/src/contrib/${{ name }}_${{ version }}.tar.gz
  - https://cloud.r-project.org/src/contrib/${{ name }}_${{ version }}.tar.gz
  - https://cran.r-project.org/src/contrib/Archive/${{ name }}/${{ name }}_${{ version }}.tar.gz
  sha256: 7f5739b9cf378dda6cd33d152b5f84ae2afa728f7dac0729dab565264138abca

build:
  number: 0
  # skip: ${{ r_base == '4.6.1' }} ONLY IF NEEDED
  script: $R CMD INSTALL $R_ARGS .

requirements:
  build:
  - cross-r-base_${{ target_platform }} ==${{ r_base }}
  - ${{ compiler('c') }}
  - ${{ compiler('fortran') }}
  host:
  - r-base ==${{ r_base }}
  - libflang

tests:
- package_contents:
    lib:
    - R/library/${{ name }}/libs/${{ name }}.so
- script: run_r_test test_${{ name }}.R
  files:
    recipe:
    - test_${{ name }}.R
  requirements:
    build:
    - r-wasm-tester

about:
  homepage: https://cran.r-project.org/package=${{ name }}
  documentation: https://cran.r-project.org/web/packages/${{ name }}/refman/${{ name }}.html
  repository: https://cran.r-project.org/package=${{ name }}
  license: LicenseRef-Unlimited
  license_family: MIT
  license_file:
  - ${{ PREFIX }}/lib/R/share/licenses/TODO
  summary: Penalized Smoothing Splines
  description: |-
    Smoothing splines with penalties on order m derivatives.

extra:
  recipe-maintainers:
  - DerThorsten
