context:
  version: 5.0.0

package:
  name: xeus-lite
  version: ${{ version }}

source:
  url: https://github.com/jupyter-xeus/xeus-lite/archive/refs/tags/${{ version }}.tar.gz
  sha256: d0f03b73526f398d43b404170459135abcb2489f9b10ee007c90f7af46f66228

build:
  number: 0

requirements:
  build:
  - ${{ compiler("cxx") }}
  - cmake
  - ninja
  host:
  - nlohmann_json
  - xeus

tests:
- script:
  - test -f $PREFIX/lib/libxeus-lite.a

about:
  license: BSD-3-Clause
  license_family: BSD-3
  license_file: LICENSE
  summary: xeus
  homepage: https://github.com/jupyter-xeus/xeus-lite
extra:
  recipe-maintainers:
  - DerThorsten
  - JohanMabille

