context:
  name: less
  version: '693'

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/gwsw/less/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 82a25fef545ade475fa5911bda949ca4dca5e9bd4cb80969ba0b7bfbc022bbf1

build:
  number: 0

requirements:
  build:
  - ${{ compiler("c") }}
  - make
  - autoconf
  host:
  - ncurses <6.5
  - pcre2

tests:
- script:
  - test -f $PREFIX/bin/less.data
  - test -f $PREFIX/bin/less.js
  - test -f $PREFIX/bin/less.wasm
- script: |
    OUTPUT=$(run_modularized $PREFIX/bin/less.js --version | head -1 | cut -c -9)
    if [[ "$OUTPUT" != "less ${{ version }} " ]]; then
      echo "Unexpected output: $OUTPUT"
      exit 1
    fi
  requirements:
    build:
    - run_modularized >= 0.1.2

about:
  license: GPL-3.0-only
  license_file: COPYING

extra:
  recipe-maintainers:
  - ianthomas23
