context:
  name: lua
  version: 5.5.1

package:
  name: ${{ name }}-static
  version: ${{ version }}

source:
- url: https://www.lua.org/ftp/lua-${{ version }}.tar.gz
  sha256: 1c4b4068d67061f2a2231ad2b5422e77acea1487ea9890f6320af614f4373dce
  patches:
  - luaconf.patch


- path: CMakeLists.txt

build:
  number: 1

requirements:
  build:
  - ${{ compiler('c') }}
  - cmake
  - make

tests:
- script: |
    test -f $PREFIX/lib/liblua.a
    test ! -f $PREFIX/lib/liblua.so
    OUTPUT=$(run_modularized $PREFIX/bin/lua.js -e "a=1+1;print(a)")
    if [[ "$OUTPUT" != "2" ]]; then
      echo "Unexpected output: $OUTPUT"
      exit 1
    fi
  requirements:
    build:
    - run_modularized >= 0.1.2
- script: |
    OUTPUT=$(run_modularized $PREFIX/bin/luac.js -v)
    echo $OUTPUT
    if [[ "$OUTPUT" != *"${{ version }}"* ]]; then
      echo "Unexpected output."
      exit 1
    fi
  requirements:
    build:
    - run_modularized >= 0.1.2

- script:
    - generic-testing
  requirements:
    build:
    - generic-testing
    
about:
  summary: Lua is a powerful, fast, lightweight, embeddable scripting language
  license: MIT
  license_file: doc/readme.html
  homepage: http://www.lua.org/

extra:
  recipe-maintainers:
  - DerThorsten
  - JohanMabille
