context:
  name: r-xml2
  version: 1.6.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url:
  - https://cran.r-project.org/src/contrib/${{ name[2:] }}_${{ version }}.tar.gz
  - https://cloud.r-project.org/src/contrib/${{ name[2:] }}_${{ version }}.tar.gz
  sha256: b0660edab0a839866a0cccd44721c54d497000fd6577a25106a33280318bf579

build:
  number: 0
  skip: ${{ r_base == '4.6.0' }}
  script: $R CMD INSTALL $R_ARGS .

requirements:
  build:
  - cross-r-base_${{ target_platform }} ==${{ r_base }}
  - ${{ compiler('c') }}
  - r-cli
  - r-rlang
  host:
  - r-base ==${{ r_base }}
  - r-cli
  - r-rlang
  - libxml2
  run:
  - r-cli
  - r-rlang

tests:
- package_contents:
    lib:
    - R/library/${{ name[2:] }}/libs/${{ name[2:] }}.so
- script: run_r_test test-r-xml2.R
  files:
    recipe:
    - test-r-xml2.R
  requirements:
    build:
    - r-wasm-tester

about:
  homepage: https://xml2.r-lib.org/
  repository: https://github.com/r-lib/xml2
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: XML Tools for R
  description: |
    Tools for working with XML files in R.

extra:
  recipe-maintainers:
  - DerThorsten
