context:
  name: cliquer
  version: 1.21

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: http://users.aalto.fi/~pat/cliquer/cliquer-${{ version }}.tar.gz
  sha256: ff306d27eda82383c0257065e3ffab028415ac9af73bccfdd9c2405b797ed1f1

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - ${{ compiler('cxx') }}

tests:
- package_contents:
    files:
    - lib/libcliquer.a
    - include/cliquer/cliquer.h
    - bin/cl
    - bin/cl.wasm

about:
  homepage: https://users.aalto.fi/~pat/cliquer.html
  license: GPL-2.0-only
  license_file: LICENSE
  summary: Cliquer is a set of C routines for finding cliques in an arbitrary weighted graph.

extra:
  recipe-maintainers:
  - wangyenshu