context:
  name : Biobase
  version: 2.72.0
package:
  name: bioconductor-${{ name | lower }}
  version: ${{ version }}

source:
  url: https://www.bioconductor.org/packages/release/bioc/src/contrib/${{ name }}_${{ version }}.tar.gz
  sha256: d04af4c5850352f96a966285ea771b15777d2f009f7b86fa4b702de13f31bbdd

build:
  number: 0
  skip: ${{ r_base == '4.6.0' }}
  script: $R CMD INSTALL $R_ARGS .

requirements:
  build:
  - cross-r-base_${{ target_platform }} ==${{ r_base }}
  - ${{ compiler('c') }}
  - bioconductor-biocgenerics 
  host:
  - r-base ==${{ r_base }}
  - bioconductor-biocgenerics
  run:
  - bioconductor-biocgenerics

tests:
- package_contents:
    lib:
    - R/library/${{ name }}/libs/${{ name }}.so

about:
  repository: https://github.com/Bioconductor/Biobase/
  license: Artistic-2.0
  license_file: LICENSE
  summary: Functions that are needed by many other packages or which replace R functions.



extra:
  recipe-maintainers:
  - DerThorsten
