context:
  version: 23.1.1
  major_version: 23

package:
  name: clang-resource-headers
  version: ${{ version }}

source:
  url: https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-${{ version }}.tar.gz
  sha256: 851b3d701a4fbdd9f69536d4acda578469e810ca7056687d6556443f5fd39557

build:
  number: 0
  noarch: generic

tests:
- package_contents:
    files:
    - lib/clang/${{ major_version }}/include/wasm_simd128.h

about:
  license: Apache-2.0 WITH LLVM-exception
  license_family: Apache
  license_file: LICENSE.TXT
  summary: Clang resource headers extracted from LLVM.
  homepage: https://llvm.org
extra:
  recipe-maintainers:
  - anutosh491
