context:
  version: 22.1.8
  major_version: 22

package:
  name: clang-resource-headers
  version: ${{ version }}

source:
  url: https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-${{ version }}.tar.gz
  sha256: ad18b70e287954c3d62bc7e0b86e7b7af2adf87bcfce21c15fe717f101d7aace

build:
  number: 0
  noarch: generic

tests:
  - package_contents:
      files:
        - lib/clang/${{ major_version }}/include/wasm_simd128.h

about:
  license: Apache-2.0 WITH LLVM-exception
  license_family: Apache
  license_file: LICENSE.TXT
  summary: Clang resource headers extracted from LLVM.
  homepage: https://llvm.org
extra:
  recipe-maintainers:
    - anutosh491
