context:
  version: 2.14.2

recipe:
  name: freetype-split

source:
  url: https://download.savannah.gnu.org/releases/freetype/freetype-${{ version }}.tar.gz
  sha256: 752c2671f85c54a84b7f0dd2b5cd26b6b741117033886ffbc5ac89a68464b848

build:
  number: 0

outputs:
- package:
    name: freetype
    version: ${{ version }}

  build:
    script: build_static.sh
  requirements:
    build:
    - ${{ compiler('c') }}
    - cmake
    - make
    host:
    - libpng
    - zlib

  tests:
  - script:
    - test -f $PREFIX/include/freetype2/freetype/freetype.h
    - test -f $PREFIX/include/freetype2/ft2build.h
    - test -f $PREFIX/lib/libfreetype.a

- package:
    name: freetype-shared
    version: ${{ version }}

  build:
    script: build_shared.sh
  requirements:
    build:
    - ${{ compiler('c') }}
    - cmake
    - ninja
    host:
    - libpng
    - zlib

  tests:
  - script:
    - test -f $PREFIX/include/freetype2/freetype/freetype.h
    - test -f $PREFIX/include/freetype2/ft2build.h
    - test -f $PREFIX/lib/libfreetype.so

about:
  homepage: https://www.freetype.org/
  license: GPL-2.0-only OR FTL
  license_file:
  - docs/GPLv2.TXT
  - docs/FTL.TXT
  summary: A Free, High-Quality, and Portable Font Engine
  description: |
    FreeType is designed to be small, efficient, highly customizable
    and portable while capable of producing high-quality output (glyph images)
    of most vector and bitmap font formats.
  documentation: http://freetype.sourceforge.net/freetype2/documentation.html
  repository: http://git.savannah.gnu.org/cgit/freetype/

extra:
  recipe-maintainers:
  - wolfv
  - anutosh491
