#!/usr/bin/env bash
set -euxo pipefail

OPENBLAS_LIB="${PREFIX}/lib/libopenblas.a"

export CXXFLAGS="${CXXFLAGS:-} -s ALLOW_MEMORY_GROWTH=1 -s MAXIMUM_MEMORY=4GB"
export LDFLAGS="${LDFLAGS:-} -s ALLOW_MEMORY_GROWTH=1 -s MAXIMUM_MEMORY=4GB"

emcmake cmake . \
    -DCMAKE_INSTALL_PREFIX="${PREFIX}" \
    -DCMAKE_PREFIX_PATH="${PREFIX}" \
    -DCMAKE_C_FLAGS="${CFLAGS:-}" \
    -DCMAKE_CXX_FLAGS="${CXXFLAGS:-}" \
    -DCMAKE_EXE_LINKER_FLAGS="${LDFLAGS:-}" \
    -DCMAKE_SHARED_LINKER_FLAGS="${LDFLAGS:-}" \
    -DBUILD_SHARED_LIBS=OFF \
    -DSUITESPARSE_USE_FORTRAN=OFF \
    -DSUITESPARSE_USE_CUDA=OFF \
    -DSUITESPARSE_USE_OPENMP=OFF \
    -DGRAPHBLAS_USE_JIT=OFF \
    -DBLAS_FOUND=TRUE \
    -DLAPACK_FOUND=TRUE \
    -DBLAS_LIBRARIES="$OPENBLAS_LIB" \
    -DLAPACK_LIBRARIES="$OPENBLAS_LIB" \
    -DBLA_VENDOR=OpenBLAS \
    -DSUITESPARSE_ENABLE_PROJECTS="all"

emmake make -j8
emmake make install