context:
  version: 10.8.4

package:
  name: passagemath-ecl
  version: ${{ version }}

source:
- url: https://pypi.org/packages/source/p/passagemath-ecl/passagemath_ecl-${{ version }}.tar.gz
  sha256: e0f2e0e9785867739695a4e229db474b09a580a0cbe4d409489ae03c752adaac

build:
  script: ${{ PYTHON }} -m pip install .
  number: 0

requirements:
  build:
  - python
  - crossenv >=1.2
  - cross-python_emscripten-wasm32
  - ${{ compiler("c") }}
  - ${{ compiler("cxx") }}
  - pip
  - passagemath-setup
  - passagemath-environment
  - cython
  - cysignals
  - pkgconfig
  - passagemath-abi == ${{ version }}
  host:
  - python
  - ecl
  - passagemath-categories
  run:
  - python
  - cysignals
  - passagemath-categories
  - passagemath-environment

tests:
- script: pytester
  files:
    recipe:
    - test_passagemath_ecl.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run
    - passagemath-repl

about:
  license: GPL-2.0-or-later
  license_file: README.rst
  summary: 'passagemath: Embeddable Common Lisp'
  description: |
    Distribution of a part of the Sage library.
    It provides the Python and Cython interfaces to Embeddable Common Lisp.

extra:
  emscripten_tests:
    python:
      pytest_files:
      - test_passagemath_ecl.py
  recipe-maintainers:
  - mkoeppe
