context:
  version: 0.21.0

package:
  name: xleaflet
  version: ${{ version }}

source:
  url: https://github.com/jupyter-xeus/xleaflet/archive/refs/tags/${{ version }}.tar.gz
  sha256: 6553676a2b634a7e16d03defb4b07c25e413fc834f6e24799ded375c0ba92909
  patches:
  - patches/shared.patch

build:
  number: 0

requirements:
  build:
  - ${{ compiler("cxx") }}
  - cmake
  - make
  host:
  - xproperty >=0.12.0,<0.13
  - xwidgets >=0.29.0,<0.30
  - xtensor>=0.27,<0.28

tests:
- script:
  - test -f $PREFIX/share/xleaflet/basemaps.json
  - test -f $PREFIX/lib/libxleaflet.so

about:
  license: BSD-3-Clause
  license_family: BSD-3
  license_file: LICENSE
  summary: C++ backend for the jupyter leaflet widget
  homepage: https://github.com/jupyter-xeus/xleaflet
extra:
  recipe-maintainers:
  - anutosh491
