context:
  version: 4.7-1.2
  name: r-randomforest
  ccname: randomForest

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url:
    - https://cran.r-project.org/src/contrib/${{ ccname }}_${{ version }}.tar.gz
    - https://cloud.r-project.org/src/contrib/${{ ccname }}_${{ version }}.tar.gz
  sha256: aad33227b648bad50412849d7e0fed00fd07f1d1d4a14fa015b4b9f939b04a11

build:
  number: 0
  string: r${{ r_abi_build_tag }}_h${{ hash }}_${{ build_number }}
  script: $R CMD INSTALL $R_ARGS .

requirements:
  build:
    - cross-r-base_${{ target_platform }} ==${{ r_base }}
    - ${{ compiler('c') }}
    - flang_${{ target_platform }}
  host:
    - libflang

tests:
- package_contents:
    lib:
    - R/library/${{ ccname }}/libs/${{ ccname }}.so

about:
  homepage: https://jeroen.r-universe.dev/sys
  repository: https://github.com/jeroen/sys/
  license: GPL-2.0-or-later
  license_family: GPL3
  license_file: GPL-3
  summary: Classification and regression based on a forest of trees using random inputs, based on Breiman (2001)
extra:
  recipe-maintainers:
    - DerThorsten
