context:
  name: atlasofliegroups
  version: 1.0.8

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: http://www.liegroups.org/software/source/1.0.8/atlas_${{ version }}.tgz
  sha256: fdd3db6e7e8cc51c6222fb18800a983b5a25b696b214200c861fcc5924382a66

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - make
    - bison
    - flex
    - python >=3.6

tests:
- package_contents:
    files:
    - bin/atlas.js
    - bin/atlas.wasm
    - bin/Fokko.js
    - bin/Fokko.wasm

about:
  homepage: https://www.liegroups.org
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Atlas of Lie Groups and Representations software.

extra:
  recipe-maintainers:
  - wangyenshu
