context:
  name: atlasofliegroups
  version: master

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/jeffreyadams/atlasofliegroups/archive/refs/heads/master.zip

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - make
    - bison
    - flex
    - python >=3.6

about:
  homepage: https://www.liegroups.org
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Atlas of Lie Groups and Representations software.

extra:
  recipe-maintainers:
  - wangyenshu