context:
  name: cpp-tabulate
  version: '2.0'

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/p-ranav/tabulate/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 80760758c713ce09a07106d5436938565a01a419e492f9a74593abd1b009c4f1

build:
  number: 0

requirements:
  build:
  - ${{ compiler("cxx") }}
  - cmake
  - ninja

about:
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Table Maker for Modern C++
  homepage: https://github.com/p-ranav/tabulate

extra:
  recipe-maintainers:
  - DerThorsten
