context:
  version: 2.2.2

package:
  name: wrapt
  version: ${{ version }}

source:
- url: https://pypi.io/packages/source/w/wrapt/wrapt-${{ version }}.tar.gz
  sha256: 0788e321027c999bf221b667bd4a54aaefd1a36283749a860ac3eb77daed0302

build:
  number: 0

  files:
    exclude:
    - '**/*.pyi'
    - '**/__pycache__/**'
    - '**/*.pyc'
    - '**/test_*.py'
  python:
    skip_pyc_compilation:
    - '**/*.py'
requirements:
  build:
  - ${{ compiler("c") }}
  - cross-python_emscripten-wasm32
  - python
  - pip
  host:
  - python
  run:
  - python

tests:
- script: pytester
  files:
    recipe:
    - test_import_wrapt.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run
about:
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Module for decorators, wrappers and monkey patching

  homepage: https://github.com/GrahamDumpleton/wrapt
