context:
  name: lie
  version: 2.2.2

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: http://www-math.univ-poitiers.fr/~maavl/LiE/conLiE.tar.gz
  sha256: c4d6f67fa17d2bc77c875a5b2ad2b42ffc5cadf30e7d1c64c097648ccb918b1e

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - make
    - bison
    - flex

tests:
- package_contents:
    files:
    - bin/lie.wasm
    - bin/lie.js

about:
  homepage: http://www-math.univ-poitiers.fr/~maavl/LiE/
  license: LGPL-3.0-only
  license_file: README
  summary: A computer algebra package for Lie group computations.

extra:
  recipe-maintainers:
  - wangyenshu