context:
  name: antlr4-runtime
  version: 4.13.2

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/antlr/antlr4/archive/refs/tags/${{ version }}.tar.gz
  sha256: 9f18272a9b32b622835a3365f850dd1063d60f5045fb1e12ce475ae6e18a35bb

build:
  number: 0
  script: build.sh

requirements:
  build:
  - ${{ compiler('c') }}
  - ${{ compiler('cxx') }}
  - cmake
  - ninja

tests:
- package_contents:
    lib:
    - libantlr4-runtime.a
    include:
    - antlr4-runtime/antlr4-runtime.h
- script:
  - build_tests.sh
  requirements:
    build:
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
  files:
    recipe:
    - build_tests.sh
    - tests/

about:
  homepage: https://www.antlr.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: ANTLR (ANother Tool for Language Recognition) C++ runtime library
  description: |
    ANTLR is a powerful parser generator for reading, processing, executing,
    or translating structured text or binary files. This package provides
    the C++ runtime library required to run parsers generated by ANTLR 4.
  documentation: https://github.com/antlr/antlr4/blob/master/doc/index.md
  repository: https://github.com/antlr/antlr4

extra:
  recipe-maintainers:
  - Alex-PLACET
