context:
  name: tarski
  version: 1.42-20260525 

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/kovzol/tarski/archive/refs/tags/${{ version }}.tar.gz
  sha256: 2dce575532151e22101ec015cef8cf759e1610383d573c4177f77cbe90e9dc8f

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - pkg-config
  - ${{ compiler('c') }}
  - ${{ compiler('cxx') }}
  host:
  - openssl
  - zlib

tests:
- package_contents:
    files:
    - bin/tarski.js
    - bin/qepcad.wasm
    - include/qepcad.h
    - lib/qepcad.a

about:
  homepage: https://www.usna.edu/Users/cs/wcbrown/tarski/index.html
  license: LicenseRef-Tarski AND LicenseRef-Saclib AND LicenseRef-Qepcad
  license_file: LICENSE
  summary: Tarski is a system that provides an interface to a number of functions for computing with Tarski formulas and semi-algebraic sets.

extra:
  recipe-maintainers:
  - wangyenshu
