#!/bin/bash
set -ex

# ============================================================================
# Common CMake Configuration
# ============================================================================

# Common CMake settings for all builds
CMAKE_COMMON_ARGS=""
CMAKE_COMMON_ARGS="$CMAKE_COMMON_ARGS -DCMAKE_PREFIX_PATH:PATH=${PREFIX}"
CMAKE_COMMON_ARGS="$CMAKE_COMMON_ARGS -DCMAKE_INSTALL_PREFIX:PATH=${PREFIX}"
CMAKE_COMMON_ARGS="$CMAKE_COMMON_ARGS -DCMAKE_INSTALL_LIBDIR=lib"
CMAKE_COMMON_ARGS="$CMAKE_COMMON_ARGS -DCMAKE_BUILD_TYPE=Release"
CMAKE_COMMON_ARGS="$CMAKE_COMMON_ARGS -DCMAKE_PLATFORM_NO_VERSIONED_SONAME=TRUE"

# Arrow feature flags (used by both Arrow C++ and PyArrow)
ARROW_FEATURES=""
ARROW_FEATURES="$ARROW_FEATURES -DARROW_SIMD_LEVEL=NONE"
ARROW_FEATURES="$ARROW_FEATURES -DARROW_RUNTIME_SIMD_LEVEL=NONE"
ARROW_FEATURES="$ARROW_FEATURES -DARROW_BUILD_SHARED=OFF"
ARROW_FEATURES="$ARROW_FEATURES -DARROW_BUILD_TESTS=OFF"
ARROW_FEATURES="$ARROW_FEATURES -DARROW_ENABLE_TIMING_TESTS=OFF"
ARROW_FEATURES="$ARROW_FEATURES -DARROW_MIMALLOC=OFF"
# Enable features
ARROW_FEATURES="$ARROW_FEATURES -DARROW_COMPUTE=ON"
ARROW_FEATURES="$ARROW_FEATURES -DARROW_COMPUTE_KERNELS=ON"
ARROW_FEATURES="$ARROW_FEATURES -DARROW_CSV=ON"
ARROW_FEATURES="$ARROW_FEATURES -DARROW_JSON=ON"
ARROW_FEATURES="$ARROW_FEATURES -DARROW_FILESYSTEM=ON"
ARROW_FEATURES="$ARROW_FEATURES -DARROW_DATASET=ON"
ARROW_FEATURES="$ARROW_FEATURES -DARROW_ACERO=ON"
ARROW_FEATURES="$ARROW_FEATURES -DARROW_WITH_UTF8PROC=ON"
ARROW_FEATURES="$ARROW_FEATURES -DARROW_WITH_RE2=ON"
ARROW_FEATURES="$ARROW_FEATURES -DARROW_IPC=ON"
ARROW_FEATURES="$ARROW_FEATURES -DARROW_WITH_BROTLI=ON"
ARROW_FEATURES="$ARROW_FEATURES -DARROW_WITH_SNAPPY=ON"
# Enable Parquet with bundled Thrift
ARROW_FEATURES="$ARROW_FEATURES -DARROW_PARQUET=ON"
ARROW_FEATURES="$ARROW_FEATURES -DARROW_DEPENDENCY_SOURCE=BUNDLED"
ARROW_FEATURES="$ARROW_FEATURES -DARROW_THRIFT_USE_SHARED=OFF"
# Disable features (Substrait requires Boost setup, BZ2 has CMake issues)
ARROW_FEATURES="$ARROW_FEATURES -DARROW_SUBSTRAIT=OFF"
ARROW_FEATURES="$ARROW_FEATURES -DARROW_CUDA=OFF"
ARROW_FEATURES="$ARROW_FEATURES -DARROW_FLIGHT=OFF"
ARROW_FEATURES="$ARROW_FEATURES -DARROW_GANDIVA=OFF"
ARROW_FEATURES="$ARROW_FEATURES -DARROW_ORC=OFF"
ARROW_FEATURES="$ARROW_FEATURES -DARROW_AZURE=OFF"
ARROW_FEATURES="$ARROW_FEATURES -DARROW_GCS=OFF"

# ============================================================================
# Build Arrow C++ with all features (except CUDA)
# ============================================================================

mkdir -p build_cpp
cd build_cpp

# Add Emscripten-specific flags to help Boost detect the platform correctly
export CXXFLAGS="${CXXFLAGS} -fms-extensions -pthread"

# Configure Arrow C++ with comprehensive feature set
cmake ${CMAKE_ARGS} \
    ${CMAKE_COMMON_ARGS} \
    ${ARROW_FEATURES} \
    -DARROW_INSTALL_NAME_RPATH=ON \
    -DARROW_EXPORT_SET=ON \
    -Dutf8proc_LIB=${PREFIX}/lib/libutf8proc.a \
    -Dutf8proc_INCLUDE_DIR=${PREFIX}/include \
    -DRapidJSON_DIR=${PREFIX}/lib/cmake/RapidJSON/ \
    -S ../cpp -B ./

# Build and install Arrow C++
emmake make install -j${CPU_COUNT:-8}

