#!/bin/bash

# ============================================================================
# Build PyArrow Python Bindings
# ============================================================================

# Configure PyArrow CMake options (reuse Arrow feature flags from main build)
PYARROW_CMAKE_OPTIONS="-DCMAKE_PREFIX_PATH:PATH=${PREFIX}"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DCMAKE_INSTALL_PREFIX:PATH=${PREFIX}"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DCMAKE_INSTALL_LIBDIR=lib"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DCMAKE_BUILD_TYPE=Release"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DCMAKE_PLATFORM_NO_VERSIONED_SONAME=TRUE"

# Arrow feature flags (same as Arrow C++ build)
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DARROW_SIMD_LEVEL=NONE"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DARROW_RUNTIME_SIMD_LEVEL=NONE"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DARROW_BUILD_SHARED=OFF"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DARROW_BUILD_TESTS=OFF"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DARROW_ENABLE_TIMING_TESTS=OFF"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DARROW_MIMALLOC=OFF"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DARROW_COMPUTE=ON"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DARROW_COMPUTE_KERNELS=ON"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DARROW_CSV=ON"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DARROW_JSON=ON"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DARROW_FILESYSTEM=ON"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DARROW_DATASET=ON"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DARROW_PARQUET=ON"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DARROW_WITH_UTF8PROC=ON"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DARROW_WITH_RE2=ON"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DARROW_DEPENDENCY_SOURCE=BUNDLED"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DARROW_THRIFT_USE_SHARED=OFF"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DARROW_SUBSTRAIT=OFF"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DARROW_CUDA=OFF"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DARROW_FLIGHT=OFF"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DARROW_GANDIVA=OFF"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DARROW_ORC=OFF"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DARROW_AZURE=OFF"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DARROW_GCS=OFF"

# Python paths
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DPython3_INCLUDE_DIR=$PREFIX/include/python${PY_VER}"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DPython3_INCLUDE_DIRS=$PREFIX/include/python${PY_VER}"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DPython3_NumPy_INCLUDE_DIR=$BUILD_PREFIX/lib/python${PY_VER}/site-packages/numpy/_core/include"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DPython3_NumPy_INCLUDE_DIRS=$BUILD_PREFIX/lib/python${PY_VER}/site-packages/numpy/_core/include"

# Arrow component paths (find already-built Arrow C++)
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DArrow_DIR=$PREFIX/lib/cmake/Arrow"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DArrowDataset_DIR=$PREFIX/lib/cmake/ArrowDataset"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DArrowCompute_DIR=$PREFIX/lib/cmake/ArrowCompute"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DArrowAcero_DIR=$PREFIX/lib/cmake/ArrowAcero"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DArrowParquet_DIR=$PREFIX/lib/cmake/ArrowParquet"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DParquet_DIR=$PREFIX/lib/cmake/Parquet"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -Dre2_DIR=$PREFIX/lib/cmake/re2"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -Dutf8proc_LIB=$PREFIX/lib/libutf8proc.a"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -Dabsl_DIR=$PREFIX/lib/cmake/absl"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -Dutf8proc_INCLUDE_DIR=$PREFIX/include"

# Emscripten-specific configuration
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DCMAKE_PROJECT_INCLUDE=$RECIPE_DIR/cmake/overwriteProp.cmake"

# PyArrow feature flags (enable Dataset, Acero, and Parquet)
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DPYARROW_WITH_COMPUTE=ON"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DPYARROW_BUILD_DATASET=ON"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DPYARROW_BUILD_ACERO=ON"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DPYARROW_DATASET=ON"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DPYARROW_ACERO=ON"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DPYARROW_BUILD_PARQUET=ON"
PYARROW_CMAKE_OPTIONS="$PYARROW_CMAKE_OPTIONS -DPYARROW_PARQUET=ON"

export PYARROW_CMAKE_OPTIONS
export _PYTHON_SYSCONFIGDATA_NAME="_sysconfigdata__emscripten_wasm32-emscripten"

echo "PY_VER IS $PY_VER"

# Pretend we are Pyodide
export PYODIDE=1
export PYTHONINCLUDE=$PREFIX/include/python$PY_VER
export CPYTHONLIB=$PREFIX/lib/libpython$PY_VER.a
export NUMPY_LIB="$PREFIX/lib/python$PY_VER/site-packages/numpy"
export SYSCONFIG_NAME="_sysconfigdata__emscripten_wasm32-emscripten"
export ARROW_HOME=$PREFIX
export INCLUDE_NUMPY_FLAGS="-I$PREFIX/lib/python${PY_VER}/site-packages/numpy/_core/include"
export CFLAGS="$CFLAGS $INCLUDE_NUMPY_FLAGS"
export CXXFLAGS="$CXXFLAGS $INCLUDE_NUMPY_FLAGS"
export CFLAGS="$CFLAGS -sWASM_BIGINT"
export CXXFLAGS="$CXXFLAGS -sWASM_BIGINT"
export LDFLAGS="$LDFLAGS -sWASM_BIGINT"

export CMAKE_BUILD_PARALLEL_LEVEL=4

cd $SRC_DIR/python

echo "PYTHON IS $PYTHON"

# Install PyArrow using the pip from the build prefix but targeting the host prefix
${PYTHON} -m pip install . -vvv

SP=$PREFIX/lib/python${PY_VER}/site-packages/

# Copy libarrow_python.so to $PREFIX/lib so it can be found as a dependency by WASM side modules
# The Cython extensions (_compute.so, lib.so, etc.) depend on libarrow_python.so
cp "$SP/pyarrow/libarrow_python.so" "$PREFIX/lib/libarrow_python.so"

# Clean up tests and disabled modules
rm -rf $SP/pyarrow/tests
rm -rf $SP/pyarrow/__pycache__/

# Remove files for disabled features
rm -f $SP/pyarrow/_cuda.pxd
rm -f $SP/pyarrow/_cuda.pyx
rm -f $SP/pyarrow/_flight.pyx
rm -f $SP/pyarrow/_gcsfs.pyx
rm -f $SP/pyarrow/_hdfs.pyx

cd $PREFIX
find . -name "*.pyc" -exec rm -f {} \;
