context:
  name: fplll
  version: 5.5.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/fplll/fplll/releases/download/${{ version }}/fplll-${{ version }}.tar.gz
  sha256: f0af6bdd0ebd5871e87ff3ef7737cb5360b1e38181a4e5a8c1236f3476fec3b2

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - pkg-config
  - autoconf-archive
  - ${{ compiler('cxx') }}
  host:
  - gmp
  - mpfr

tests:
- package_contents:
    files:
    - lib/libfplll.a
    - include/fplll.h

about:
  homepage: https://github.com/fplll/fplll
  license: LGPL-2.1-only
  license_file: COPYING
  summary: Lattice algorithms using floating-point arithmetic

extra:
  recipe-maintainers:
  - wangyenshu