context:
  version: 4.2.2

package:
  name: givaro
  version: ${{ version }}

source:
  url: https://github.com/linbox-team/givaro/releases/download/v${{ version }}/givaro-${{ version }}.tar.gz
  sha256: 53e9fb290deb0e20799c62d250d65c2226013d60b4cebe6b0b54c73000cb8fff

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - ${{ compiler('cxx') }}
  host:
  - gmp

tests:
- package_contents:
    files:
    - lib/libgivaro.a
    - include/givaro-config.h

about:
  homepage: https://casys.gricad-pages.univ-grenoble-alpes.fr/givaro
  license: CECILL-B
  license_file: Licence_CeCILL-B_V1-en.txt
  summary: C++ library for arithmetic and algebraic computations

extra:
  recipe-maintainers:
  - wangyenshu