context:
  version: 10.8.10

package:
  name: passagemath-planarity
  version: ${{ version }}

source:
- url: https://pypi.org/packages/source/p/passagemath-planarity/passagemath_planarity-${{ version }}.tar.gz
  sha256: d40128712371ba581ae69d34cfe61cb978e5635fcc09f5dde70cea321774dc4e

build:
  script: ${{ PYTHON }} -m pip install .
  number: 0

requirements:
  build:
  - python
  - crossenv >=1.2
  - cross-python_emscripten-wasm32
  - ${{ compiler("c") }}
  - ${{ compiler("cxx") }}
  - pip
  - passagemath-setup
  - passagemath-environment
  - cython<3.3
  - cysignals
  - pkgconfig
  - passagemath-abi == ${{ version }}
  host:
  - python
  - planarity
  run:
  - python
  - cysignals
  - passagemath-graphs

tests:
- script: pytester
  files:
    recipe:
    - test_passagemath_planarity.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run
    - passagemath-repl

about:
  license: GPL-2.0-or-later
  license_file: README.rst
  summary: 'passagemath: Graph planarity with the edge addition planarity suite'
  description: |
    Distribution of a part of the Sage library.
    It provides a Cython interface to the Edge Addition Planarity Suite.

extra:
  emscripten_tests:
    python:
      pytest_files:
      - test_passagemath_planarity.py
  recipe-maintainers:
  - mkoeppe
