context:
  name: fastcan
  version: 0.6.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 11bc5f94828cba1bd983de81f05f3e3526c1322632d2994dda5b9bcef9e7e9f9

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - cross-python_${{ target_platform }}
    - python
    - cython
    - meson-python
    - pip
  host:
    - python
    - scikit-learn >=1.8.0
  run:
    - python
    - scikit-learn >=1.8.0

tests:
- script: pytester
  files:
    recipe:
    - test_fastcan.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run

about:
  license: MIT
  license_file: LICENSE
  summary: A fast canonical-correlation-based search algorithm
  homepage: https://fastcan.readthedocs.io/en/latest/
  repository: https://github.com/scikit-learn-contrib/fastcan/

extra:
  recipe-maintainers:
    - MatthewSZhang