context:
  version: 1.4.4

package:
  name: python-duckdb
  version: ${{ version }}

source:
  git: https://github.com/duckdb/duckdb-python.git
  tag: v${{ version }}
  # expected_commit: a12f36ca411007f5eb48919448f61c7498112553

build:
  number: 0
  script: build.sh

  files:
    exclude:
    - '**.dist-info/**'
    - '**/__pycache__/**'
    - '**/*.pyc'
    - '**/test_*.py'
    - 'duckdb_build/**'
  python:
    skip_pyc_compilation:
    - '**/*.py'

requirements:
  build:
  - python
  - cross-python_${{ target_platform }}
  - ${{ compiler('cxx') }}
  - pip
  - setuptools
  - setuptools-scm
  - pybind11
  - scikit-build-core
  - cmake
  - ninja
  host:
  - python
  - pybind11
  run:
  - python

tests:
- script: pytester
  files:
    recipe:
    - test_duckdb.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run

about:
  homepage: https://duckdb.org/
  license: MIT
  license_file: LICENSE
  summary: DuckDB is an analytical in-process SQL database management system
  description: |
    DuckDB is an in-process SQL OLAP database management system.
    It is designed to support analytical query workloads (OLAP) while
    being embeddable in Python and other languages.
  repository: https://github.com/duckdb/duckdb-python

extra:
  recipe-maintainers:
  - wolfv
