context:
  version: "1.4.4"
  name: python-duckdb

package:
  name: ${{ name }}
  version: ${{ version }}

source:
- url: https://github.com/duckdb/duckdb-python/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 551b0b1ef1c83461a11097011e96e6d84fe8b6ba3c6a342af804cd8bfb275a53

build:
  number: 0
  script: build.sh

requirements:
  build:
    - ${{ compiler('cxx') }}
    - cross-python_${{ target_platform }}
    - python
    - pip
    - setuptools
    - setuptools-scm
    - scikit-build-core
    - pybind11
    - cmake
    - ninja
  host:
    - python
    - pybind11
  run:
    - python

tests:
  - package_contents:
      files:
        - lib/python*/site-packages/duckdb/__init__.py

about:
  homepage: https://duckdb.org/
  license: MIT
  license_file: LICENSE
  summary: DuckDB in-process SQL database compiled for emscripten-wasm32
  description: Python bindings for DuckDB, an in-process SQL OLAP database management system, compiled for emscripten-wasm32.
  repository: https://github.com/duckdb/duckdb-python

extra:
  recipe-maintainers:
    - MRYingLEE
