context:
  name: gfan
  version: "0.8beta"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://users-math.au.dk/jensen/software/gfan/gfan${{ version }}.tar.gz
  sha256: fa7884e5f317c50f8fb4f37bcf5d419f0fd5f7b90d6037349d1957ea73cebbee

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - ${{ compiler("c") }}
  - ${{ compiler('cxx') }}
  - pkg-config
  - autoconf-archive
  host:
    - gmp
    - cddlib
    - onetbb

tests:
  - package_contents:
      bin:
        - gfan
        - gfan.wasm

about:
  homepage: https://users-math.au.dk/jensen/software/gfan/gfan.html
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: Gfan is a software package for computing Gröbner fans and tropical varieties.

extra:
  recipe-maintainers:
    - wangyenshu
