#!/bin/bash
set -euo pipefail

export CFLAGS="${CFLAGS:-} ${EM_FORGE_SIDE_MODULE_CFLAGS:-}"
export CXXFLAGS="${CXXFLAGS:-} ${EM_FORGE_SIDE_MODULE_CFLAGS:-}"
export LDFLAGS="${LDFLAGS:-} ${EM_FORGE_SIDE_MODULE_LDFLAGS:-}"

emcmake cmake -S . -B build \
    -GNinja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="${PREFIX}" \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_PREFIX_PATH="${PREFIX}" \
    -DBUILD_SHARED_LIBS=OFF \
    -DNANOARROW_INSTALL_SHARED=OFF \
    -DNANOARROW_IPC=ON \
    -DNANOARROW_DEVICE=OFF \
    -DNANOARROW_TESTING=OFF \
    -DNANOARROW_BUILD_APPS=OFF \
    -DNANOARROW_BUILD_TESTS=OFF \
    -DNANOARROW_BUILD_TESTS_WITH_ARROW=OFF \
    -DNANOARROW_BUILD_BENCHMARKS=OFF \
    -DNANOARROW_BUILD_INTEGRATION_TESTS=OFF

emmake ninja -C build
emmake ninja -C build install