context:
  version: 23.1.1

package:
  name: llvm-driver
  version: ${{ version }}

source:
  url: https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-${{ version }}.tar.gz
  sha256: 851b3d701a4fbdd9f69536d4acda578469e810ca7056687d6556443f5fd39557
  patches:
  - patches/0001-fix-multicall-tool-aliases.patch

build:
  number: 0
  script: build.sh

requirements:
  build:
  - ${{ compiler("c") }}
  - ${{ compiler("cxx") }}
  - cmake
  - make    # [unix]
  - llvm-tblgen =${{ version }}

tests:
- package_contents:
    files:
    - bin/llvm.js
    - bin/llvm.wasm

about:
  license: Apache-2.0 WITH LLVM-exception
  license_family: Apache
  license_file: LICENSE.TXT
  summary: LLVM's multicall tool driver for WebAssembly hosts
  homepage: https://llvm.org

extra:
  recipe-maintainers:
  - anutosh491
  channel: emscripten-forge-4x-experimental
