context:
  name: cross-r-base

build:
  number: 0

outputs:

- package:
    name: ${{ name }}
    version: 4.5.3
  requirements:
    run:
    - r-base ==4.5.3 h15dba0b_1
  build:
    script: build.sh
  tests:
  - package_contents:
      files:
      - etc/conda/activate.d/activate_z-${{ name }}.sh
      - etc/conda/deactivate.d/deactivate_z-${{ name }}.sh

- package:
    name: ${{ name }}
    version: 4.6.1
  requirements:
    run:
    - r-base ==4.6.1
  build:
    script: build.sh
  tests:
  - package_contents:
      files:
      - etc/conda/activate.d/activate_z-${{ name }}.sh
      - etc/conda/deactivate.d/deactivate_z-${{ name }}.sh

about:
  summary: Package to cross-compile R packages to WebAssembly using Emscripten.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
  - IsabelParedes
