context:
  name: mmh3
  version: 5.2.1

package:
  name: ${{ name }}
  version: ${{ version }}

source:
- url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: bbea5b775f0ac84945191fb83f845a6fd9a21a03ea7f2e187defac7e401616ad

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . ${{ PIP_ARGS }}

  files:
    exclude:
    - '**.dist-info/**'
    - '**/*.pyi'
    - '**/test_*.py'
requirements:
  build:
  - ${{ compiler('c') }}
  - cross-python_${{ target_platform }}
  - python
  - pip
  host:
  - python
  run:
  - python

tests:
- script: pytester
  files:
    recipe:
    - test_import_mmh3.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run

about:
  homepage: https://github.com/hajimes/mmh3
  license: MIT
  license_file: LICENSE
  summary: Python extension for MurmurHash (MurmurHash3), a set of fast and robust hash functions.
  repository: https://github.com/hajimes/mmh3

extra:
  recipe-maintainers:
  - Copilot
