context:
  name: class
  version: 7.3-24

package:
  name: r-${{ name }}
  version: ${{ version | replace('-', '_') }}

source:
  url:
  - https://cran.r-project.org/src/contrib/${{ name }}_${{ version }}.tar.gz
  - https://cloud.r-project.org/src/contrib/${{ name }}_${{ version }}.tar.gz
  sha256: e8c66e57e3f4214ced6fff135a0d9b55f7bd7d6c947b219063de57b275c507e1


build:
  number: 0
  script: $R CMD INSTALL $R_ARGS .
  skip: ${{ r_base == '4.6.1' }}

requirements:
  build:
  - cross-r-base_${{ target_platform }} ==${{ r_base }}
  - ${{ compiler('c') }}
  - r-mass
  host:
  - r-base ==${{ r_base }}
  - r-mass
  run:
  - r-mass

tests:
- package_contents:
    lib:
    - R/library/${{ name }}/libs/${{ name }}.so
- script: run_r_test
  files:
    recipe:
    - test_class.R
  requirements:
    build:
    - r-wasm-tester

about:
  homepage: http://www.stats.ox.ac.uk/pub/MASS4/
  license: GPL-2.0-or-later
  license_family: GPL2
  license_file: ${{ PREFIX }}/lib/R/share/licenses/GPL-2
  summary: Functions for Classification
  description: |
    Various functions for classification, including k-nearest neighbour,
    Learning Vector Quantization and Self-Organizing Maps.

extra:
  recipe-maintainers:
  - DerThorsten
