#!/bin/bash

filtered_args=()
for arg in "$@"; do
    if [[ "$arg" != "--enable-bulk-memory-opt" && "$arg" != "--enable-call-indirect-overlong" ]]; then
        filtered_args+=("$arg")
    fi
done

$BUILD_PREFIX/opt/emsdk/upstream/bin/wasm-opt-original "${filtered_args[@]}"
