context:
  name: readline
  version: 8.3

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://ftp.gnu.org/gnu/readline/readline-${{ version }}.tar.gz
  sha256: fe5383204467828cd495ee8d1d3c037a7eba1389c22bc6a041f627976f9061cc

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - ${{ compiler('cxx') }}

tests:
- package_contents:
    files:
    - lib/libreadline.a
    - include/readline/readline.h

about:
  homepage: https://tiswww.cwru.edu/php/chet/readline/rltop.html
  license: GPL-3.0-only
  license_file: COPYING
  summary: The GNU Readline library provides a set of functions for use by applications that allow users to edit command lines as they are typed in.

extra:
  recipe-maintainers:
  - wangyenshu