context:
  version: 26.5.5

package:
  name: fricas0-ecl
  version: ${{ version }}

source:
- url: https://common-lisp.net/project/ecl/static/files/release/ecl-${{ version }}.tgz
  sha256: "a01a5bcda8c5b73e59dda3494fd13e5fec5db6aa1dad782c3cc3bb57f1633435"
- git_url: https://github.com/wangyenshu/fricas0-web-assets.git
  target_directory: web

build:
  number: 0

requirements:
  build:
  - ${{ compiler("c") }}
  - make
  - pkg-config
  host:
  - gmp
  - libffi
  - libgc
  - libatomic_ops
  - fricas0-data

tests:
- package_contents:
    files:
    - bin/ecl.js
    - bin/ecl.wasm
    - bin/ecl.html
    - libecl.a

about:
  license: LGPL-2.1-or-later
  license_file: LICENSE
  summary: Embeddable Common-Lisp
  homepage: https://ecl.common-lisp.dev/

extra:
  recipe-maintainers:
  - oldk1331
  - wangyenshu