#!/bin/bash
set -e

mkdir -p _build
cd _build

export CFLAGS="$CFLAGS $EM_FORGE_SIDE_MODULE_CFLAGS"
export CXXFLAGS="$CXXFLAGS $EM_FORGE_SIDE_MODULE_CFLAGS"
export LDFLAGS="$LDFLAGS $EM_FORGE_SIDE_MODULE_LDFLAGS"

emcmake cmake -GNinja \
    ${CMAKE_ARGS} \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="${PREFIX}" \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_PREFIX_PATH="${PREFIX}" \
    -DCMAKE_C_FLAGS_RELEASE="$CFLAGS" \
    -DALLOW_IN_SOURCE_BUILD=ON \
    -DJAS_WASM=1 \
    -DJAS_ENABLE_SHARED=OFF \
    -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=BOTH \
    -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=BOTH \
    -DMATH_LIBRARY= \
    -DJAS_ENABLE_LIBJPEG=ON \
    -DJAS_ENABLE_LIBHEIF=OFF \
    -DJAS_ENABLE_OPENGL=OFF \
    -DJAS_ENABLE_DOC=OFF \
    -DJAS_ENABLE_PROGRAMS=OFF \
    -DJAS_STRICT=OFF \
    -DJAS_ENABLE_CXX=OFF \
    -DJAS_ENABLE_CMAKE_PACKAGE_CONFIG=ON \
    ..

ninja install

# Remove .la files if any
find "${PREFIX}" -name '*.la' -delete 2>/dev/null || true
