context:
  version: "3.4.18"
package:
  name: sdl3
  version: ${{ version }}
source:
  url: https://github.com/libsdl-org/SDL/releases/download/release-${{ version }}/SDL3-${{ version }}.tar.gz
  sha256: 9c75cf16330322c217dedd2e0609f1124f1b54b8633e763467b4684d0f4334a3
build:
  number: 0
  script: build.sh
requirements:
  build:
    - ${{ compiler('c') }}
    - cmake
    - ninja
about:
  homepage: https://libsdl.org/
  license: Zlib
  license_file: LICENSE.txt
  summary: SDL3 for emscripten-wasm32
