context:
  name: Macaulay2-vanilla
  version: '1.26.06-vanilla.2'

package:
  name: ${{ name | lower }}
  version: ${{ version }}

source:
- url: https://github.com/pzinn/M2/archive/refs/tags/release-${{ version }}.tar.gz
  sha256: c577342d1721b7a7ab04874e4b31f0910e01e40f0c83a94eb2df895cb0eb0934
- git: https://github.com/wangyenshu/Macaulay2-web-assets.git
  target_directory: web

build:
  number: 1

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - cmake
  - ${{ compiler("c") }}
  - ${{ compiler('cxx') }}
  - pkg-config
  - autoconf-archive
  - bison
  - flex
  - diffutils
  - patch
  - gettext
  - nodejs >=22
  host:
  - 4ti2
  - libgc
  - boost-cpp
  - cddlib
  - csdp
  - eigen
  - fflas-ffpack
  - libflint
  - givaro
  - glpk
  - jansson
  - libxml2
  - lrslib
  - mpfi
  - topcom
  - cohomcalg
  - fplll
  - libfrobby
  - glpk
  - gmp
  - xz
  - memtailor
  - mathic
  - mathicgb
  - mpfr
  - mpsolve
  - nauty
  - normaliz
  - ntl
  - openblas
  - singular
  - lrslib
  - onetbb
  - zlib
  - libffi
  - gfanlib
  - msolve
  - gdbm
  - gtest
  - zlib
  - cocoalib

tests:
- package_contents:
    files:
    - bin/M2-binary.wasm
    - bin/M2-binary.js
    - bin/M2.data
    - bin/M2.data.js

about:
  homepage: https://macaulay2.com/
  license: GPL-2.0-or-later
  license_file:
  - M2/Macaulay2/COPYING-GPL-2
  - M2/Macaulay2/COPYING-GPL-3
  summary: Paul Zinn-Justin's fork of Macaulay2, a system for computing in commutative algebra, algebraic geometry and related fields. 

extra:
  recipe-maintainers:
  - wangyenshu
