context:
  version: 10.8.3

package:
  name: passagemath-m4ri-m4rie
  version: ${{ version }}

source:
- url: https://pypi.org/packages/source/p/passagemath-m4ri-m4rie/passagemath_m4ri_m4rie-${{ version }}.tar.gz
  sha256: 76ab0c8929f50665307687162b23fbf145ba7f8cfcdc367b0acab5a6a05e75a7

build:
  number: 0
  script: |
    export PKG_CONFIG_PATH="$PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"
    ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
  - python
  - crossenv >=1.2
  - cross-python_emscripten-wasm32
  - ${{ compiler("c") }}
  - ${{ compiler("cxx") }}
  - pip
  - passagemath-setup
  - passagemath-environment
  - cython
  - gmpy2
  - cysignals
  - pkgconfig
  - numpy
  - passagemath-abi == ${{ version }}
  host:
  - python
  - libgd
  - libpng
  - gmp
  - zlib
  - numpy
  - m4ri
  - m4rie
  - passagemath-modules
  run:
  - python
  - cysignals
  - passagemath-modules

tests:
- script: pytester
  files:
    recipe:
    - test_passagemath_m4ri_m4rie.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run
    - passagemath-repl

about:
  license: GPL-2.0-or-later
  license_file: README.rst
  summary: 'passagemath: Linear Algebra with m4ri and m4rie'
  description: |
    Distribution of a small part of the Sage library for use with passagemath-modules.
    It provides modules that depend on the libraries m4ri and m4rie
    for dense matrices over GF(2) and GF(2**e) for e from 2 to 16.

extra:
  emscripten_tests:
    python:
      pytest_files:
      - test_passagemath_m4ri_m4rie.py
  recipe-maintainers:
  - mkoeppe
