// Functional test for boost-tti 
// adapted from libs/tti/test

#include <boost/tti/tti.hpp>
#include <iostream>
#include <type_traits>

#define CHECK(x) do { if (!(x)) { std::cerr << "FAIL: " #x << "\n"; return 1; } } while (0)

struct HMember
{
    typedef int AnIntType;      // nested type
    int AnInt;                  // data member
    static long SomeStaticData; // static data member
    enum AnEnum { E1, E2 };     // nested enum
    void VoidFunction() {}
    int aFunction(int x) { return x; }
};

struct HNoMember
{
    double x;
};

// Traits generated by the module's macros (BOOST_TTI_HAS_* declares the
// metafunction; the *_GEN form yields the same metafunction name).
BOOST_TTI_HAS_TYPE(AnIntType)
BOOST_TTI_HAS_DATA(AnInt)
BOOST_TTI_HAS_DATA(x)
BOOST_TTI_HAS_ENUM(AnEnum)
BOOST_TTI_HAS_MEMBER_FUNCTION(VoidFunction)
BOOST_TTI_HAS_MEMBER_FUNCTION(aFunction)

// Real use: SFINAE dispatch on the generated trait.
template<class T>
typename std::enable_if<has_type_AnIntType<T>::value, int>::type classify() { return 1; }

template<class T>
typename std::enable_if<!has_type_AnIntType<T>::value, int>::type classify() { return 0; }

int main()
{
    // Compile-time checks on the module's actual trait values.
    static_assert(has_type_AnIntType<HMember>::value, "nested type");
    static_assert(!has_type_AnIntType<HNoMember>::value, "no nested type");
    static_assert(has_data_AnInt<HMember, int>::value, "member data");
    static_assert(!has_data_AnInt<HMember, long>::value, "wrong member data type");
    static_assert(!has_data_x<HMember, double>::value, "member absent");
    static_assert(has_data_x<HNoMember, double>::value, "other member present");
    static_assert(has_enum_AnEnum<HMember>::value, "nested enum");
    static_assert(!has_enum_AnEnum<HNoMember>::value, "no enum");
    static_assert((has_member_function_VoidFunction<void (HMember::*)()>::value), "mem fn");
    static_assert((has_member_function_aFunction<int (HMember::*)(int)>::value), "mem fn sig");
    static_assert(!(has_member_function_aFunction<void (HMember::*)()>::value), "wrong sig");
    static_assert(!(has_member_function_aFunction<int (HNoMember::*)(int)>::value), "absent fn");

    // Runtime dispatch driven by the traits.
    CHECK(classify<HMember>() == 1);
    CHECK(classify<HNoMember>() == 0);

    std::cout << "boost-tti OK\n";
    return 0;
}
