context:
  name: quadprog
  version: 1.5-8

package:
  name: r-${{ name | lower }}
  version: ${{ version | replace('-', '_') }}

source:
  url:
  - https://cran.r-project.org/src/contrib/${{ name }}_${{ version }}.tar.gz
  - https://cloud.r-project.org/src/contrib/${{ name }}_${{ version }}.tar.gz
  - https://cran.r-project.org/src/contrib/Archive/${{ name }}/${{ name }}_${{ version }}.tar.gz
  sha256: 22128dd6b08d3516c44ff89276719ad4fe46b36b23fdd585274fa3a93e7a49cd

build:
  number: 0
  # skip: ${{ r_base == '4.6.1' }} ONLY IF NEEDED

requirements:
  build:
  - cross-r-base_${{ target_platform }} ==${{ r_base }}
  - ${{ compiler('c') }}
  - ${{ compiler('fortran') }}
  host:
  - r-base ==${{ r_base }}
  - libflang

tests:
- package_contents:
    lib:
    - R/library/${{ name }}/libs/${{ name }}.so
- script: run_r_test test_${{ name }}.R
  files:
    recipe:
    - test_${{ name }}.R
  requirements:
    build:
    - r-wasm-tester

about:
  homepage: https://cran.r-project.org/package=${{ name }}
  documentation: https://cran.r-project.org/web/packages/${{ name }}/refman/${{ name }}.html
  repository: https://cran.r-project.org/package=${{ name }}
  license: GPL-2.0-or-later
  license_family: GPL
  license_file:
  - ${{ PREFIX }}/lib/R/share/licenses/GPL-2
  summary: Functions to Solve Quadratic Programming Problems
  description: |-
    This package contains routines and documentation for
    solving quadratic programming problems.

extra:
  recipe-maintainers:
  - DerThorsten
