context:
  version: 11.6.0

package:
  name: ntl
  version: ${{ version }}

source:
  url: https://libntl.org/ntl-${{ version }}.tar.gz
  sha256: bc0ef9aceb075a6a0673ac8d8f47d5f8458c72fe806e4468fbd5d3daff056182

build:
  number: 0

requirements:
  build:
  - ${{ compiler("cxx") }}
  - gmp

tests:
- package_contents:
    files:
      - lib/libntl.a

about:
  license: LGPL-2.1-or-later
  license_file: README
  summary: Library for number theory
  homepage: https://libntl.org/

extra:
  recipe-maintainers:
  - mkoeppe
