context:
  name: biopython
  version: '1.87'

package:
  name: biopython
  version: ${{ version }}

source:
- url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 8456c803459b679a9712422e5a7fd9809f2f089bf69bb085f3b077946ac9bdbf

build:
  number: 0

  files:
    exclude:
    - '**/*.pyc'
    - '**/__pycache__/**'
    - '**.dist-info/**'
    - '**/test_*.py'
  python:
    skip_pyc_compilation:
    - '**/*.py'
requirements:
  build:
  - cross-python_emscripten-wasm32
  - python
  - ${{ compiler('c') }}
  - pip
  host:
  - python
  run:
  - numpy

tests:
- script: pytester
  files:
    recipe:
    - test_import_biopython.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run

about:
  license: BSD-3-Clause
  license_file: LICENSE.rst
  homepage: http://biopython.org
  summary: Collection of freely available tools for computational molecular biology
