context:
  version: 0.9.0

package:
  name: xeus-lua
  version: ${{ version }}

source:
  url: https://github.com/jupyter-xeus/xeus-lua/archive/refs/tags/${{ version }}.tar.gz
  sha256: 96bc65272e0140c6de0894f5243f1393dfe7d8e9e847eb624cb6a5ed00de9fe2

build:
  number: 0

requirements:
  build:
  - ${{ compiler("cxx") }}
  - cmake
  - ninja
  host:
  - lua
  - nlohmann_json
  - nlohmann_json-abi
  - xeus-lite
  - xeus
  - xtl
  - xcanvas
  - xwidgets

tests:
- script:
  - test -f $PREFIX/bin/xlua.wasm
  - test -f $PREFIX/bin/xlua.js
  - test -f $PREFIX/share/jupyter/kernels/xlua/kernel.json
  - test -f $PREFIX/share/jupyter/kernels/xlua/logo-32x32.png
  - test -f $PREFIX/share/jupyter/kernels/xlua/logo-64x64.png

about:
  license: BSD-3-Clause
  license_family: BSD-3
  license_file: LICENSE
  summary: xeus-lua
  homepage: https://github.com/jupyter-xeus/xeus-lua

extra:
  recipe-maintainers:
  - DerThorsten
  - martinRenou
  - JohanMabille
