context:
  version: 0.10.1

package:
  name: xeus-lua
  version: ${{ version }}

source:
  url: https://github.com/jupyter-xeus/xeus-lua/archive/refs/tags/${{ version }}.tar.gz
  sha256: fd9f9d9e40b7c2ff864a0b0d2cf50cbd8038edcb660590c934fbe7c5c041244e

build:
  number: 0

requirements:
  build:
  - ${{ compiler("cxx") }}
  - cmake
  - ninja
  host:
  - lua <5.5
  - nlohmann_json
  - xeus-lite >=5.0,<6.0
  - xeus >=6.0,<7.0
  - xcanvas >=0.7,<0.8
  - xwidgets >=0.30,<0.31

about:
  license: BSD-3-Clause
  license_family: BSD-3
  license_file: LICENSE
  summary: xeus-lua
  homepage: https://github.com/jupyter-xeus/xeus-lua
extra:
  recipe-maintainers:
  - DerThorsten
  - martinRenou
  - JohanMabille
tests:
- script:
  - test -f $PREFIX/bin/xlua.wasm
  - test -f $PREFIX/bin/xlua.js
  - test -f $PREFIX/share/jupyter/kernels/xlua/kernel.json
  - test -f $PREFIX/share/jupyter/kernels/xlua/logo-32x32.png
  - test -f $PREFIX/share/jupyter/kernels/xlua/logo-64x64.png
