context:
  name: 4ti2
  version: 1.6.15

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/4ti2/4ti2/releases/download/Release_${{ version | replace('.','_') }}/4ti2-${{ version }}.tar.gz
  sha256: 070e639398fda1a4665b3291e5ea80f2ba280d9bffd50656ad8482d471b96965

build:
  number: 0

requirements:
  build:
  - ${{ compiler('cxx') }}
  - libtool
  - m4
  - make
  - gnuconfig
  host:
  - glpk
  - gmp
  - zlib

tests:
- package_contents:
    files:
    - include/4ti2/4ti2.h
    - lib/lib4ti2gmp.a

about:
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: Algebraic, geometric and combinatorial problems on linear spaces
  homepage: https://4ti2.github.io/

extra:
  recipe-maintainers:
  - mkoeppe
