context:
  name: r-matrixStats
  version: 1.5.0

package:
  name: ${{ name | lower }}
  version: ${{ version }}

source:
  url:
  - https://cran.r-project.org/src/contrib/${{ name[2:] }}_${{ version }}.tar.gz
  - https://cloud.r-project.org/src/contrib/${{ name[2:] }}_${{ version }}.tar.gz
  sha256: 12996c5f3e6fc202a43e1087f16a71b7fa93d7e908f512542c7ee89cf95dcc15

build:
  number: 4
  script: $R CMD INSTALL $R_ARGS .

requirements:
  build:
  - cross-r-base_${{ target_platform }} ==${{ r_base }}
  - ${{ compiler('cxx') }}
  host:
  - r-base ==${{ r_base }}

tests:
- package_contents:
    lib:
    - R/library/${{ name[2:] }}/libs/${{ name[2:] }}.so

about:
  homepage: https://cran.r-project.org/package=matrixStats
  repository: https://github.com/HenrikBengtsson/matrixStats
  license: Artistic-2.0
  license_family: Artistic
  license_file: LICENSE
  summary: High-performing functions operating on rows and columns of matrices
  description: |
    High-performing functions operating on rows and columns of matrices, e.g.
    col / rowMedians(), col / rowRanks(), and col / rowSds(). Functions
    optimized per data type and for subsetted calculations such that both memory
    usage and processing time is minimized. There are also optimized vector-
    based methods, e.g. binMeans(), madDiff() and weightedMedian().

extra:
  recipe-maintainers:
  - DerThorsten
