context:
  version: 2.5.0

package:
  name: fflas-ffpack
  version: ${{ version }}

source:
  url: https://github.com/linbox-team/fflas-ffpack/releases/download/v${{ version }}/fflas-ffpack-${{ version }}.tar.gz
  sha256: dafb4c0835824d28e4f823748579be6e4c8889c9570c6ce9cce1e186c3ebbb23

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - pkg-config
  - ${{ compiler('cxx') }}
  host:
  - openblas
  - givaro
  - gmp

tests:
- package_contents:
    files:
    - include/fflas-ffpack/fflas-ffpack.h
    - include/fflas-ffpack/fflas/fflas.h
    - include/fflas-ffpack/ffpack/ffpack.h

about:
  homepage: http://linbox-team.github.io/fflas-ffpack/
  license: LGPL-2.1-only
  license_file: COPYING
  summary: FFLAS-FFPACK is a LGPL-2.1+ source code library for basic linear algebra operations over a finite field.

extra:
  recipe-maintainers:
  - wangyenshu