context:
  name: astropy-healpix
  version: 2.0.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
- url: https://pypi.org/packages/source/a/astropy-healpix/astropy_healpix-${{ version }}.tar.gz
  sha256: 6ce7646dc5b1c09a7ed24b1f23d3e2fce8e3570387220d26a24487ab001b3b0b

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . ${{ PIP_ARGS }}

  files:
    exclude:
    - '**/tests/**'
    - '**/__pycache__/**'
    - '**/*.pyc'
    - '**/test_*.py'
  python:
    skip_pyc_compilation:
    - '**/*.py'

requirements:
  build:
  - python
  - cross-python_${{ target_platform }}
  - numpy
  - ${{ compiler('c') }}
  host:
  - python
  - pip
  - numpy
  - setuptools
  - setuptools_scm
  - extension-helpers
  - wheel
  run:
  - python
  - numpy >=2
  - astropy >=6.1

tests:
- script: pytester
  requirements:
    build:
    - pytester
    run:
    - pytester-run
  files:
    recipe:
    - test_astropy_healpix.py

about:
  homepage: https://astropy-healpix.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: BSD-licensed HEALPix for Astropy
  description: BSD-licensed HEALPix for Astropy

extra:
  recipe-maintainers:
  - astrofrog
  - bsipocz
  - mwcraig
