context:
  version: 7.1.2
package:
  name: imagemagick
  version: ${{ version }}

source:
  url: https://github.com/ImageMagick/ImageMagick/archive/${{ version }}-16.tar.gz
  sha256: aadfa67a104d14a35339de0f2cc286c973a0f43329770c69e9667a22208750fb
build:
  number: 0

  files:
    exclude:
    - share/man/man1/**
requirements:
  build:
  - libtool
  - ${{ compiler('c') }}
  - make
  - pkg-config
  host:
  - libtiff
  - libpng
  - libjpeg-turbo
  - bzip2
  - libxml2
  - openjpeg
  - zlib

tests:
- package_contents:
    files:
    - lib/libMagick++-7.Q8.a
    - include/ImageMagick-7/Magick++.h

about:
  homepage: http://www.imagemagick.org/
  license: AGPL-3.0-only
  license_file: LICENSE
  summary: Software suite to create, edit, compose, or convert bitmap images.

