/*
 * wasm_dlsym.h -- static symbol table used by the dlopen()/dlsym()
 * emulation of the WebAssembly OpenJDK (generated by wasm-dlsym-gen.py).
 */
#ifndef WASM_DLSYM_H
#define WASM_DLSYM_H

struct wasm_dl_symbol {
  const char *name;
  void *addr;
  int lib;          /* index into wasm_dl_libraries */
};

extern const char *const wasm_dl_libraries[];      /* NULL terminated */
extern const struct wasm_dl_symbol wasm_dl_symbols[];  /* sorted by name */
extern const int wasm_dl_symbol_count;

#endif
