context:
  name: spherogram
  version: 2.4.1

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/s/spherogram/spherogram-${{ version }}.tar.gz
  sha256: 9351a77308fee452421b914ae55f3cdaff805692b834777aa6a034a9a85bf970

build:
  number: 0
  script: ${PYTHON} -m pip install . ${PIP_ARGS}

requirements:
  build:
  - ${{ compiler('c') }}
  - cross-python_${{ target_platform }}
  - python
  - pip
  - setuptools
  - wheel
  - cython
  host:
  - python
  run:
  - python
  - decorator
  - networkx
  - packaging
  - snappy-manifolds >=1.4
  - knot-floer-homology >=1.2.2

tests:
- script: pytester
  files:
    recipe:
    - test_spherogram.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run
- package_contents:
    files:
    - lib/python3.13/site-packages/spherogram/planarity.cpython-313-wasm32-emscripten.so
    - lib/python3.13/site-packages/spherogram/planarmap.cpython-313-wasm32-emscripten.so

about:
  homepage: https://github.com/3-manifolds/Spherogram
  license: GPL-2.0-or-later
  license_file: README.rst
  summary: Spherical diagrams for 3-manifold topology, including links and their exteriors
  repository: https://github.com/3-manifolds/Spherogram

extra:
  recipe-maintainers:
  - wangyenshu
