#!/bin/bash





# side module
# export EM_FORGE_SIDE_MODULE_LDFLAGS="${LDFLAGS_BASE} -s SIDE_MODULE=1"
# export EM_FORGE_SIDE_MODULE_CFLAGS="${EM_FORGE_CFLAGS_BASE} -I${PREFIX}/include"

# # wasm bigint
# export LDFLAGS="$LDFLAGS -sWASM_BIGINT"

echo "EM_FORGE_SIDE_MODULE_LDFLAGS" $EM_FORGE_SIDE_MODULE_LDFLAGS
echo "EM_FORGE_SIDE_MODULE_CFLAGS" $EM_FORGE_SIDE_MODULE_CFLAGS


LDFLAGS="$LDFLAGS $EM_FORGE_SIDE_MODULE_LDFLAGS"
CFLAGS="$CFLAGS $EM_FORGE_SIDE_MODULE_CFLAGS"

export LDFLAGS
export CFLAGS


ARCHFLAGS="" ${PYTHON} -m pip install . --verbose
