#!/bin/bash

echo "EM_FORGE_SIDE_MODULE_LDFLAGS" $EM_FORGE_SIDE_MODULE_LDFLAGS
echo "EM_FORGE_SIDE_MODULE_CFLAGS" $EM_FORGE_SIDE_MODULE_CFLAGS


LDFLAGS="$LDFLAGS $EM_FORGE_SIDE_MODULE_LDFLAGS"
CFLAGS="$CFLAGS $EM_FORGE_SIDE_MODULE_CFLAGS"

export LDFLAGS
export CFLAGS


ARCHFLAGS="" ${PYTHON} -m pip install . --verbose
