context:
  name: multidict
  version: 6.8.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 5cd4637ce76312ba1e05eb9c5193fec231f64fee0944e135fa1e951242355b37

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . ${{ PIP_ARGS }}

  files:
    exclude:
    - '**/__pycache__/**'
    - '**/*.pyc'
    - '**/test_*.py'
  python:
    skip_pyc_compilation:
    - '**/*.py'
requirements:
  build:
  - ${{ compiler('cxx')}}
  - cross-python_${{ target_platform }}
  - python
  - cython
  - expandvars
  - pip
  host:
  - python

tests:
- script: pytester
  requirements:
    build:
    - pytester
    run:
    - pytester-run
  files:
    recipe:
    - test_import_multidict.py

about:
  homepage: https://github.com/aio-libs/multidict
  summary: multidict implementation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
  - Copilot
