context:
  name: lcalc
  version: 2.2.1

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://gitlab.com/sagemath/lcalc/-/archive/${{ version }}/lcalc-${{ version }}.tar.gz
  sha256: ed6b7c33da64093bf82b6b3e481e2520e68f1e1d571d65a7aead2b4a6b43dba7

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - ${{ compiler("c") }}
  - ${{ compiler('cxx') }}
  - pkg-config
  - autoconf-archive
  - gengetopt
  host:
  - pari
  - gmp

tests:
  - package_contents:
      files:
        - bin/lcalc
        - lib/pkgconfig/lcalc.pc

about:
  homepage: https://gitlab.com/sagemath/lcalc
  license: GPL-2.0-only
  license_file: README.md
  summary: Lcalc is a package for working with L-functions.

extra:
  recipe-maintainers:
  - wangyenshu