package:
  name: sourmash
  version: '4.7.0'

source:
- url: https://codeload.github.com/sourmash-bio/sourmash/tar.gz/fecfc97c3ec0be1dcfe43c73a12297f1295b5199
  sha256: 0dff73ca2252877108756cc1e53ef5981312a9006be93dfd88cbd7aaaf35f6ae

build:
  number: 0

requirements:
  build:
    - '{{ compiler("c") }}'
    - '{{ compiler("rust") }}'
    - cross-python_emscripten-32
    - python
    - cffi ==1.15.0
    - pip
    - maturin
  host:
    - python
    - pip
    - cffi ==1.15.0
    - maturin
    - toml
  run:
    - python
    - screed >=1.1.2
    - cffi >=1.14
    - deprecation >=2.0.6
    - cachetools >=4.2.1,<5
    - numpy
    - matplotlib-base
    - scipy
    - bitstring >=3.1.9,<4

extra:
  emscripten_tests:
    python:
      pytest_files:
      - test_sourmash.py
