package:
  name: sourmash
  version: '4.8.2'

source:
- url:  https://pypi.io/packages/source/s/sourmash/sourmash-4.8.2.tar.gz
  sha256: e0df78032e53ed88977445933ba3481dd10c7d3bd26d019511a6a4e6d7518475

build:
  number: 0

requirements:
  build:
    - '{{ compiler("c") }}'
    - '{{ compiler("rust") }}'
    - cross-python_emscripten-32
    - python
    - cffi ==1.15.0
    - pip
    - maturin
  host:
    - python
    - pip
    - cffi ==1.15.0
    - maturin
    - toml
  run:
    - python
    - screed >=1.1.2
    - cffi >=1.14
    - deprecation >=2.0.6
    - cachetools >=4.2.1,<5
    - numpy
    - matplotlib-base
    - scipy
    - bitstring >=3.1.9,<4

extra:
  emscripten_tests:
    python:
      pytest_files:
      - test_sourmash.py
