context:
  name: harfbuzz
  version: 14.5.1

package:
  name: ${{ name }}-static
  version: ${{ version }}

source:
- url: https://github.com/harfbuzz/harfbuzz/releases/download/${{ version }}/harfbuzz-${{ version }}.tar.xz
  sha256: 7e2fa4e8c7c98e8d8140671f5772542afaaa6acccfbd746506886b6d85f7f8d6
  patches:
  - patches/0001-Disable-threads.patch

build:
  number: 1

requirements:
  build:
  - ${{ compiler('cxx') }}
  - meson
  - ninja
  - pkg-config
  host:
  - freetype-static
  run:
  - ${{pin_compatible('freetype-static', lower_bound='x', upper_bound='x') }}

tests:
- package_contents:
    include:
    - harfbuzz/hb.h
    - harfbuzz/hb-version.h
    lib:
    - libharfbuzz.a
- script:
  - generic-testing
  requirements:
    build:
    - generic-testing

about:
  homepage: https://harfbuzz.github.io/
  license: MIT
  license_file: COPYING
  summary: An OpenType text shaping engine.
  description: |
    HarfBuzz is a text shaping library. New Harbuzz targets various font
    technologies while Old HarfBuzz targets only OpenType fonts.

extra:
  recipe-maintainers:
  - ianthomas23
