context:
  name: harfbuzz
  version: 14.5.0

package:
  name: ${{ name }}-static
  version: ${{ version }}

source:
- url: https://github.com/harfbuzz/harfbuzz/releases/download/${{ version }}/harfbuzz-${{ version }}.tar.xz
  sha256: b7132e148358a45185c9feafd049dbaf243649d3c44414b3534d9c95d18592b9
  patches:
  - patches/0001-Disable-threads.patch

build:
  number: 0

requirements:
  build:
  - ${{ compiler('cxx') }}
  - meson
  - ninja
  - pkg-config
  host:
  - freetype-static
  run:
  - ${{pin_compatible('freetype-static', lower_bound='x.x.x', upper_bound='x.x.x') }}

tests:
- package_contents:
    include:
    - harfbuzz/hb.h
    - harfbuzz/hb-version.h
    lib:
    - libharfbuzz.a
- script:
  - generic-testing
  requirements:
    build:
    - generic-testing

about:
  homepage: https://harfbuzz.github.io/
  license: MIT
  license_file: COPYING
  summary: An OpenType text shaping engine.
  description: |
    HarfBuzz is a text shaping library. New Harbuzz targets various font
    technologies while Old HarfBuzz targets only OpenType fonts.

extra:
  recipe-maintainers:
  - ianthomas23
