context:
  name: fps-kernel-web-worker
  version: 0.2.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/fps_kernel_web_worker-${{ version }}.tar.gz
  sha256: d422e32ac9013030435243056142c040687daeddba96ebe74a793a9e48f1b6e2

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . ${{ PIP_ARGS }}
  noarch: python

  files:
    exclude:
    - '**/__pycache__/**'
    - '**/*.pyc'
    - '**/test_*.py'
  python:
    skip_pyc_compilation:
    - '**/*.py'
requirements:
  build:
  - pip != 25.1
  - cross-python_${{ target_platform }}
  - uv-build
  host:
  - python
  run:
  - python
  - jupyverse-api >=0.14.0,<0.15.0
  - pyjs >=3

tests:
- script: pytester
  requirements:
    build:
    - pytester
    run:
    - pytester-run
  files:
    recipe:
    - test_import_kernelwebworker.py

about:
  homepage: https://github.com/jupyter-server/jupyverse/tree/main/plugins/kernel_web_worker
  license: BSD-3-Clause
  license_file: COPYING.md
  summary: An FPS plugin for the kernel web worker API

extra:
  recipe-maintainers:
  - davidbrochart
