context:
  name: r-factominer
  version: 2.14

package:
  name: ${{ name }}
  version: ${{ version | replace('-', '_') }}

source:
  url:
  - https://cran.r-project.org/src/contrib/FactoMineR_${{ version }}.tar.gz
  - https://cloud.r-project.org/src/contrib/FactoMineR_${{ version }}.tar.gz
  sha256: fd6f934e9dd1e80a4b094cdeba12a1bb305357a742e9241b1a87dfe4e455c168

build:
  number: 5
  string: r${{ r_abi_build_tag }}_h${{ hash }}_${{ build_number }}
  script: $R CMD INSTALL $R_ARGS .

requirements:
  build:
  - cross-r-base_${{ target_platform }} ==${{ r_base }}
  - ${{ compiler('c') }}
  
  - r-car
  - r-cluster
  - r-dt
  - r-ellipse
  - r-emmeans
  - r-flashclust
  - r-graphics
  - r-grdevices
  - r-lattice
  - r-leaps
  - r-mass
  - r-multcompview
  - r-scatterplot3d
  - r-stats
  - r-utils
  - r-ggplot2

  host:
  - r-car
  - r-cluster
  - r-dt
  - r-ellipse
  - r-emmeans
  - r-flashclust
  - r-graphics
  - r-grdevices
  - r-lattice
  - r-leaps
  - r-mass
  - r-multcompview
  - r-scatterplot3d
  - r-stats
  - r-utils
  - r-ggplot2

  run:
  - r-car
  - r-cluster
  - r-dt
  - r-ellipse
  - r-emmeans
  - r-flashclust
  - r-graphics
  - r-grdevices
  - r-lattice
  - r-leaps
  - r-mass
  - r-multcompview
  - r-scatterplot3d
  - r-stats
  - r-utils
  - r-ggplot2
  - r-ggrepel

tests:
- package_contents:
    lib:
    - R/library/FactoMineR/libs/FactoMineR.so

about:
  homepage: https://github.com/husson/FactoMineR/
  repository: https://github.com/husson/FactoMineR/issues
  license: GPL-2.0-or-later
  license_family: GPL3
  license_file: GPL-3
  summary: Exploratory data analysis methods to summarize, visualize and describe datasets.


extra:
  recipe-maintainers:
  - DerThorsten
