context:
  name: r-cluster
  version: "2.1.8.2"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url:
  - https://cran.r-project.org/src/contrib/cluster_${{ version }}.tar.gz
  - https://cloud.r-project.org/src/contrib/cluster_${{ version }}.tar.gz
  sha256: 4cc898a58baade883bb33aa0ee9be1723f321bd85ad91562cbd1e43dfdb41585

build:
  number: 0
  script: $R CMD INSTALL $R_ARGS .

requirements:
  build:
  - cross-r-base_${{ target_platform }} ==${{ r_base }}
  - ${{ compiler('c') }}
  - ${{ compiler('fortran') }}
  host:
  - libflang
  - r-base ==${{ r_base }}

tests:
- package_contents:
    lib:
    - R/library/cluster/libs/cluster.so
- script: run_r_test test_cluster.R
  files:
    recipe:
    - test_cluster.R
  requirements:
    build:
    - r-wasm-tester

about:
  homepage: https://svn.r-project.org/R-packages/trunk/cluster/
  license: GPL-2.0-or-later
  license_file: GPL-2
  summary: "Finding Groups in Data: Cluster Analysis Extended Rousseeuw et al."

extra:
  recipe-maintainers:
  - anutosh491
