context:
  name: rw
  version: 0.10

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pilotfiber.dl.sourceforge.net/project/rankwidth/rw-${{ version }}.tar.gz
  sha256: 89a8ed364893ac1b70ab70a152e3e7db3cf348bb69098aa6dbb969639df927db

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - pkg-config
  - autoconf-archive
  - ${{ compiler('cxx') }}
  host:
  - igraph

tests:
- package_contents:
    files:
    - lib/librw.a
    - include/rw.h

about:
  homepage: https://sourceforge.net/projects/rankwidth/
  license: GPL-2.0-only
  license_file: COPYING
  summary: rw calculates rank-width and rank-decompositions. 

extra:
  recipe-maintainers:
  - wangyenshu