context:
  name: rw
  version: '0.2'

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pilotfiber.dl.sourceforge.net/project/rankwidth/rw-${{ version }}.tar.gz
  sha256: a73c4b527f343bfaa32ef396416f887b5574997e2ec9caeb924770385b050619

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - pkg-config
  - autoconf-archive
  - ${{ compiler('cxx') }}
  host:
  - igraph

tests:
- package_contents:
    files:
    - lib/librw.a
    - include/rw.h

about:
  homepage: https://sourceforge.net/projects/rankwidth/
  license: GPL-2.0-only
  license_file: COPYING
  summary: rw calculates rank-width and rank-decompositions.

extra:
  recipe-maintainers:
  - wangyenshu
