context:
  name: git2cpp
  version: 0.0.10

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/QuantStack/${{ name }}/archive/refs/tags/${{ version }}.tar.gz
  sha256: 2d2a0c55aecb05d82bcfc91377d5c344dc7ea6028c6964afa73d256032f70216

build:
  number: 0

requirements:
  build:
  - ${{ compiler("cxx") }}
  - cli11<2.6.2
  - cmake
  - termcolor-cpp
  host:
  - libgit2>=1.9.0
  - pcre2
  - zlib

tests:
- script:
  - test -f $PREFIX/bin/git2cpp.js
  - test -f $PREFIX/bin/git2cpp.wasm
- script: |
    OUTPUT=$(run_modularized $PREFIX/bin/git2cpp.js --version | cut -c -15)
    if [[ "$OUTPUT" != "git2cpp version" ]]; then
      echo "Unexpected output: $OUTPUT"
      exit 1
    fi
  requirements:
    build:
    - run_modularized >= 0.1.2

about:
  homepage: https://github.com/QuantStack/git2cpp
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
  - ianthomas23
