context:
  version: 0.2.10

package:
  name: xeus-ocaml
  version: ${{ version }}

source:
  url: https://github.com/davy39/xeus-ocaml/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 6ea09c94538b2a13fce17e4c3257e5937cea799888da4fc4f1b309e6c9f98a3b

requirements:
  build:
  - ${{ compiler("cxx") }}
  - cmake      >= 4.0.0
  - ninja
  - opam

  host:
  - nlohmann_json
  - nlohmann_json-abi
  - xeus       >=5.2.6
  - xeus-lite  >=4.0.0

build:
  number: 0

tests:
- script:
  - test -f $PREFIX/bin/xocaml.wasm
  - test -f $PREFIX/bin/xocaml.js

about:
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Ocaml kernel for Jupyter based on xeus
  homepage: https://github.com/davy39/xeus-ocaml

extra:
  recipe-maintainers:
  - Davy39