context:
  name: form
  version: 5.0.1

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/form-dev/form/releases/download/v${{ version }}/form-${{ version }}.tar.gz
  sha256: ce62530a54e5232dfefb6c1ff0e7047372a43941b3c0e0db08b5714fd868722c

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - ${{ compiler("c") }}
  - ${{ compiler('cxx') }}
  - pkg-config
  host:
  - gmp
  - mpfr
  - zstd
  - zlib

tests:
- package_contents:
    files:
    - bin/form
    - bin/form.wasm

about:
  homepage: https://www.nikhef.nl/~form/
  license: GPL-3.0-only
  license_file: COPYING
  summary: The FORM project for symbolic manipulation of very big expressions 

extra:
  recipe-maintainers:
  - wangyenshu