context:
  name: form
  version: 5.0.2

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/form-dev/form/releases/download/v${{ version }}/form-${{ version }}.tar.gz
  sha256: 90a3fbc31a31de50a181e63ce222d0224642a5916fdbb25373913558a6d6921a

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - ${{ compiler("c") }}
  - ${{ compiler('cxx') }}
  - pkg-config
  host:
  - gmp
  - mpfr
  - zstd
  - zlib

tests:
- package_contents:
    files:
    - bin/form
    - bin/form.wasm

about:
  homepage: https://www.nikhef.nl/~form/
  license: GPL-3.0-only
  license_file: COPYING
  summary: The FORM project for symbolic manipulation of very big expressions

extra:
  recipe-maintainers:
  - wangyenshu
