context:
  commit: 722a30ce258eb38bee0a834406aed60a06f32d1d
  version: 0.0.0.dev${{ commit[:7] }}

package:
  name: memtailor
  version: ${{ version }}

source:
  git: https://github.com/broune/memtailor.git
  branch: master
  depth: 1

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - ${{ compiler('cxx') }}

tests:
- package_contents:
    files:
    - lib/libmemtailor.a
    - include/memtailor.h

about:
  repository: https://github.com/broune/memtailor
  license: BSD-3-Clause
  license_file: license.txt
  summary: Memtailor is a C++ library of special purpose memory allocators

extra:
  recipe-maintainers:
  - wangyenshu