context:
  name: memtailor
  version: 1.4

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: 
  - https://github.com/Macaulay2/memtailor/releases/download/v${{ version }}/memtailor-${{ version }}.tar.gz
  sha256: 4d5baebf701b04b44201b75831f451305b572a5bc39235a94567ad4e59ad6cdc

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - ${{ compiler('cxx') }}

tests:
- package_contents:
    files:
    - lib/libmemtailor.a
    - include/memtailor.h

about:
  repository: https://github.com/Macaulay2/memtailor
  license: BSD-3-Clause
  license_file: license.txt
  summary: Memtailor is a C++ library of special purpose memory allocators

extra:
  recipe-maintainers:
  - wangyenshu