context:
  commit: c72c945ba8e18e68e5650e7e4982b86e558abe6c
  version: 0.0.0.dev${{ commit[:7] }}


package:
  name: mathicgb
  version: ${{ version }}

source:
  git: https://github.com/broune/mathicgb.git
  branch: master
  depth: 1

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - pkg-config
  - autoconf-archive
  - ${{ compiler('cxx') }}
  host:
  - memtailor
  - mathic

tests:
- package_contents:
    files:
    - lib/libmathicgb.a
    - include/mathicgb.h

about:
  repository: https://github.com/broune/mathicgb
  summary: Mathicgb is a program for computing Groebner basis and signature Grobner bases.

extra:
  recipe-maintainers:
  - wangyenshu