context:
  name: mathicgb
  version: 1.4

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: 
  - https://github.com/Macaulay2/mathicgb/releases/download/v${{ version }}/mathicgb-${{ version }}.tar.gz
  sha256: 3c13033762fc8e26c6c47e8e2e8557fcbae030f7514372dc47b0c71272b7304e

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - pkg-config
  - autoconf-archive
  - ${{ compiler('cxx') }}
  host:
  - memtailor
  - mathic

tests:
- package_contents:
    files:
    - lib/libmathicgb.a
    - include/mathicgb.h

about:
  repository: https://github.com/Macaulay2/mathicgb
  summary: Mathicgb is a program for computing Groebner basis and signature Grobner bases.

extra:
  recipe-maintainers:
  - wangyenshu