context:
  name: pycairo
  version: 1.29.1

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/pygobject/pycairo/releases/download/v${{ version }}/${{ name }}-${{ version }}.tar.gz
  sha256: 4fbd26b4af24c9787d84cf5448e34eb8dca064b732479aaecd03109520eebd5f

build:
  number: 0
  files:
    exclude:
    - '**/__pycache__/**'
    - '**/*.pyc'
    - '**/test_*.py'
  python:
    skip_pyc_compilation:
    - '**/*.py'

requirements:
  build:
  - ${{ compiler('c') }}
  - cross-python_${{ target_platform }}
  - meson >=0.62
  - ninja
  - pkg-config
  - python
  host:
  - cairo
  - expat
  - fontconfig
  - freetype
  - libffi
  - libpng
  - lzo
  - pixman
  - python
  - zlib
  run:
  - python

tests:
- script: pytester
  files:
    recipe:
    - test_pycairo.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run

about:
  homepage: http://cairographics.org/pycairo/
  license: LGPL-2.1-only OR MPL-1.1
  license_file: COPYING
  summary: Python bindings for the Cairo graphics library.
  repository: https://github.com/pygobject/pycairo/

extra:
  recipe-maintainers:
  - wolfv
