context:
  version: 1.0.19

package:
  name: tkrzw
  version: ${{ version }}

source:
  url: https://dbmx.net/tkrzw/pkg/tkrzw-${{ version }}.tar.gz
  sha256: c88b689c5e9661b8d3c05cb3fd69b5b9792074dc1284eaeda41e961e207a485f
  patches:
  - emscripten.patch
  - emscripten-2.patch
build:
  number: 0

requirements:
  build:
  - ${{ compiler("c") }}
  - ${{ compiler("cxx") }}
  - make

tests:
- package_contents:
    files:
    - include/tkrzw_dbm.h
    - include/tkrzw_dbm_hash.h
    - include/tkrzw_file.h
    - include/tkrzw_langc.h
    - lib/libtkrzw.a

about:
  homepage: https://dbmx.net/tkrzw/
  license: Apache-2.0
  license_file: COPYING
  summary: Tkrzw is a C++ library implementing DBM with various algorithms.

extra:
  recipe-maintainers:
  - wangyenshu
