context:
  version: 1.0.24

package:
  name: tkrzw
  version: ${{ version }}

source:
  url: https://dbmx.net/tkrzw/pkg/tkrzw-${{ version }}.tar.gz
  sha256: 1bb4952a05386fc2398b00251872ffc3ccf47e123e0307b757a6aa16c3a752b0
  patches:
  - emscripten.patch
  - emscripten-2.patch
build:
  number: 1

requirements:
  build:
  - ${{ compiler("c") }}
  - ${{ compiler("cxx") }}
  - make

tests:
- package_contents:
    files:
    - include/tkrzw_dbm.h
    - include/tkrzw_dbm_hash.h
    - include/tkrzw_file.h
    - include/tkrzw_langc.h
    - lib/libtkrzw.a

about:
  homepage: https://dbmx.net/tkrzw/
  license: Apache-2.0
  license_file: COPYING
  summary: Tkrzw is a C++ library implementing DBM with various algorithms.

extra:
  recipe-maintainers:
  - wangyenshu
