context:
  version: 1.0.13

package:
  name: tkrzw
  version: ${{ version }}

source:
  url: https://dbmx.net/tkrzw/pkg/tkrzw-${{ version }}.tar.gz
  sha256: 5ab64332eee698cf2bfef67135ffce9279a5f29065620b45a8a4699cc42cd6ce
  patches:
  - emscripten.patch
  - emscripten-2.patch
build:
  number: 0

requirements:
  build:
  - ${{ compiler("c") }}
  - ${{ compiler("cxx") }}
  - make

tests:
- package_contents:
    files:
    - include/tkrzw_dbm.h
    - include/tkrzw_dbm_hash.h
    - include/tkrzw_file.h
    - include/tkrzw_langc.h
    - lib/libtkrzw.a

about:
  homepage: https://dbmx.net/tkrzw/
  license: Apache-2.0
  license_file: COPYING
  summary: Tkrzw is a C++ library implementing DBM with various algorithms.

extra:
  recipe-maintainers:
  - wangyenshu
