context:
  name: r-gridtext
  version: 0.1.6

package:
  name: ${{ name }}
  version: ${{ version | replace('-', '_') }}

source:
  url: https://cran.r-project.org/src/contrib/${{ name[2:]}}_${{ version }}.tar.gz
  sha256: 2b380e133719582e37cbb68754b0e0b009d95c7ad7e9d3da40d38dd858ee81de

build:
  number: 5
  string: r${{ r_abi_build_tag }}_h${{ hash }}_${{ build_number }}
  script: $R CMD INSTALL $R_ARGS .

requirements:
  build:
  - cross-r-base_${{ target_platform }} ==${{ r_base }}
  - ${{ compiler('c') }}

tests:
- package_contents:
    lib:
    - R/library/${{ name[2:]  }}/libs/${{ name[2:]  }}.so

about:
  homepage: https://cran.r-project.org/package=gridtext
  repository: https://github.com/wilkelab/gridtext
  license: MIT
  license_family: MIT
  license_file: LICENSE



extra:
  recipe-maintainers:
  - DerThorsten
