context:
  name: r-gtools
  version: 3.9.5

package:
  name: ${{ name }}
  version: ${{ version | replace('-', '_') }}

source:
  url: https://cran.r-project.org/src/contrib/${{ name[2:]}}_${{ version }}.tar.gz
  sha256: 72ce7df216d7ea15d3cb669d6d98f21cbfac4923c5830c6ec836d41e06aa92f7

build:
  number: 5
  string: r${{ r_abi_build_tag }}_h${{ hash }}_${{ build_number }}
  script: $R CMD INSTALL $R_ARGS .

requirements:
  build:
  - cross-r-base_${{ target_platform }} ==${{ r_base }}
  - ${{ compiler('c') }}

tests:
- package_contents:
    lib:
    - R/library/${{ name[2:] | upper }}/libs/${{ name[2:] | upper }}.so

about:
  homepage: https://cran.r-project.org/package=gtools
  repository: https://github.com/cran/gtools
  license: GPL-2.0
  license_family: GPL2
  license_file: GPL-2


extra:
  recipe-maintainers:
  - IsabelParedes
