context:
  name : S4Vectors
  version: 0.50.1

package:
  name: bioconductor-${{ name | lower }}
  version: ${{ version }}

source:
  url: https://www.bioconductor.org/packages/release/bioc/src/contrib/${{ name }}_${{ version }}.tar.gz
  sha256: a85dac9e625424bc06501a47ab57abb0d2b4c53aeb4714bd88397cc3cd9c690e

build:
  number: 1
  script: $R CMD INSTALL $R_ARGS .

requirements:
  build:
  - cross-r-base_${{ target_platform }} == 4.5.3
  - ${{ compiler('c') }}
  - bioconductor-biocgenerics # Not yet available for R 4.6.0
  host:
  - r-base == 4.5.3
  - bioconductor-biocgenerics
  run:
  - bioconductor-biocgenerics

tests:
- package_contents:
    lib:
    - R/library/${{ name }}/libs/${{ name }}.so

about:
  repository: https://github.com/Bioconductor/S4Vectors
  license: Artistic-2.0
  license_file: LICENSE
  summary: S4 implementation of vector-like and list-like objects

extra:
  recipe-maintainers:
  - DerThorsten
