context:
  name: boost-histogram
  version: 1.8.0

package:
  name: boost-histogram
  version: ${{ version }}

source:
- url: https://pypi.io/packages/source/b/boost_histogram/boost_histogram-${{ version }}.tar.gz
  sha256: 43d5c4c07315390b4a751165fa1fb00faafcc06c9da5442115063fba0e6130b1
  patches:
  - patches/patch_allow_shared.patch

build:
  number: 0
  script: ${PYTHON} -m pip install . ${PIP_ARGS}

  files:
    exclude:
    - '**/*.pyi'
    - '**/__pycache__/**'
    - '**/*.pyc'
    - '**/test_*.py'
  python:
    skip_pyc_compilation:
    - '**/*.py'
requirements:
  build:
  - python
  - cross-python_emscripten-wasm32
  - ${{ compiler('cxx') }}
  - pip
  - setuptools_scm
  - scikit-build-core
  host:
  - python
  - pybind11
  run:
  - python
  - numpy

tests:
- script: pytester
  files:
    recipe:
    - test_import_boost_histogram.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run

about:
  summary: The Boost::Histogram Python wrapper.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/scikit-hep/boost-histogram
