context:
  name: mpsolve
  version: 3.2.3

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://numpi.dm.unipi.it/wp-content/uploads/2025/08/mpsolve-${{ version }}.tar.bz2
  sha256: 1f2e239c698c783b63a5e6903e76316c0335a01d71c466a8551e8a3f790b3971

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - ${{ compiler("c") }}
  - ${{ compiler('cxx') }}
  - pkg-config
  - autoconf-archive
  host:
  - gmp

tests:
- package_contents:
    files:
    - lib/libmps.a
    - include/mps/mps.h

about:
  homepage: https://numpi.dm.unipi.it/scientific-computing-libraries/mpsolve/
  license: GPL-3.0-only
  license_file: COPYING
  summary: MPSolve is a C package to solve polynomials and secular equations.

extra:
  recipe-maintainers:
  - wangyenshu