#!/usr/bin/env bash
set -euxo pipefail
cmake ${CMAKE_ARGS:-} -S . -B build -GNinja   -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$PREFIX" -DCMAKE_PREFIX_PATH="$PREFIX"   -DBUILD_SHARED_LIBS=OFF -DBUILD_STATIC_LIBS=ON -DBUILD_CURL_EXE=OFF -DBUILD_EXAMPLES=OFF   -DBUILD_LIBCURL_DOCS=OFF -DBUILD_MISC_DOCS=OFF -DBUILD_TESTING=OFF -DHTTP_ONLY=ON   -DCURL_USE_OPENSSL=ON -DCURL_ZLIB=ON -DCURL_BROTLI=OFF -DCURL_ZSTD=OFF   -DCURL_USE_LIBPSL=OFF -DUSE_LIBIDN2=OFF -DUSE_NGHTTP2=OFF -DUSE_NGTCP2=OFF   -DUSE_QUICHE=OFF -DENABLE_ARES=OFF -DENABLE_IPV6=OFF -DENABLE_UNIX_SOCKETS=OFF   -DCURL_DISABLE_SOCKETPAIR=ON -DCURL_CA_BUNDLE=none -DCURL_CA_PATH=none
cmake --build build
cmake --install build
