context:
  name: writexl
  version: 2.0.0

package:
  name: r-${{ name }}
  version: ${{ version }}

source:
  url:
  - https://cran.r-project.org/src/contrib/${{ name }}_${{ version }}.tar.gz
  - https://cloud.r-project.org/src/contrib/${{ name }}_${{ version }}.tar.gz
  - https://cran.r-project.org/src/contrib/Archive/${{ name }}/${{ name }}_${{ version }}.tar.gz
  sha256: dc464354abc68f4aa023ca17d126758fdfadcb21aec1cf5c40f16f34e00dbd3d

build:
  number: 0
  script: $R CMD INSTALL $R_ARGS .

requirements:
  build:
  - cross-r-base_${{ target_platform }} ==${{ r_base }}
  - ${{ compiler('c') }}
  host:
  - r-base ==${{ r_base }}
  - zlib
  run:
  - zlib

tests:
- package_contents:
    lib:
    - R/library/${{ name }}/libs/${{ name }}.so
- script: run_r_test
  files:
    recipe:
    - test_${{ name }}.R
  requirements:
    build:
    - r-wasm-tester

about:
  homepage: https://libxlsxwriter.github.io/
  repository: https://github.com/ropensci/writexl
  documentation: https://docs.ropensci.org/writexl/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Portable, light-weight data frame to xlsx exporter for R
  description: |
    Wraps the libxlsxwriter library to create files in Microsoft Excel 'xlsx'
    format.

extra:
  recipe-maintainers:
  - IsabelParedes
