context:
  name: primecount
  version: '8.6'

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/kimwalisch/primecount/archive/refs/tags/v${{ version }}.tar.gz
  sha256: f394a0e57e129db6440373fa10ca9744cc0de14d0718d1aa073f1434fd87189a

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - ${{ compiler('cxx') }}
  host:
  - primesieve

tests:
- package_contents:
    files:
    - lib/libprimecount.a
    - include/primecount.h
    - bin/primecount.js
    - bin/primecount.wasm

about:
  homepage: https://github.com/kimwalisch/primecount/
  license: BSD-2-Clause
  license_file: COPYING
  summary: Fast prime counting function library

extra:
  recipe-maintainers:
  - wangyenshu
