context:
  name: primecount
  version: 8.5

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/kimwalisch/primecount/archive/refs/tags/v${{ version }}.tar.gz
  sha256: a2dd9714e723388987183776d068d6845b82b2cf8ea44ecb6cea3fd9dde938ea

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - ${{ compiler('cxx') }}

tests:
- package_contents:
    files:
    - lib/libprimecount.a
    - lib/libprimesieve.a
    - include/primecount.h
    - include/primesieve.h
    - bin/primecount.js
    - bin/primecount.wasm

about:
  homepage: https://github.com/kimwalisch/primecount/
  license: BSD-2-Clause
  license_file: COPYING
  summary: Fast prime counting function library 

extra:
  recipe-maintainers:
  - wangyenshu