context:
  name: bliss
  version: '0.77'

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://users.aalto.fi/~tjunttil/bliss/downloads/bliss-${{ version }}.zip
  sha256: acc8b98034f30fad24c897f365abd866c13d9f1bb207e398d0caf136875972a4

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - ${{ compiler("c") }}
  - ${{ compiler('cxx') }}
  - pkg-config
  - autoconf-archive
  host:
  - gmp

tests:
  - package_contents:
      files:
        - bin/bliss.js
        - lib/libbliss.a
        - include/bliss/graph.hh

about:
  license: LGPL-3.0-only AND GPL-3.0-only
  license_file: COPYING
  summary: Combinatorial matrix recognition
  homepage: https://users.aalto.fi/~tjunttil/bliss/index.html

extra:
  recipe-maintainers:
  - mkoeppe
