context:
  version: 0.77

package:
  name: bliss
  version: ${{ version }}

source:
  url: https://github.com/scipopt/bliss/archive/eddc188c79ea1e1f4f865ec0e87b6a1eb955b54c.zip
  sha256: ce288d386692d6693fef92127180db8cccd3945704037b7bdeaf41d43350c7cf

build:
  number: 0

requirements:
  build:
  - ${{ compiler("cxx") }}
  - cmake
  - ninja

tests:
- script:
  - test -d ${PREFIX}/include/bliss

about:
  license: LGPL-3.0-or-later
  license_file: COPYING.LESSER
  summary: Combinatorial matrix recognition
  homepage: https://github.com/discopt/bliss

extra:
  recipe-maintainers:
  - mkoeppe
