context:
  name: rebound
  version: 5.0.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
- url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 9012bc4ceac42da8c1344f54e72b64da4720149875dc069d8e0dd1be0285dc04
  patches:
  - patches/0001-skip-c-extension-on-emscripten.patch
  - patches/0002-load-librebound-from-prefix.patch
  - patches/0003-fix-pyodide-import.patch

build:
  number: 0
  script: ${PYTHON} -m pip install . ${PIP_ARGS} --no-deps --no-build-isolation

  files:
    exclude:
    - '**/__pycache__/**'
    - '**/*.pyc'
    - '**/*.so'
  python:
    skip_pyc_compilation:
    - '**/*.py'

requirements:
  build:
  - cross-python_${{ target_platform }}
  - python
  - setuptools
  - wheel
  - pip
  host:
  - python
  run:
  - python
  - librebound

tests:
- script: pytester
  files:
    recipe:
    - test_import_rebound.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run
    - librebound

about:
  homepage: https://github.com/hannorein/rebound
  license: GPL-3.0-only
  license_file: LICENSE
  summary: An open-source multi-purpose N-body code
  documentation: https://rebound.hanno-rein.de

extra:
  recipe-maintainers:
  - mmesch
