#!/usr/bin/env bash
set -euxo pipefail
cmake ${CMAKE_ARGS:-} -S . -B build -GNinja   -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$PREFIX" -DCMAKE_PREFIX_PATH="$PREFIX"   -DBUILD_SHARED_LIBS=OFF -DSDLIMAGE_INSTALL=ON -DSDLIMAGE_INSTALL_MAN=OFF   -DSDLIMAGE_VENDORED=OFF -DSDLIMAGE_DEPS_SHARED=OFF -DSDLIMAGE_SAMPLES=OFF -DSDLIMAGE_TESTS=OFF   -DSDLIMAGE_BACKEND_STB=ON -DSDLIMAGE_PNG_LIBPNG=OFF -DSDLIMAGE_AVIF=OFF -DSDLIMAGE_JXL=OFF   -DSDLIMAGE_TIF=OFF -DSDLIMAGE_WEBP=ON -DSDLIMAGE_WEBP_SHARED=OFF
cmake --build build
cmake --install build
