context:
  version: 10.8.2

source:
- url: https://pypi.org/packages/source/p/passagemath-environment/passagemath_environment-${{ version }}.tar.gz
  sha256: 1886520b42b8bf09996b1670aa36edee2e5851fab3c873ae84d122aa58147fa3

build:
  number: 1

outputs:
- package:
    name: passagemath-environment
    version: ${{ version }}

  build:
    script: ${{ PYTHON }} -m pip install .
    noarch: python

  requirements:
    build:
    - python
    - crossenv >=1.2
    - cross-python_emscripten-wasm32
    - ${{ compiler("c") }}
    - pip
    - passagemath-abi
    host:
    - python
    - setuptools
    - wheel
    - pip
    run:
    - python
    - packaging
    - platformdirs
    - passagemath-abi == ${{ version }}

  tests:
  - script: pytester
    files:
      recipe:
      - test_passagemath_environment.py
    requirements:
      build:
      - pytester
      run:
      - pytester-run

- package:
    name: passagemath-abi
    version: ${{ version }}

  build:
    noarch: generic
    script: echo "passagemath-abi is built"
  requirements:
    run_exports:
      strong:
      - ${{ pin_subpackage('passagemath-abi', exact=True) }}
  tests:
  - script: echo "passagemath-abi is an empty package."

about:
  summary: 'passagemath: System and software environment'
  license: GPL-2.0-or-later
  license_file: README.rst
  description: |
    Distribution of a small part of the Sage library.
    It provides the connection to the system and software environment.

extra:
  emscripten_tests:
    python:
      pytest_files:
      - test_passagemath_environment.py
  recipe-maintainers:
  - mkoeppe
