context:
  name: jiter
  version: 0.16.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
- url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 7b24c3492c5f4f84a37946ad9cf504910cf6a782d6a4e0689b6673c5894b4a1c

build:
  number: 0

  files:
    exclude:
    - '**/__pycache__/**'
    - '**/*.pyc'
  python:
    skip_pyc_compilation:
    - '**/*.py'

requirements:
  build:
  - cross-python_${{ target_platform }}
  - setuptools-rust
  - rust-nightly
  - maturin
  host:
  - python
  - pip
  run:
  - python

tests:
- script: pytester
  requirements:
    build:
    - pytester
    run:
    - pytester-run
  files:
    recipe:
    - test_import_jiter.py

about:
  license: MIT
  license_file: LICENSE
  summary: Fast iterable JSON parser written in Rust with support for parsing partial JSON
  homepage: https://github.com/pydantic/jiter/tree/main/crates/jiter-python
  repository: https://github.com/pydantic/jiter
  documentation: https://github.com/pydantic/jiter

extra:
  recipe-maintainers:
  - IsabelParedes
