context:
  name: fricas0-data
  version: 

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: 
  sha256: 

build:
  number: 0
  noarch: generic

requirements:
  build:
  - ecl
  - ${{ compiler('cxx') }}

tests:
- package_contents:
    files:


about:
  homepage: https://github.com/oldk1331/fricas0
  license:
  license_file: 
  summary: FriCAS0 -- a pure Common Lisp build 

extra:
  recipe-maintainers:
  - wangyenshu