context:
  name: fricas0-data
  version: 1.3.13

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/oldk1331/fricas0/archive/refs/tags/${{ version }}.tar.gz
  sha256: a26f48558c5b4fe346382cb0d7fa24b638e1a89f3396be8049dc4add9dbda57e

build:
  number: 0
  noarch: generic

requirements:
  build:
  - ecl
  - ${{ compiler('cxx') }}

tests:
- package_contents:
    files: 
    - share/fricas0-data/fricas.lisp

about:
  homepage: https://github.com/oldk1331/fricas0
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: FriCAS0 -- a pure Common Lisp build 

extra:
  recipe-maintainers:
  - wangyenshu