context:
  name: multidict
  version: 7.1.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 61a4e5d81b8d4e4ad61964b230129e7a2b914793d96289029078fc9009f074ec

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . ${{ PIP_ARGS }}

  files:
    exclude:
    - '**/__pycache__/**'
    - '**/*.pyc'
    - '**/test_*.py'
  python:
    skip_pyc_compilation:
    - '**/*.py'
requirements:
  build:
  - ${{ compiler('cxx')}}
  - cross-python_${{ target_platform }}
  - python
  - cython
  - expandvars
  - pip
  host:
  - python-dev
tests:
- script: pytester
  requirements:
    build:
    - pytester
    run:
    - pytester-run
  files:
    recipe:
    - test_import_multidict.py

- script: generic-testing
  requirements:
    build:
    - generic-testing
about:
  homepage: https://github.com/aio-libs/multidict
  summary: multidict implementation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
  - Copilot
