context:
  name: r-sqlite
  version: 3.53.1 
  ccname : RSQLite

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/r-lib/${{ ccname }}/archive/refs/tags/${{ version }}.tar.gz
  sha256: b9282f50dadd726896242af5d0788eed6f2df826c40c6f4842fa81dbd31d4e79

build:
  number: 7
  skip: ${{ r_base == '4.6.0' }}
  script: $R CMD INSTALL $R_ARGS .

requirements:
  build:
  - cross-r-base_${{ target_platform }} ==${{ r_base }}
  - ${{ compiler('c') }}
  - r-bit64
  - r-blob
  - r-dbi
  - r-memoise
  - r-rcpp

  host:
  - r-base ==${{ r_base }}
  - r-bit64
  - r-blob
  - r-dbi
  - r-memoise
  - r-rcpp
  run:
  - r-bit64
  - r-blob
  - r-dbi
  - r-memoise





tests:
- package_contents:
    lib:
    - R/library/${{ ccname }}/libs/${{ ccname }}.so

about:
  homepage: hhttps://cran.r-project.org/web/packages/RSQLite/index.html
  repository: https://github.com/r-dbi/RSQLite
  license: GPL-2.0-only
  license_family: GPL2
  license_file: GPL-2
  summary: Embeds the SQLite database engine in R and provides an interface compliant with the DBI package.



extra:
  recipe-maintainers:
    - DerThorsten
