context:
  version: 3.0.5


package:
  name: howardhinnant_date
  version: ${{ version }}

source:
  url: https://github.com/howardhinnant/date/archive/refs/tags/v${{ version }}.tar.gz
  sha256: ef786edc203daec76475825640b3af247bd08e31fc52217e5ce8f76107b4bb05

build:
  number: 0

requirements:
  build:
  - ${{ compiler("cxx") }}
  - cmake
  - ninja

tests:
- script:
  - test -f $PREFIX/include/date/date.h
  - test -f $PREFIX/include/date/tz.h
  - test -f $PREFIX/lib/cmake/date/dateConfig.cmake
  - test -f $PREFIX/lib/libdate-tz.a

about:
  license: MIT
  license_file: LICENSE.txt
  summary: date
  homepage: https://github.com/howardhinnant/date
extra:
  recipe-maintainers:
  - DerThorsten
