context:
  name : XVector
  version: 0.52.0

package:
  name: bioconductor-${{ name | lower }}
  version: ${{ version }}

source:
  url: https://www.bioconductor.org/packages/release/bioc/src/contrib/${{ name }}_${{ version }}.tar.gz
  sha256: 80b520c984e9da13fe06a2a6bdf712fffa6275705f3d0fb16af60eb5fb28609d

build:
  number: 2
  skip: ${{ r_base == '4.6.0' }}
  script: $R CMD INSTALL $R_ARGS .

requirements:
  build:
  - cross-r-base_${{ target_platform }} ==${{ r_base }}
  - ${{ compiler('c') }}
  - bioconductor-biocgenerics
  - bioconductor-s4vectors
  - bioconductor-iranges
  host:
  - r-base ==${{ r_base }}
  - bioconductor-biocgenerics
  - bioconductor-s4vectors
  - bioconductor-iranges
  run:
  - bioconductor-biocgenerics
  - bioconductor-s4vectors
  - bioconductor-iranges

tests:
- package_contents:
    lib:
    - R/library/${{ name }}/libs/${{ name }}.so

about:
  repository: https://git.bioconductor.org/packages/XVector
  license: Artistic-2.0
  license_file: LICENSE
  summary: Provides memory efficient S4 classes for storing sequences "externally" (e.g. behind an R external pointer, or on disk).



extra:
  recipe-maintainers:
  - DerThorsten
