context:
  version: 10.8.2

package:
  name: passagemath-highs
  version: ${{ version }}

source:
- url: https://pypi.org/packages/source/p/passagemath-highs/passagemath_highs-${{ version }}.tar.gz
  sha256: 9d59f38e97b1fa31b5b8ec026163ed0ba78e8d7db8d3cec4dc7b59221c629c66

build:
  script: ${{ PYTHON }} -m pip install .
  number: 1

requirements:
  build:
  - python
  - crossenv >=1.2
  - cross-python_emscripten-wasm32
  - ${{ compiler("c") }}
  - ${{ compiler("cxx") }}
  - pip
  - passagemath-setup
  - passagemath-environment
  - cython
  - cysignals
  - pkgconfig
  - passagemath-abi
  host:
  - python
  - highs
  - zlib
  - gmp
  - passagemath-categories
  run:
  - python
  - cysignals
  - passagemath-categories

tests:
- script: pytester
  files:
    recipe:
    - test_passagemath_highs.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run
    - passagemath-repl

about:
  license: GPL-2.0-or-later
  license_file: README.rst
  summary: 'passagemath: Linear and mixed integer linear optimization backend using HiGHS'
  description: |
    Distribution of a part of the Sage library.
    It provides a backend for linear and mixed integer linear optimization backend using HiGHS.

extra:
  emscripten_tests:
    python:
      pytest_files:
      - test_passagemath_highs.py
  recipe-maintainers:
  - mkoeppe
