context:
  name: r-Matrix
  version: 1.7-5

package:
  name: ${{ name | lower }}
  version: ${{ version | replace('-', '_') }}

source:
  url:
  - https://cran.r-project.org/src/contrib/${{ name[2:] }}_${{ version }}.tar.gz
  - https://cloud.r-project.org/src/contrib/${{ name[2:] }}_${{ version }}.tar.gz
  sha256: 308b0edd7bcb023a8bb50cc5cec98e66b3658c94a5badfb1ce6024e595fa8a83

build:
  number: 3
  script: $R CMD INSTALL $R_ARGS .

requirements:
  build:
  - ${{ compiler('c') }}
  - cross-r-base_${{ target_platform }} ==${{ r_base }}
  - r-lattice
  host:
  - r-base ==${{ r_base }}
  - r-lattice
  - libblas
  - liblapack
  - libflang
  run:
  - r-lattice

tests:
- package_contents:
    lib:
    - R/library/${{ name[2:] }}/libs/${{ name[2:] }}.so

about:
  homepage: http://Matrix.R-forge.R-project.org/
  license: GPL-2.0-or-later
  license_file: LICENCE
  license_family: GPL3
  summary: Sparse and Dense Matrix Classes and Methods
  description: |
    A rich hierarchy of sparse and dense matrix classes, including general,
    symmetric, triangular, and diagonal matrices with numeric, logical, or
    pattern entries. Efficient methods for operating on such matrices, often
    wrapping the 'BLAS', 'LAPACK', and 'SuiteSparse' libraries.

extra:
  recipe-maintainers:
  - IsabelParedes
  - anutosh491
