context:
  name: river
  version: 0.24.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
- url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: cc94a5fd312d31e7f07ea7e34319f46e0daad5b70918f3f45d3334f2c2d65090

build:
  number: 0
  script: ${PYTHON} -m pip install . ${PIP_ARGS}

  files:
    exclude:
    - '**/*.pyi'
    - '**/*.pxd'
    - '**/*.pyx'
    - '**/__pycache__/**'
    - '**/*.pyc'
    - '**/test_*.py'
  python:
    skip_pyc_compilation:
    - '**/*.py'

requirements:
  build:
  - ${{ compiler('c') }}
  - cross-python_${{ target_platform }}
  - python
  - pip
  - cython
  - numpy
  - setuptools-rust
  - rust-nightly
  - setuptools
  host:
  - python
  - numpy
  - poetry-core
  run:
  - python >=3.11
  - numpy >=1.23.0
  - pandas >=2.2.3,<3.0.0
  - scipy >=1.14.1,<2.0.0
  - typing_extensions

tests:
- script: pytester
  files:
    recipe:
    - test_import_river.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Online machine learning in Python
  homepage: https://github.com/online-ml/river
  documentation: https://riverml.xyz/
  repository: https://github.com/online-ml/river

extra:
  recipe-maintainers:
  - IsabelParedes
