context:
  name: lrslib
  version: 0.71.0
  git_tag: 071b+autotools-2021-07-13

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/passagemath/upstream-lrslib/archive/refs/tags/lrslib-${{ git_tag }}.tar.gz
  sha256: 1ac73fc170100d85d63d73c4d5eacc78059f148464481fe5d05c4072fff65b53

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - ${{ compiler("c") }}
  - ${{ compiler('cxx') }}
  - pkg-config
  - autoconf-archive
  host:
  - gmp

tests:
- package_contents:
    files:
    - lib/liblrs.a
    - include/lrslib.h

about:
  homepage: https://github.com/passagemath/upstream-lrslib/tree/autoconfiscation
  license: GPL-2.0-only
  license_file: COPYING
  summary: Reverse search algorithm for vertex enumeration/convex hull problems by David Avis. Branch "upstream" created from release archives at http://cgm.cs.mcgill.ca/~avis/C/lrs.html.

extra:
  recipe-maintainers:
  - wangyenshu
