context:
  name: pyproj
  version: 3.8.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/p/pyproj/pyproj-${{ version }}.tar.gz
  sha256: efa59725bba68bf97fa808b61302df32934acdceb6a5c92a8dd0e71dc266a876

build:
  number: 0

  files:
    exclude:
    - '**/*.pyi'
    - '**/*.pxi'
    - '**/__pycache__/**'
    - '**/*.pyx'
    - '**/*.pxd'
    - '**/*.pyc'
    - '**/test_*.py'
  python:
    skip_pyc_compilation:
    - '**/*.py'
requirements:
  build:
  - python
  - cross-python_${{ target_platform }}
  - cython
  - ${{ compiler('c') }}
  host:
  - python
  - proj == 9.8.1
  run:
  - python
  - proj
  - certifi

tests:
- script: pytester
  requirements:
    build:
    - pytester
    run:
    - pytester-run
  files:
    recipe:
    - test_pyproj.py


about:
  homepage: https://github.com/pyproj4/pyproj
  license: MIT
  license_file:
  - LICENSE
  - LICENSE_proj
  summary: Python interface to PROJ library

extra:
  recipe-maintainers:
  - KGB99
  - DerThorsten
