context:
  name: cockle_fs
  version: 0.3.0

package:
  name: ${{ name }}
  version: ${{ version }}

build:
  number: 2

requirements:
  build:
    - ${{ compiler("c") }}
    - cmake
    - nodejs
    - typescript<6

tests:
- package_contents:
    files:
    - bin/fs.js
    - bin/fs.wasm
    - bin/fs.d.ts

about:
  homepage: https://github.com/jupyterlite/cockle
  license: BSD-3-Clause
  license_file: LICENSE
  summary: fs for cockle
  documentation: https://github.com/jupyterlite/cockle

extra:
  recipe-maintainers:
    - DerThorsten
    - ianthomas23
