context:
  name: sheenbidi
  version: 3.0.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
- url: https://github.com/Tehreer/SheenBidi/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 86c56014034739ba39a24c23eb00323b0bf6f737354f665786015fca842af786

build:
  number: 0

requirements:
  build:
  - ${{ compiler('c') }}
  - ${{ compiler('cxx') }}
  - meson
  - ninja
  - pkg-config

tests:
  - package_contents:
      include:
      - SheenBidi/SheenBidi.h
      - SheenBidi/SBVersion.h
      lib:
      - libSheenBidi.a

about:
  homepage: https://github.com/Tehreer/SheenBidi
  license: Apache-2.0
  license_file: LICENSE
  summary: A sophisticated implementation of Unicode Bidirectional Algorithm

extra:
  recipe-maintainers:
  - ianthomas23
