context:
  name: aiohttp
  version: 3.11.18

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: ae856e1138612b7e412db63b7708735cff4d38d0399f6a5435d3dac2669f558a

build:
  number: 0

  files:
    exclude:
    - '**/*.pyi'
    - '**/*.pxi'
    - '**/__pycache__/**'
    - '**/*.pyx'
    - '**/*.pxd'
    - '**/*.pyc'
  python:
    skip_pyc_compilation:
    - '**/*.py'

requirements:
  build:
  - ${{ compiler('cxx')}}
  - cross-python_${{ target_platform }}
  - python
  host:
  - python
  run:
  - aiosignal
  - aiohappyeyeballs
  - async-timeout
  - attrs
  - charset-normalizer
  - frozenlist
  - multidict
  - yarl

tests:
- script: pytester
  requirements:
    build:
    - pytester
    run:
    - pytester-run
  files:
    recipe:
    - test_aiohttp.py

about:
  summary: Async http client/server framework (asyncio)
  homepage: https://github.com/aio-libs/aiohttp
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  maintainers:
  - IsabelParedes
