context:
  name: aiohttp
  version: 3.11.17

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 2bf3ff374c3abd7a5c6c8de3ad7ed91e0e89a8b53353314c93766c3add5a208a

build:
  number: 0

  files:
    exclude:
    - '**/*.pyi'
    - '**/*.pxi'
    - '**/__pycache__/**'
    - '**/*.pyx'
    - '**/*.pxd'
    - '**/*.pyc'
  python:
    skip_pyc_compilation:
    - '**/*.py'

requirements:
  build:
  - ${{ compiler('cxx')}}
  - cross-python_${{ target_platform }}
  - python
  host:
  - python
  run:
  - aiosignal
  - aiohappyeyeballs
  - async-timeout
  - attrs
  - charset-normalizer
  - frozenlist
  - multidict
  - yarl

tests:
- script: pytester
  requirements:
    build:
    - pytester
    run:
    - pytester-run
  files:
    recipe:
    - test_aiohttp.py

about:
  summary: Async http client/server framework (asyncio)
  homepage: https://github.com/aio-libs/aiohttp
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  maintainers:
  - IsabelParedes
