#!/bin/bash
# Emit the CMake package config for one boost module package.
#
# Usage: gen_cmake_configs.sh <base> <compiled|header-only> [lib.a ...] [-- dep.a ...]
#   base   plain module name ('filesystem', 'accumulators', 'logic', ...)
#   kind   'compiled' links the module's own archives whole-archive; anything
#          after the optional '--' separator is linked plain (closure deps,
#          e.g. libboost_atomic.a or external libz.a/libbz2.a)
#
# Writes $PREFIX/lib/cmake/boost_<base>/boost_<base>Config.cmake exposing the
# imported target Boost::<base> (INTERFACE; include dir = prefix/include),
# so tests can do: find_package(boost_<base> CONFIG REQUIRED) and link
# Boost::<base>. Paths in the config are relative to CMAKE_CURRENT_LIST_DIR,
# keeping the package relocatable. Invoked from each module output's build
# script (see scripts/gen_boost_deps.py)

set -e

base="$1"
kind="$2"
shift 2

wa=()
deps=()
mode=wa
for a in "$@"; do
    if [ "$a" = "--" ]; then
        mode=deps
        continue
    fi
    if [ "$mode" = wa ]; then wa+=("$a"); else deps+=("$a"); fi
done

out_dir="$PREFIX/lib/cmake/boost_${base}"
mkdir -p "$out_dir"
out="$out_dir/boost_${base}Config.cmake"

{
    echo "# Generated by gen_cmake_configs.sh - package boost-${base}"
    echo "# Exposes target Boost::${base} for find_package(boost_${base} CONFIG)."
    echo 'get_filename_component(_boost_pfx "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)'
    echo "add_library(Boost::${base} INTERFACE IMPORTED)"
    echo "set_target_properties(Boost::${base} PROPERTIES INTERFACE_INCLUDE_DIRECTORIES \"\${_boost_pfx}/include\")"
    if [ "$kind" = "compiled" ]; then
        echo "set_property(TARGET Boost::${base} APPEND PROPERTY INTERFACE_LINK_LIBRARIES \"-Wl,--whole-archive\")"
        for l in "${wa[@]}"; do
            echo "set_property(TARGET Boost::${base} APPEND PROPERTY INTERFACE_LINK_LIBRARIES \"\${_boost_pfx}/lib/${l}\")"
        done
        echo "set_property(TARGET Boost::${base} APPEND PROPERTY INTERFACE_LINK_LIBRARIES \"-Wl,--no-whole-archive\")"
        for l in "${deps[@]}"; do
            echo "set_property(TARGET Boost::${base} APPEND PROPERTY INTERFACE_LINK_LIBRARIES \"\${_boost_pfx}/lib/${l}\")"
        done
    fi
} > "$out"
