context:
  version: 0.48.0
  name: wheel

package:
  name: ${{ name }}
  version: ${{ version }}

source:
- url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 94800765601e9171bf5d58d066e640662842bcedcbab982b2c90787a2c987322

build:
  number: 0

  files:
    exclude:
    - '**/__pycache__/**'
    - '**/*.pyc'
    - '**/test_*.py'
  python:
    skip_pyc_compilation:
    - '**/*.py'
requirements:
  build:
  - ${{ compiler("c") }}
  - cross-python_${{ target_platform }}
  host:
  - python
  - flit-core
  run:
  - python

tests:
- script: pytester
  files:
    recipe:
    - test_import_wheel.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run

about:
  license: MIT
  license_file: LICENSE.txt
  summary: A built-package format for Python.
  homepage: https://github.com/pypa/wheel

extra:
  recipe-maintainers:
  - IsabelParedes
