context:
  version: "5.4.9"
package:
  name: lua
  version: ${{ version }}
source:
  url: https://www.lua.org/ftp/lua-${{ version }}.tar.gz
  sha256: 2335b6c582a52654f94612bf10d2f4672805d05329aa6568b1d8cd9e5c6fb8e6
build:
  number: 0
  script: build.sh
requirements:
  build:
    - ${{ compiler('c') }}
    - cmake
    - ninja
about:
  homepage: https://www.lua.org/
  license: MIT
  license_file: doc/readme.html
  summary: Lua 5.4 static library for Wesnoth/Emscripten
