context:
  name: libcadabra2
  version: 2.5.14

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/kpeeters/cadabra2/archive/refs/tags/${{ version }}.tar.gz
  sha256: 9e85977f49dae20230f4865a4f879d819cbfaaf3797d22adef1407990eab66ff

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - ${{ compiler("c") }}
  - ${{ compiler('cxx') }}
  - pkg-config
  - python
  - cross-python_${{ target_platform }}
  host:
  - libpython
  - python
  - gmp
  - boost-cpp
  - openssl
  - sqlite
  - matplotlib
  - sympy
  - gmpy2

tests:
- package_contents:
    files:
    - lib/libcadabra2++.a
    - lib/libcadabra2++_static.a
    - include/cadabra2++/include/cadabra2++.hh


about:
  homepage: https://cadabra.science/
  license: GPL-3.0-only
  license_file: LICENSE
  summary: A field-theory motivated approach to computer algebra. 

extra:
  recipe-maintainers:
  - wangyenshu