#!/bin/bash
set -e

mkdir build
cd build

# Configure step
emcmake cmake ${CMAKE_ARGS} .. \
    -GNinja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_PREFIX_PATH=$PREFIX \
    -DCMAKE_INSTALL_PREFIX=$PREFIX \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DMINJA_TEST_ENABLED=OFF \
    -DMINJA_EXAMPLE_ENABLED=OFF

# Build step
emmake ninja install

# Install CMake config files (not generated by upstream CMakeLists.txt)
mkdir -p $PREFIX/lib/cmake/minja
cp ${RECIPE_DIR}/minjaConfig.cmake $PREFIX/lib/cmake/minja/
cp ${RECIPE_DIR}/minjaTargets.cmake $PREFIX/lib/cmake/minja/
