context:
  name: dolo
  version: 0.4.9.20

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/d/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: d9c41bc96fa31629289a0fcc0083be0df3076cae8bf9aee634f8d0006125b4d2
  patches:
  - patches/0001-support-python-313-build.patch
  - patches/0002-use-cpu-numba-target-on-emscripten.patch

build:
  number: 0
  script: ${PYTHON} -m pip install . ${PIP_ARGS}

  files:
    exclude:
    - '**/tests/**'
    - '**/__pycache__/**'
    - '**/*.pyc'
    - '**/test_*.py'
  python:
    skip_pyc_compilation:
    - '**/*.py'

requirements:
  build:
  - cross-python_${{ target_platform }}
  - python
  - pip
  host:
  - python
  - poetry-core
  run:
  - python
  - numpy >=2
  - pyyaml >=6,<7
  - interpolation >=2.2.7,<3
  - pandas >=2.2.2,<3
  - matplotlib-base >=3.6,<4
  - scipy >=1.11.1,<2
  - quantecon >=0.7.2,<1
  - xarray >=2024.1
  - multipledispatch >=0.6,<1
  - dolang >=0.0.21,<0.0.22
  - numba 0.66.*

tests:
- script: pytester
  files:
    recipe:
    - test_dolo.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run

about:
  homepage: https://www.econforge.org/dolo/
  repository: https://github.com/EconForge/dolo.py
  documentation: https://www.econforge.org/dolo.py/
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Economic modeling in Python

extra:
  recipe-maintainers:
  - anutosh491
  - albop
