context:
  version: 1.3.0
  name: r-rlang

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url:
  - https://cran.r-project.org/src/contrib/${{ name[2:] }}_${{ version }}.tar.gz
  - https://cloud.r-project.org/src/contrib/${{ name[2:] }}_${{ version }}.tar.gz
  sha256: 80aa537d49e72265f443a15e8936128af583caa5e572086518b503cbf064279c

build:
  number: 0
  script: $R CMD INSTALL $R_ARGS .

requirements:
  build:
  - cross-r-base_${{ target_platform }} ==${{ r_base }}
  - ${{ compiler('c') }}
  host:
  - r-base ==${{ r_base }}

tests:
- package_contents:
    lib:
    - R/library/${{ name[2:] }}/libs/${{ name[2:] }}.so

about:
  homepage: http://rlang.r-lib.org
  repository: https://github.com/r-lib/rlang
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Functions for Base Types and Core R and 'Tidyverse' Features
  description: |
    A toolbox for working with base types, core R features like the condition
    system, and core 'Tidyverse' features like tidy evaluation.
  license_family: GPL3

extra:
  recipe-maintainers:
  - IsabelParedes
