context:
  name: peewee
  version: 4.0.3

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: a3062505505e12cdf386066cda43d93a98f38a995dd9664cac0534378b2f6d1e

build:
  number: 0

  files:
    exclude:
    - '**/__pycache__/**'
    - '**/*.pyc'
    - '**/test_*.py'
  python:
    skip_pyc_compilation:
    - '**/*.py'
requirements:
  build:
  - ${{ compiler("c") }}
  - cross-python_emscripten-wasm32
  - pip
  - cython
  host:
  - python >=3.7
  - cffi
  - sqlite
  run:
  - python >=3.7
  - cffi

tests:
- script: pytester
  files:
    recipe:
    - test_peewee.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run
about:
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Python Object-Relational Mapping (ORM) library
  description: Peewee is a simple and small ORM. It has few (but expressive) concepts, making it easy to learn and 
    intuitive to use.
  documentation: https://github.com/coleifer/peewee/blob/master/docs/index.rst

  homepage: https://github.com/coleifer/peewee/
extra:
  recipe-maintainers:
  - michaelweinold
