context:
  name: galpy
  version: 1.11.2

package:
  name: ${{ name }}
  version: ${{ version }}

source:
- url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 5180a25743e6c8e5fbaffc1ff89f22940276b6341b2d3a9c4ca5e348eb071e5e

build:
  number: 2

  files:
    exclude:
    - '**/__pycache__/**'
    - '**/*.pyc'
    - '**/test_*.py'
  python:
    skip_pyc_compilation:
    - '**/*.py'

requirements:
  build:
  - ${{ compiler('c') }}
  - cross-python_${{ target_platform }}
  - python
  - pip
  - setuptools
  - numpy
  - cython
  host:
  - python
  - numpy
  - pip
  - gsl
  run:
  - python
  - packaging
  - numpy
  - scipy
  - matplotlib

tests:
- script: pytester
  files:
    recipe:
    - test_import_galpy.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Galactic Dynamics in python
  homepage: http://github.com/jobovy/galpy
  documentation: https://docs.galpy.org/

extra:
  recipe-maintainers:
  - IsabelParedes
