context:
  version: 0.1.1

package:
  name: xeus-shakespearelang
  version: ${{ version }}

source:
  url: https://github.com/DerThorsten/xeus-pywrap/archive/refs/tags/${{ version }}.tar.gz
  sha256: 6be2c4b922ef3c0cb0e4de82a04119490e05f5b60d08f9638f5ac27b22479f0d


build:
  number: 1

requirements:
  build:
  - ${{ compiler("cxx") }}
  - cmake >=4
  - ninja
  - python
  host:
  - python
  - libpython
  - nlohmann_json
  - nlohmann_json-abi
  - xeus
  - xeus-lite >=5.0.0
  - pybind11<3
  - pybind11_json
  - xtl
  - pyjs >=4.0.1
  - zstd
  - openssl < 4
  run: 
  - python
  - xeus-pywrap >=0.1.1
  - tatsu

tests:
- package_contents:
    files:
    - share/jupyter/kernels/xeus_shakespearelang/kernel.json
    - lib/python3.13/site-packages/xeus_shakespearelang/__init__.py

about:
  license: BSD-3-Clause
  license_family: BSD-3
  license_file: LICENSE
  summary: xeus-shakespearelang
  homepage: https://github.com/DerThorsten/xeus-pywrap

extra:
  recipe-maintainers:
  - DerThorsten