context:
  name: e-antic
  version: 2.1.1

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/flatsurf/e-antic/releases/download/${{ version }}/e-antic-${{ version }}.tar.gz
  sha256: e3287fa603b44d9a43c4cac5d883e65e90aedc35821061c1dc5b8d9c94a01cd8

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - cmake
  - ${{ compiler("c") }}
  - ${{ compiler('cxx') }}
  - pkg-config
  host:
  - gmp
  - boost-cpp
  - libflint

tests:
- package_contents:
    files:
    - lib/libeantic.a
    - include/e-antic/e-antic.h


about:
  homepage: https://flatsurf.github.io/e-antic/
  license: GPL-3.0-only OR LGPL-3.0-only
  license_file: 
  - COPYING
  - COPYING.LESSER
  summary: Embedded algebraic number fields 

extra:
  recipe-maintainers:
  - wangyenshu