context:
  name: parallelly
  version: 1.48.0

package:
  name: r-${{ name | lower }}
  version: ${{ version | replace('-', '_') }}

source:
  url:
  - https://cran.r-project.org/src/contrib/${{ name }}_${{ version }}.tar.gz
  - https://cloud.r-project.org/src/contrib/${{ name }}_${{ version }}.tar.gz
  - https://cran.r-project.org/src/contrib/Archive/${{ name }}/${{ name }}_${{ version }}.tar.gz
  sha256: 58fe71ccee8e4dc95591958c5428c5000350937024373b99b258a76da0927636

build:
  number: 0
  # skip: ${{ r_base == '4.6.1' }} ONLY IF NEEDED
  script: $R CMD INSTALL $R_ARGS .

requirements:
  build:
  - cross-r-base_${{ target_platform }} ==${{ r_base }}
  - ${{ compiler('c') }}
  host:
  - r-base ==${{ r_base }}

tests:
- package_contents:
    lib:
    - R/library/${{ name }}/libs/${{ name }}.so
- script: run_r_test test_${{ name }}.R
  files:
    recipe:
    - test_${{ name }}.R
  requirements:
    build:
    - r-wasm-tester

about:
  homepage: https://parallelly.futureverse.org
  documentation: https://cran.r-project.org/web/packages/${{ name }}/refman/${{ name }}.html
  repository: https://github.com/futureverse/parallelly
  license: LGPL-2.1-or-later
  license_file:
  - ${{ PREFIX }}/lib/R/share/licenses/LGPL-2.1
  summary: Enhancing the 'parallel' Package
  description: |-
    Utility functions that enhance the 'parallel' package and support the built-in parallel backends of the 'future' package.  For example, availableCores() gives the number of CPU cores available to your R process as given by the operating system, 'cgroups' and Linux containers, R options, and environment variables, including those set by job schedulers on high-performance compute clusters. If none is set, it will fall back to parallel::detectCores(). Another example is 'parallel::makeCluster(type = "RPSOCK")', which is backward compatible with 'parallel::makeCluster()' while doing a better job in setting up remote cluster workers without the need for configuring the firewall to do port-forwarding to your local computer.

extra:
  recipe-maintainers:
  - DerThorsten
