context:
  name: mpfi
  version: 1.5.2

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/passagemath/passagemath/releases/download/passagemath-10.8.1/mpfi-${{ version }}.tar.bz2
  sha256: c04f52cb306824b91b6d6eacf4f675b91fdee47c30f14d5b346dbfcd2492d274

build:
  number: 0

requirements:
  build:
  - ${{ compiler('c') }}
  - libtool
  - m4
  - make
  - gnuconfig
  host:
  - gmp
  - mpfr

tests:
- package_contents:
    files:
    - include/mpfi.h
    - lib/libmpfi.a

about:
  license: LGPL-3.0-only
  license_file: COPYING.LESSER
  summary: Multiple precision interval arithmetic library based on MPFR
  homepage: https://gitlab.inria.fr/mpfi/mpfi

extra:
  recipe-maintainers:
  - mkoeppe
