context:
  version: '1.6.0'
  build_number: 4

source:
  - path: bin
    target_directory: bin
  - path: pytester
    target_directory: pytester

build:
  number: ${{ build_number }}

outputs:
  - package:
      name: pytester
      version: ${{ version }}

    build:
      script: ./build.sh
      noarch: generic
    

    requirements:
      build:
        - python
      run:
        - python
        - microsoft::playwright
        - conda-forge::pyjs_code_runner 
    
    tests:
      - package_contents:
          strict: false
          files:
            - bin/pytester
            - lib/python*/site-packages/pytester/__init__.py
            - lib/python*/site-packages/pytester/__main__.py
            - lib/python*/site-packages/pytester/empack_config.yaml
            - lib/python*/site-packages/pytester/main_mount/main.py

  - package:
      name: pytester-run
      version: ${{ version }}
    build:
      noarch: generic
    requirements:
      run:
        - pyjs-dev
        - pytest
        - python 
    tests:
      - package_contents:
          strict: false
          files: []

about:
  license: MIT
  license_file: LICENSE.txt
  summary: test meta pkg

