context:
  version: '1.6.1'
  build_number: 3

source:
  - path: bin
    target_directory: bin
  - path: pytester
    target_directory: pytester

build:
  number: ${{ build_number }}

outputs:
  - package:
      name: pytester
      version: ${{ version }}

    build:
      script: ./build.sh
      noarch: generic
    

    requirements:
      build:
        - python
      run:
        - python
        - playwright <=  1.62.1 
        - playwright-python <=  1.62
        - pyjs_code_runner 
    
    tests:
      - package_contents:
          strict: false
          files:
            - bin/pytester
            - lib/python*/site-packages/pytester/__init__.py
            - lib/python*/site-packages/pytester/__main__.py
            - lib/python*/site-packages/pytester/empack_config.yaml
            - lib/python*/site-packages/pytester/main_mount/main.py
      - script: |
          python -c "from playwright._impl import _driver as d; import os; p=d.compute_driver_executable(); print(p); print(os.path.exists(p[0] if isinstance(p, (tuple, list)) else p))"


  - package:
      name: pytester-run
      version: ${{ version }}
    build:
      noarch: generic
    requirements:
      run:
        - pyjs-dev
        - pytest
        - python 
    tests:
      - package_contents:
          strict: false
          files: []

about:
  license: MIT
  license_file: LICENSE.txt
  summary: test meta pkg

