context:
  version: '1.6.0'
  build_number: 2

source:
  - path: bin
    target_directory: bin
  - path: pytester
    target_directory: pytester

outputs:
  - package:
      name: pytester
      version: ${{ version }}

    build:
      number: ${{ build_number }}
      script: ./build.sh
      noarch: generic

    requirements:
      host:
        - python
      run:
        - microsoft::playwright >= 1.58.0
        - conda-forge::pyjs_code_runner >= 3.2.0
    
    tests:
        - script:
          - test -f $PREFIX/bin/pytester
          - test -f $PREFIX/include/python$PY_VER/Python.h
          - test -f $PREFIX/lib/python$PY_VER/site-packages/pytester/main_mount/main.py

  - package:
      name: pytester-run
      version: ${{ version }}
    build:
      number: ${{ build_number }}
      noarch: generic
    requirements:
      run:
        - pyjs-dev
        - pytest
        - python 




about:
  license: MIT
  license_file: LICENSE.txt
  summary: test meta pkg

