context:
  name: cockle_fs
  version: 0.3.0

package:
  name: ${{ name }}
  version: ${{ version }}

build:
  number: 2

requirements:
  build:
  - ${{ compiler("c") }}
  - cmake
  - nodejs
  - typescript<6

tests:
- script: generic-testing
  requirements:
    build:
    - generic-testing
about:
  homepage: https://github.com/jupyterlite/cockle
  license: BSD-3-Clause
  license_file: LICENSE
  summary: fs for cockle
  documentation: https://github.com/jupyterlite/cockle

extra:
  recipe-maintainers:
  - DerThorsten
  - ianthomas23
