context:
  name: tornado
  version: 6.5.9

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/t/tornado/tornado-${{ version }}.tar.gz
  sha256: 4d868544ebdf2fc155239a74397f65ebfea9b4d3635296c96b5dfb0701c354f5

build:
  number: 0
  script: ${PYTHON} -m pip install . ${PIP_ARGS}

  files:
    exclude:
    - '**/*.pyi'
    - '**/test/**'
    - '**/__pycache__/**'
    - '**/*.pyc'
    - '**/test_*.py'
  python:
    skip_pyc_compilation:
    - '**/*.py'
requirements:
  build:
  - ${{ compiler("c") }}
  - cross-python_${{ target_platform }}
  - pip
  - python
  host:
  - python
  run:
  - python

tests:
- script: pytester
  requirements:
    build:
    - pytester >= 0.9.0
    run:
    - pytester-run >= 0.9.0
  files:
    recipe:
    - test_tornado.py
about:
  homepage: https://www.tornadoweb.org/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
  - ukukas
