context:
  version: "3.12.0"

package:
  name: flit-core
  version: ${{ version }}

source:
- url: https://pypi.io/packages/source/f/flit-core/flit_core-${{ version }}.tar.gz
  sha256: 18f63100d6f94385c6ed57a72073443e1a71a4acb4339491615d0f16d6ff01b2

build:
  number: 0
  noarch: generic
  script: ${PYTHON} -m pip install . --no-deps ${PIP_ARGS}

  files:
    exclude:
    - '**/__pycache__/**'
    - '**/*.pyc'
    - '**/test_*.py'
  python:
    skip_pyc_compilation:
    - '**/*.py'

requirements:
  build:
  - cross-python_${{ target_platform }}
  - python
  - pip
  host:
  - python
  run:
  - python

tests:
- script: pytester
  files:
    recipe:
    - test_flit_core.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Distribution-building parts of Flit
  homepage: https://github.com/pypa/flit

extra:
  recipe-maintainers:
  - Alex-PLACET
