context:
  version: 10.8.4

package:
  name: passagemath-polyhedra
  version: ${{ version }}

source:
- url: https://pypi.org/packages/source/p/passagemath-polyhedra/passagemath_polyhedra-${{ version }}.tar.gz
  sha256: 819b63c379439899813c9c289bd16321675b699021f7facd3dac97532e553d1a

build:
  number: 0
  script: ${{ PYTHON }} -m pip install .

requirements:
  build:
  - python
  - crossenv >=1.2
  - cross-python_emscripten-wasm32
  - ${{ compiler("c") }}
  - ${{ compiler("cxx") }}
  - pip
  - passagemath-setup
  - passagemath-environment
  - cython
  - gmpy2
  - cysignals
  - pkgconfig
  - numpy
  - passagemath-abi == ${{ version }}
  host:
  - python
  - gmp
  - mpfr
  - mpc
  - numpy
  - passagemath-modules
  run:
  - python
  - gmpy2
  - memory-allocator
  - cysignals
  - passagemath-glpk
  - passagemath-modules
  - passagemath-ppl

tests:
- script: pytester
  files:
    recipe:
    - test_passagemath_polyhedra.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run
    - passagemath-repl

about:
  license: GPL-2.0-or-later
  license_file: README.rst
  summary: 'passagemath: Convex polyhedra in arbitrary dimension, mixed integer linear optimization'
  description: |
    Distribution of a part of the Sage library for computations with convex polyhedra
    in arbitrary dimension (in exact rational arithmetic), and linear and mixed integer
    linear optimization (in floating point arithmetic).

extra:
  emscripten_tests:
    python:
      pytest_files:
      - test_passagemath_polyhedra.py
  recipe-maintainers:
  - mkoeppe
