context:
  name: patsy
  version: 1.0.3

package:
  name: patsy
  version: ${{ version }}

source:
- url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 79ebf4c93ff4d296e58a9d5be2b2ee31bd49d737cf11d70ffbd8a44b2de42e65

build:
  number: 0

  files:
    exclude:
    - '**/__pycache__/**'
    - '**/*.pyc'
    - '**/test_*.py'
  python:
    skip_pyc_compilation:
    - '**/*.py'

requirements:
  build:
  - cross-python_emscripten-wasm32
  - python
  - pip
  host:
  - python
  run:
  - numpy
  - six

tests:
- script: pytester
  files:
    recipe:
    - test_import_patsy.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run

about:
  homepage: https://github.com/pydata/patsy
  license: BSD-2-Clause AND PSF-2.0
  license_family: BSD
  license_file: LICENSE.txt
  summary: Describing statistical models in Python using symbolic formulas
  documentation: https://patsy.readthedocs.io
