context:
  name: zarr
  version: 3.2.1

package:
  name: ${{ name }}
  version: ${{ version }}

source:
- url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 71565b738a0e7e8ed226f0516eba8c6bb53440ad7669a8c48ebb3534a161d035
  patches:
  - patches/0001-Add-WASM-compatible-sync-for-Pyodide.patch
  - patches/0002-Set-threading.max_workers-1-on-WASM-in-config.patch
  - patches/0003-Fix-exclusive-atomic-writes-on-Emscripten.patch

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . ${{ PIP_ARGS }}

  files:
    exclude:
    - '**/__pycache__/**'
    - '**/*.pyc'
    - '**/test_*.py'
  python:
    skip_pyc_compilation:
    - '**/*.py'
requirements:
  build:
  - ${{ compiler('cxx') }}
  - cross-python_${{ target_platform }}
  - python
  - pip
  - hatchling
  - hatch-vcs
  host:
  - python
  run:
  - numpy
  - numcodecs
  - typing-extensions
  - donfig
  - google-crc32c
  - packaging

tests:
- script: pytester
  files:
    recipe:
    - test_import_zarr.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run

about:
  license: MIT
  license_file: LICENSE.txt
  summary: An implementation of chunked, compressed, N-dimensional arrays for Python
  homepage: https://github.com/zarr-developers/zarr-python
  documentation: https://zarr.readthedocs.io/
