context:
  version: 1.91.0

source:
- url: https://archives.boost.io/release/${{ version }}/source/boost_${{ version | replace('.', '_') }}.tar.bz2
  sha256: de5e6b0e4913395c6bdfa90537febd9028ea4c0735d2cdb0cd9b45d5f51264f5

build:
  number: 0

outputs:
- package:
    name: libboost-python
    version: ${{ version }}
  build:
    script: build.sh
    files:
      exclude:
      - '**/test/**'
  requirements:
    build:
    - ${{ compiler('cxx') }}
    - cross-python_${{ target_platform }}
    - python
    host:
    - boost-cpp
    - python
    run:
    - boost-cpp
    - python
  tests:
  - package_contents:
      files:
      - lib/libboost_python*.a

- package:
    name: libboost-python-example
    version: ${{ version }}
  build:
    script: build_example.sh
  requirements:
    build:
    - ${{ compiler('cxx') }}
    - cross-python_${{ target_platform }}
    - python
    - pip
    host:
    - ${{ pin_subpackage('libboost-python', exact=True) }}
    - python
    - pip
    run:
    - python
  tests:
  - script: pytester
    requirements:
      build:
      - pytester
      run:
      - pytester-run
    files:
      recipe:
      - test_mymodule.py

about:
  license: BSL-1.0
  license_file: LICENSE_1_0.txt
  summary: Boost.Python — C++/Python interoperability library (Emscripten build)
  homepage: http://www.boost.org/

extra:
  recipe-maintainers:
  - mmesch
