#!/usr/bin/env python3
"""Retarget Julia's system image IR from i686-linux-gnu to wasm32-unknown-emscripten.

The system image is generated by a 32-bit *native* bootstrap Julia (the wasm
build has no code generator), so it comes out as LLVM IR for i686. Both
targets are 32-bit little endian with the same Julia object layout
(MAX_ALIGN 8), so the module only needs its target strings swapped -- plus
two things that did not exist when julia-wasm was written against LLVM 9:

  * Julia's non-integral address spaces (10-13, used to track GC references)
    collide with the WebAssembly reference-type address spaces (10 = externref,
    20 = funcref, both 8 bits wide in the wasm data layout). Upstream Julia
    solved this later with the RemoveJuliaAddrspaces pass; this does the same
    on the textual IR: drop the address spaces, turn the now-degenerate
    addrspacecasts into bitcasts, and fix up the mangled intrinsic names.

  * x86 "target-cpu"/"target-features" function attributes, which the wasm
    backend would warn about for every function in the image.

Usage: retarget_sysimg.py <in.ll> <out.ll> [--datalayout DL] [--triple T]
"""

import argparse
import re
import sys

WASM_TRIPLE = "wasm32-unknown-emscripten"
WASM_DATALAYOUT = (
    "e-m:e-p:32:32-p10:8:8-p20:8:8-i64:64-i128:128-f128:64-n32:64-S128-ni:1:10:20"
)

# " addrspace(10)" / "addrspace(13)" -- Julia uses 10 (tracked), 11 (derived),
# 12 (callee-rooted) and 13 (loaded).
ADDRSPACE_RE = re.compile(r"\s*addrspace\(1[0-3]\)")
# Mangled pointer types inside intrinsic names: @llvm.memcpy.p0i8.p11i8.i32
INTRINSIC_PTR_RE = re.compile(r"(@llvm[\w.]*?)\.p1[0-3]([a-zA-Z0-9_])")
DECLARE_NAME_RE = re.compile(r"^declare[^@]*(@[\w.$\\\"]+)\(")
ATTR_STRIP_RE = re.compile(r'\s*"(?:target-cpu|target-features|probe-stack|stack-probe-size)"="[^"]*"')


def convert_code(part):
    """Rewrite a piece of IR that is not inside a string literal."""
    if "addrspace(1" in part:
        part = ADDRSPACE_RE.sub("", part)
        # `addrspacecast T* %x to T*` is invalid once the address spaces are
        # gone; a pointer bitcast is the identity we want instead.
        part = part.replace("addrspacecast", "bitcast")
    if "@llvm" in part:
        # apply repeatedly: names can mangle several pointer types
        while True:
            new = INTRINSIC_PTR_RE.sub(r"\1.p0\2", part)
            if new == part:
                break
            part = new
    return part


def convert_line(line):
    """Rewrite one line of textual IR."""
    if line.startswith("target datalayout"):
        return 'target datalayout = "%s"\n' % ARGS.datalayout
    if line.startswith("target triple"):
        return 'target triple = "%s"\n' % ARGS.triple
    if line.startswith("attributes #"):
        return ATTR_STRIP_RE.sub("", line)

    # The system image's data is a byte string that can contain anything,
    # including text that looks like IR ("addrspace(10)", "@llvm..."), and
    # rewriting inside it would corrupt the image. LLVM escapes quotes inside
    # string literals as \22, so splitting on '"' separates code from data.
    parts = line.split('"')
    for i in range(0, len(parts), 2):
        parts[i] = convert_code(parts[i])
    return '"'.join(parts)


def main():
    global ARGS
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("input")
    p.add_argument("output")
    p.add_argument("--triple", default=WASM_TRIPLE)
    p.add_argument("--datalayout", default=WASM_DATALAYOUT)
    ARGS = p.parse_args()

    seen_declares = set()
    n_lines = 0
    n_dropped = 0
    with open(ARGS.input, "r") as fin, open(ARGS.output, "w") as fout:
        for line in fin:
            n_lines += 1
            line = convert_line(line)
            if line.startswith("declare"):
                # dropping address spaces can make two declarations identical
                m = DECLARE_NAME_RE.match(line)
                if m:
                    if m.group(1) in seen_declares:
                        n_dropped += 1
                        continue
                    seen_declares.add(m.group(1))
            fout.write(line)
    print(
        "retargeted %s -> %s (%d lines, %d duplicate declarations dropped)"
        % (ARGS.input, ARGS.output, n_lines, n_dropped),
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
