context:
  version: 10.8.6

package:
  name: passagemath-symbolics
  version: ${{ version }}

source:
- url: https://pypi.org/packages/source/p/passagemath-symbolics/passagemath_symbolics-${{ version }}.tar.gz
  sha256: 1e7f7a9a7601affbdf391bd62230024b7fdb2246681c72c5468370187bb8e0dd

build:
  script: |
    export LDFLAGS="$LDFLAGS -Wl,--allow-multiple-definition"
    ${{ PYTHON }} -m pip install .
  number: 0

requirements:
  build:
  - python
  - crossenv >=1.2
  - cross-python_emscripten-wasm32
  - ${{ compiler("c") }}
  - ${{ compiler("cxx") }}
  - pip
  - passagemath-setup
  - passagemath-environment
  - cython
  - cysignals
  - pkgconfig
  - numpy
  - passagemath-abi == ${{ version }}
  host:
  - python
  - gmp
  - mpfr
  - mpc
  - gsl
  - libflint
  - ntl
  - singular
  - numpy
  - cysignals
  - memory-allocator
  - passagemath-categories
  - passagemath-environment
  - passagemath-modules
  run:
  - python
  - cysignals
  - memory-allocator
  - numpy
  - sympy
  - passagemath-categories
  - passagemath-environment
  - passagemath-flint
  - passagemath-gsl
  - passagemath-modules
  - passagemath-ntl

tests:
- script: pytester
  files:
    recipe:
    - test_passagemath_symbolics.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run
    - passagemath-repl

about:
  license: GPL-2.0-or-later
  license_file: README.rst
  summary: 'passagemath: Symbolic calculus'
  description: |
    Distribution of a part of the Sage library.
    It provides symbolic calculus based on Pynac, the fork of GiNaC,
    arithmetic, elementary, and special functions, asymptotic expansions,
    SageManifolds, and hyperbolic geometry.

extra:
  emscripten_tests:
    python:
      pytest_files:
      - test_passagemath_symbolics.py
  recipe-maintainers:
  - mkoeppe
