context:
  name: emscripten_emscripten-wasm32
  version: 6.0.6
  abi_version: 6.0.6

build:
  number: 0

outputs:
  - package:
      name: ${{ name }}
      version: ${{ version }}

    build:
      script: build_compiler_package.sh

    requirements:
      run:
        - emscripten-core == ${{ version }}
      run_exports:
        strong:
          - emscripten-abi == ${{ abi_version }}

    tests:
    - script: emcc -v



about:
  homepage: https://emscripten.org
  license: MIT
  license_file: LICENSE.txt
  summary: emscripten
  description: |
    Emscripten is a complete compiler toolchain to WebAssembly, using LLVM, with
    a special focus on speed, size, and the Web platform.
  documentation: https://emscripten.org/

extra:
  recipe-maintainers:
    - DerThorsten
