context:
  name: libprotobuf
  version: 7.35.0
  minor_version: ${{ (version | split('.'))[1] }}
  patch_version: ${{ (version | split('.'))[2] }}

package:
  name: ${{ name }}
  version: ${{ major_version }}.${{ version }}

source:
  url: https://github.com/protocolbuffers/protobuf/archive/refs/tags/v${{ minor_version }}.${{ patch_version }}.tar.gz
  sha256: e127ea69dd7be4e88abdd95845fb6c30d25d96971d95827e92b70e2e910d46a1

build:
  number: 0
  script: build.sh

requirements:
  build:
  - ${{ compiler('c') }}
  - ${{ compiler('cxx') }}
  - cmake
  - ninja
  host:
  - libabseil
  - zlib
  run:
  - libabseil
  - zlib

tests:
- package_contents:
    lib:
    - libprotobuf.a
    - libprotobuf-lite.a
    include:
    - google/protobuf/message.h
    - google/protobuf/descriptor.h
    - google/protobuf/descriptor.proto
- script:
  - bash build_tests.sh
  requirements:
    build:
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
  files:
    recipe:
    - build_tests.sh
    - tests/

about:
  homepage: https://protobuf.dev/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Protocol Buffers C++ Libraries
  description: |
    Protocol Buffers are a language-neutral, platform-neutral extensible
    mechanism for serializing structured data. This package provides the C++
    runtime libraries: libprotobuf and libprotobuf-lite.
  documentation: https://protobuf.dev/reference/cpp/
  repository: https://github.com/protocolbuffers/protobuf

extra:
  recipe-maintainers:
  - Alex-PLACET
