context:
  name: tree
  version: 2.3.2

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/Old-Man-Programmer/${{ name }}/archive/refs/tags/${{ version }}.tar.gz
  sha256: 22cf32e84e3eb508d97a9e991c2c3cc006b9dcf4afed201d96311c5c57d08fcf

build:
  number: 0

requirements:
  build:
  - ${{ compiler("c") }}
  - make

tests:
- package_contents:
    files:
    - bin/tree.js
    - bin/tree.wasm
- script: |
    OUTPUT=$(run_modularized $PREFIX/bin/tree.js --version)
    if [[ "$OUTPUT" != "tree v${{ version }} © 1996 - 2026 by Steve Baker, Thomas Moore, Francesc Rocher, Florian Sesser, Kyosuke Tokoro" ]]; then
      echo "Unexpected output: $OUTPUT"
      exit 1
    fi
  requirements:
    build:
    - run_modularized >= 0.1.2

about:
  license: GPL-2.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
  - ianthomas23
