context:
  name: sympow
  version: 2.023.7

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://gitlab.com/rezozer/forks/sympow/-/archive/v${{ version }}/sympow-v${{ version }}.tar.gz
  sha256: f19a2b428c573f9e4c36a97b736b562e76f4bfc354497abaeb7140632bef3400

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - ${{ compiler("c") }}
  - ${{ compiler('cxx') }}
  - pkg-config
  - autoconf-archive
  - help2man
  - pari
  host:
  - pari

tests:
  - package_contents:
      files:
        - bin/sympow

about:
  homepage: https://gitlab.com/rezozer/forks/sympow
  license: LicenseRef-sympow
  license_file: COPYING
  summary: SYMmetric POWer elliptic curve L-functions

extra:
  recipe-maintainers:
  - mkoeppe
