context:
  name: geos-static
  version: 3.15.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://download.osgeo.org/geos/geos-${{ version }}.tar.bz2
  sha256: d5e5192a686d065eaed082de14dd26244c5c8e02bff16b2c6cce3265f648e00e

build:
  number: 0

requirements:
  build:
  - cmake
  - make
  - ninja
  - ${{ compiler('c') }}
  - ${{ compiler('cxx') }}

tests:
- script:
  - test -f ${PREFIX}/include/geos.h
  - test -f ${PREFIX}/include/geos/algorithm/Area.h
  - test -f ${PREFIX}/lib/libgeos.a

about:
  homepage: https://libgeos.org/
  license: LGPL-2.1-only
  license_file: COPYING
  summary: Geometry Engine, Open Source
  description: |
    GEOS is a C++ library for performing operations on two-dimensional vector
    geometries. It is primarily a port of the JTS Topology Suite Java library.
    It provides many of the algorithms used by PostGIS, the Shapely package
    for Python, the sf package for R, and others.
  documentation: https://libgeos.org/
  repository: https://github.com/libgeos/geos

extra:
  recipe-maintainers:
  - DerThorsten
