context:
  name: regina-normal
  version: 7.3.1

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/3-manifolds/regina_wheels/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 9a42bd39c552982c22520dc2e247834351445de2832fcd789203cf3aa4fc4d57

build:
  number: 0

requirements:
  build:
  - python
  - cross-python_${{ target_platform }}
  - ${{ compiler('c') }}
  - ${{ compiler('cxx') }}
  - pip
  - setuptools
  - wheel
  host:
  - python
  - gmp
  - zlib
  - bzip2
  run:
  - python
  - gmp
  - zlib
  - bzip2

about:
  homepage: https://regina-normal.github.io/
  license: GPL-2.0-or-later
  license_file: README.rst
  summary: Self-contained Python packages of the low-dimensional topology software Regina, installable off PyPI using pip.

extra:
  recipe-maintainers:
  - wangyenshu
