context:
  name: lakers-python
  version: 0.6.2

package:
  name: ${{ name }}
  version: ${{ version }}

source:
- url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name|replace('-','_') }}-${{ version }}.tar.gz
  sha256: bc4dbe014161e4023a95affa93b9f3648f218acb6b1d99a5bc98dd7f676c5d56
  patches:
  - patches/0001-Fix-examples-path.patch

build:
  number: 0

  files:
    exclude:
    - '**/__pycache__/**'
    - '**/*.pyc'
    - '**/test_*.py'
  python:
    skip_pyc_compilation:
    - '**/*.py'

requirements:
  build:
  - cross-python_${{ target_platform }}
  - cffi
  - setuptools-rust
  - rust-nightly
  - maturin
  host:
  - python
  - cffi
  run:
  - cffi

tests:
- script: pytester
  requirements:
    build:
    - pytester
    run:
    - pytester-run
  files:
    recipe:
    - test_import_lakers.py

about:
  summary: Python wrapper for the lakers crate (EDHOC implementation in Rust)
  license: BSD-3-Clause
  license_file: LICENSE.md
  homepage: https://crates.io/crates/lakers
  repository: https://github.com/lake-rs/lakers
