context:
  name: cramjam
  version: 2.12.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 0471df877499536dfdd03036944ab36053e7636586576037557e86725d050416

build:
  number: 0

  files:
    exclude:
    - '**/__pycache__/**'
    - '**/*.pyc'
    - '**/test_*.py'
  python:
    skip_pyc_compilation:
    - '**/*.py'
requirements:
  build:
  - python
  - cross-python_${{ target_platform }}
  - maturin
  - toml
  - rust-nightly
  - ${{ compiler('cxx') }}
  host:
  - python
  - pip
  run:
  - python

tests:
- script: pytester
  files:
    recipe:
    - test_cramjam.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run

about:
  homepage: https://github.com/milesgranger/cramjam
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: python bindings to rust-implemented compression
  description: |
    Extremely thin Python bindings to de/compression algorithms in Rust.
  documentation: https://docs.rs/cramjam

extra:
  recipe-maintainers:
  - milesgranger
