context:
  name: iml
  version: 1.0.5

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: http://www.cs.uwaterloo.ca/~astorjoh/iml-${{ version }}.tar.bz2
  sha256: 1dad666850895a5709b00b97422e2273f293cfadea7697a9f90b90953e847c2a

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - ${{ compiler('c') }}
  - ${{ compiler('cxx') }}
  - pkg-config
  - autoconf-archive
  host:
  - gmp
  - openblas

tests:
- package_contents:
    files:
    - lib/libiml.a
    - include/iml.h

about:
  homepage: https://cs.uwaterloo.ca/~astorjoh/iml.html
  license: GPL-2.0-only
  license_file: COPYING
  summary: IML is a free library of C source code which implements algorithms for computing exact solutions to dense systems of linear equations over the integers.

extra:
  recipe-maintainers:
  - wangyenshu