context:
  name: findutils
  version: 4.10.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://ftp.gnu.org/gnu/${{ name }}/${{ name }}-${{ version }}.tar.xz
  sha256: 1387e0b67ff247d2abde998f90dfbf70c1491391a59ddfecb8ae698789f0a4f5

build:
  number: 0

requirements:
  build:
  - ${{ compiler("c") }}
  - make
  - autoconf

tests:
- script: generic-testing
  requirements:
    build:
    - generic-testing
about:
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
  - ianthomas23
