name: Build macOS Recipes

on:
  push:
    branches:
      - "emscripten-6x"
    paths:
      - "recipes/recipes_native/**"
      # - ".github/workflows/build_recipes_macos.yaml"
      # - ".github/workflows/reusable_build_recipes.yaml"
  pull_request:
    paths:
      - "recipes/recipes_native/**"
      # - ".github/workflows/build_recipes_macos.yaml"
      # - ".github/workflows/reusable_build_recipes.yaml"

permissions:
  contents: read
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/reusable_build_recipes.yaml
    with:
      os: macos-latest
      wasm-arch: None
      subdir: recipes_native
    secrets: inherit
