context:
  name: spatialgeometry
  version: 1.3.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/spatialgeometry-${{version }}.tar.gz
  sha256: 493627df64dd616f343008f13704200f47c1bac2f63d95b867dc9b76b7e29570

build:
  number: 0
  script: ${PYTHON} -m pip install . -vvv

  files:
    exclude:
    - '**/__pycache__/**'
    - '**/*.pyc'
  python:
    skip_pyc_compilation:
    - '**/*.py'

requirements:
  build:
  - ${{ compiler('c') }}
  - ${{ compiler('cxx') }}
  - cross-python_${{ target_platform }}
  - numpy
  - pip
  - scikit-build-core >=0.9
  - nanobind >=2
  host:
  - numpy
  - python
  run:
  - python
  - spatialmath-python >=1.0.0
  - numpy

tests:
- script: pytester
  requirements:
    build:
    - pytester
    run:
    - pytester-run
  files:
    recipe:
    - test_spatialgeometry.py

about:
  summary: A Shape and Geometry Package
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/jhavl/spatialgeometry

extra:
  recipe-maintainers:
  - IsabelParedes
