context:
  name: libflint
  version: 3.6.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/flintlib/flint/releases/download/v${{ version }}/flint-${{ version }}.tar.gz
  sha256: b95e2c7792f5eea4a1c8d2d42c4098434756832e57a094b295eb5dfdc9b4c36b
  patches:
  - patches/0001-src-generic_files-profiler.c-__EMSCRIPTEN__-Do-not-u.patch
  - patches/0001-src-ulong_extras-is_square.c-Make-mod-63-64-65-stati.patch

build:
  number: 1

requirements:
  build:
  - ${{ compiler('c') }}
  - libtool
  - m4
  - make
  - gnuconfig
  host:
  - gmp
  - mpfr

tests:
- package_contents:
    files:
    - include/flint/flint.h
    - lib/libflint.a

about:
  license: GPL-3.0-or-later OR LGPL-3.0-or-later
  license_file: COPYING
  summary: Fast Library for Number Theory
  homepage: http://www.flintlib.org

extra:
  recipe-maintainers:
  - mkoeppe
