context:
  name: mathic
  version: '1.5'

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url:
  - https://github.com/Macaulay2/mathic/releases/download/v${{ version }}/mathic-${{ version }}.tar.gz
  sha256: 42acb4886bdae84e3117aca52ec63b64693cbd0c7e3ca288fc789661d556ea20

build:
  number: 0

requirements:
  build:
  - autoconf
  - automake
  - libtool
  - make
  - pkg-config
  - ${{ compiler('cxx') }}
  host:
  - memtailor

tests:
- package_contents:
    files:
    - lib/libmathic.a
    - include/mathic.h

about:
  repository: https://github.com/Macaulay2/mathic
  license: LGPL-2.0-or-later
  license_file:
  - lgpl-2.0.txt
  - lgpl-2.1.txt
  - lgpl-3.0.txt
  summary: Mathic is a C++ library of fast data structures designed for use in Groebner basis computation.

extra:
  recipe-maintainers:
  - wangyenshu
